
--[[
	IX-Ray Module Signals
	Version: 1.0
	Author: FFx0001
	Script: ixr_module_signals.script
	Description: Module for centralized subscribes to game callbacks automatically callable in subscribed script on event called in external scripts
	
	Override options:
		script: __ixr_override_signals_intercepts.script
		auto callable function: configure(ixr_signals) then ixr_signals.add_intercept("event_name", {flat array string arg names}) end
	
	Public exports:
		get_module_info()
		init()
		is_initialized()
		add_intercept(name, args_map)
		remove_intercept(name)
		subscribe_to_event(name, func_or_userdata)
		callback_set(name, func_or_userdata)
		un_subscribe_from_event(name, func_or_userdata)
		callback_unset(name, func_or_userdata)
		send_event(name, ...)
		make_callback(name, ...)
]]

local ixr_signals = {
	intercepts = {},
	initialized = false,
	use_file_log = true,
	use_console_log = false,
}


-- #######################################
-- #	 	 PUBLIC METHODS 	  	 	 #
-- #######################################

--[[
Description: Module management. Returns metadata about the module.
Return: (table) - A table containing module information such as alias name, category, version, authors, and description.
]]
function get_module_info()
	return {
		-- (string) constant module name independent of the script name, which will be centralized via ixr_framework.get_module("alias_name") to maintain module versioning without the need to access the script name during integration.
		alias_name = "ixr_signals",
		
		-- (string) use once value at range or custom latin snake case name default categories: ["ixr_system", "sub_system", "sub_gameplay", "sub_utils"] use for ordering init calls at 1 to last ASC
		category = "ixr_system",
		
		-- (float) value for controll versions
		version = 1.0,
		
		-- (string) public exposed function name, allowed in this script for auto init module
		init_function_name = "init",
		
		-- (string|string[]) code author(s) nick name(s)
		authors = "FFx0001",
		
		-- (string) short description about module
		description = "Module for centralized subscribes to game callbacks automatically callable in subscribed script on event called in external scripts",
	}
end

--[[
Description: Initializes the module and sets up necessary configurations.
Return: (bool) - Returns true if the module was successfully initialized.
]]
function init()
	return ixr_signals.init()
end

--[[
Description: Checks whether the module has been initialized.
Return: (bool) - Returns true if the module is initialized, otherwise false.
]]
function is_initialized()
	return ixr_signals.is_initialized()
end

--[[
Description: Adds a new event type to the interception system.
Parameters:
  name (string)(required) - The name of the event to intercept.
  args_map (table)(optional) - A table mapping argument names for the event.
Return: (bool) - Returns true if the event type was successfully added.
]]
function add_intercept(name, args_map)
	return ixr_signals.add_intercept(name, args_map)
end

--[[
Description: Removes an event type from the interception system.
Parameters:
  name (string)(required) - The name of the event to remove.
Return: (bool) - Returns true if the event type was successfully removed.
]]
function remove_intercept(name)
	return ixr_signals.remove_intercept(name)
end

--[[
Description: Subscribes a function or userdata to a specified event.
Parameters:
  name (string)(required) - The name of the event to subscribe to.
  func (function|userdata)(required) - The function or userdata to be called when the event is triggered.
Return: (bool) - Returns true if the subscription was successful.
]]
function subscribe_to_event(name, func_or_userdata)
	return ixr_signals.subscribe_to_event(name, func_or_userdata)
end

--[[
Description: Alias for subscribing to an event.
Parameters:
  name (string)(required) - The name of the event to subscribe to.
  func (function|userdata)(required) - The function or userdata to be called when the event is triggered.
Return: (bool) - Returns true if the subscription was successful.
]]
function callback_set(name, func_or_userdata)
	return ixr_signals.subscribe_to_event(name, func_or_userdata)
end

--[[
Description: Unsubscribes a function or userdata from a specified event.
Parameters:
  name (string)(required) - The name of the event to unsubscribe from.
  func (function|userdata)(required) - The function or userdata to be removed from the subscription.
Return: (bool) - Returns true if the unsubscription was successful.
]]
function un_subscribe_from_event(name, func_or_userdata)
	return ixr_signals.un_subscribe_from_event(name, func_or_userdata)
end

--[[
Description: Alias for unsubscribing from an event.
Parameters:
  name (string)(required) - The name of the event to unsubscribe from.
  func (function|userdata)(required) - The function or userdata to be removed from the subscription.
Return: (bool) - Returns true if the unsubscription was successful.
]]
function callback_unset(name, func_or_userdata)
	return ixr_signals.un_subscribe_from_event(name, func_or_userdata)
end

--[[
Description: Sends an event to all subscribers.
Parameters:
  name (string)(required) - The name of the event to send.
  ... (vararg) - Additional parameters to pass to the event handlers.
Return: (void) - No return value.
]]
function send_event(name, ...)
	return ixr_signals.send_event(name, ...)
end

--[[
Description: Alias for sending an event to subscribers.
Parameters:
  name (string)(required) - The name of the event to send.
  ... (vararg) - Additional parameters to pass to the event handlers.
Return: (void) - No return value.
]]
function make_callback(name, ...)
	return ixr_signals.send_event(name, ...)
end

-- #######################################
-- #	 	 IX-Ray INTERCEPTS 	  	 	 #
-- #######################################
function ixr_signals.load_addons_intercepts()
	ixr_signals.toLog("\n[IXR SIGNALS] LOAD IXR ADDONS INTERCEPT SETTINGS\n", false)
	
	--// IXR addons
	ixr_signals.add_intercept("update",                          		{"delta_number"}) -- actor
	ixr_signals.add_intercept("load",                            		{"net_packet"}) -- actor
	ixr_signals.add_intercept("save",                            		{"net_packet"}) -- actor
	
	ixr_signals.add_intercept("save_file_loaded",                     	{"dir_path_string", "file_name_string"})
	ixr_signals.add_intercept("save_file_created",                		{"dir_path_string", "file_name_string"})
	ixr_signals.add_intercept("new_game_created",                       {"dir_path_string", "file_name_string"})
	ixr_signals.add_intercept("actor_on_spawn",                   		{})
end


-- #######################################
-- #	 	 DEFAULT INTERCEPTS 	  	 #
-- #######################################
function ixr_signals.load_default_intercepts()
	ixr_signals.load_addons_intercepts()
	ixr_signals.toLog("\n[IXR SIGNALS] LOAD DEFAULT SETTINGS\n", false)
	
	ixr_signals.add_intercept("level_input_on_key_press",				{})	
	ixr_signals.add_intercept("on_key_press",                         	{"dik_key_number"})	
	ixr_signals.add_intercept("on_key_release",                     	{"dik_key_number"})	
	ixr_signals.add_intercept("on_key_hold",                          	{"dik_key_number"})	
	
	ixr_signals.add_intercept("on_mouse_move",                        	{"dx_number", "dy_number"})	
	ixr_signals.add_intercept("on_mouse_wheel",                      	{"direction_number"})	 
	
	ixr_signals.add_intercept("on_actor_wnd_mode_switch",          		{"wnd_mode_number"}) -- 0 (Undefined) | 1 (Inventory) | 2 (Trade) | 3 (Upgrade) | 4 (DeadBodySearch) | 10 (Talk dialog  show) | 11 (Talk dialog  hide)

	ixr_signals.add_intercept("on_actor_wnd_closed",          			{"wnd_mode_number"})
	ixr_signals.add_intercept("on_actor_wnd_opened",          			{"wnd_mode_number"})	
	
	ixr_signals.add_intercept("on_actor_inventory_wnd_opened",			{"wnd_mode_number"})
	ixr_signals.add_intercept("on_actor_inventory_wnd_closed",     		{"wnd_mode_number"})
	
	ixr_signals.add_intercept("on_actor_trade_wnd_opened",   			{"wnd_mode_number"})
	ixr_signals.add_intercept("on_actor_trade_wnd_closed",    			{"wnd_mode_number"})
	
	ixr_signals.add_intercept("on_actor_upgrade_wnd_opened",  			{"wnd_mode_number"})
	ixr_signals.add_intercept("on_actor_upgrade_wnd_closed",   			{"wnd_mode_number"})
	
	ixr_signals.add_intercept("on_actor_dead_body_search_wnd_opened",	{"wnd_mode_number"})	
	ixr_signals.add_intercept("on_actor_dead_body_search_wnd_closed", 	{"wnd_mode_number"})
	
	ixr_signals.add_intercept("on_actor_dialog_wnd_showed",    			{"wnd_mode_number", "npc_id_number_or_nil"})	
	ixr_signals.add_intercept("on_actor_dialog_wnd_closed",  			{"wnd_mode_number", "npc_id_number_or_nil"})	
	
	
	ixr_signals.add_intercept("on_before_level_changing",       		{"net_packet"}) -- engine
	ixr_signals.add_intercept("on_level_changing",              		{}) -- actor binder
	ixr_signals.add_intercept("on_item_take",                   		{"item_game_object", "is_actor_exists_bool"}) -- actor
	ixr_signals.add_intercept("on_item_drop",             				{"item_game_object", "is_actor_exists_bool"}) -- actor
	
	ixr_signals.add_intercept("actor_on_spawn",                   		{})	-- ingame first update with actor
	ixr_signals.add_intercept("actor_on_init",                   		{"binder_ref"}) 
	ixr_signals.add_intercept("actor_on_reinit",                 		{"binder_ref"}) 
	ixr_signals.add_intercept("actor_on_save",                   		{"net_packet"}) 
	ixr_signals.add_intercept("actor_on_load",                   		{"net_packet"}) 
	ixr_signals.add_intercept("actor_on_level_changing",              	{}) 
	ixr_signals.add_intercept("actor_on_before_death",          		{"who_id_number", "flags_table"}) -- { ret_value = true } switch to false for ignore death
	ixr_signals.add_intercept("actor_on_death",          				{"victim_game_object", "who_game_object"})  
	ixr_signals.add_intercept("actor_on_net_destroy",           		{"binder_ref"}) 
	ixr_signals.add_intercept("actor_on_first_update",          		{"binder_ref", "delta_number"}) 
	ixr_signals.add_intercept("actor_on_update",                 		{"binder_ref", "delta_number"}) 
	ixr_signals.add_intercept("actor_on_weapon_fired",          		{"npc_game_object", "wpn_game_object", "iAmmoElapsed_bool", "ammo_type_number"}) 
	ixr_signals.add_intercept("actor_on_weapon_jammed",         		{"wpn_game_object"}) 
	ixr_signals.add_intercept("actor_on_weapon_no_ammo",        		{"wpn_game_object", "ammo_total_number"}) 
	ixr_signals.add_intercept("actor_on_weapon_no_avialable_ammo",		{"wpn_game_object", "suitable_ammo_total_number"}) -- eWeaponNoAmmoAvailable
	ixr_signals.add_intercept("actor_on_weapon_reload",         		{"wpn_game_object", "suitable_ammo_total_number"}) -- eWeaponNoAmmoAvailable копия вызова actor_on_weapon_no_avialable_ammo отсутствие патронов не означает что это перезарядка
	ixr_signals.add_intercept("actor_on_weapon_zoom_in",        		{"wpn_game_object"}) 
	ixr_signals.add_intercept("actor_on_weapon_zoom_out",       		{"wpn_game_object"}) 
	ixr_signals.add_intercept("actor_on_item_take",             		{"item_game_object", "before_transfer_parent_id_number", "is_take_from_ground_bool"}) 
	ixr_signals.add_intercept("actor_on_item_take_from_box",    		{"box_game_object", "item_game_object"}) 
	ixr_signals.add_intercept("actor_on_item_take_from_ground", 		{"item_game_object"}) 
	ixr_signals.add_intercept("actor_on_item_drop",             		{"item_game_object"}) 
	ixr_signals.add_intercept("on_before_item_use",                    	{"npc_game_object", "item_game_object", "table"})  -- { ret_value = true }
	ixr_signals.add_intercept("actor_on_item_before_use",       		{"npc_game_object", "item_game_object", "table"}) --  { ret_value = true }
	ixr_signals.add_intercept("actor_on_item_use",              		{"item_game_object", "item_section_string"}) 
	ixr_signals.add_intercept("actor_item_to_belt",             		{"item_game_object"}) 
	ixr_signals.add_intercept("actor_item_to_ruck",             		{"item_game_object"}) 
	ixr_signals.add_intercept("actor_item_to_slot",             		{"item_game_object"}) 
	ixr_signals.add_intercept("actor_on_trade",                 		{"item_game_object", "sell_bye_bool", "money_number"}) 
	ixr_signals.add_intercept("actor_on_info_callback",         		{"npc_game_object", "info_id_number"})  
	ixr_signals.add_intercept("actor_on_before_hit",             		{"sHit_struct", "bone_id_number", "flags_table"}) -- { ret_value = true }  switch to false for ignore hit
	ixr_signals.add_intercept("actor_on_hit_callback",          		{"game_object", "number", "vector", "game_object", "number"})
	ixr_signals.add_intercept("actor_on_torch_enabled",         		{"nil_or_device_torch_game_object"}) 
	ixr_signals.add_intercept("actor_on_torch_disabled",        		{"nil_or_device_torch_game_object"}) 
	ixr_signals.add_intercept("actor_on_attach_vehicle",        		{"vechicle_game_object"}) 
	ixr_signals.add_intercept("actor_on_detach_vehicle",        		{"vechicle_game_object"}) 
	ixr_signals.add_intercept("actor_on_use_vehicle",           		{"vechicle_game_object"}) 
	ixr_signals.add_intercept("actor_on_hud_animation_end",     		{"item_game_object", "hud_section_string", "m_current_motion_string", "state_number", "animation_slot_number"}) -- не полностью соответствует варианту из anomaly-coc ("game_object", "string", "bool", "bool", "number")
	ixr_signals.add_intercept("actor_on_before_sleep",               	{"hours_number"}) 
	ixr_signals.add_intercept("actor_on_sleep",                  		{"hours_number"}) 
	ixr_signals.add_intercept("actor_on_interaction",            		{"string", "game_object", "string"}) 
	ixr_signals.add_intercept("actor_on_leave_dialog",           		{"npc_id_number"}) 
	ixr_signals.add_intercept("actor_on_foot_step",              		{"alife_game_object", "power_number", "play_bool", "on_ground_bool", "hud_view_bool"}) 
	ixr_signals.add_intercept("actor_on_footstep",                		{"alife_game_object", "power_number", "play_bool", "on_ground_bool", "hud_view_bool"}) -- replicated actor_on_foot_step
	ixr_signals.add_intercept("actor_on_article",             			{"npc_game_object", "article_group", "article_name"}) 

	ixr_signals.add_intercept("npc_on_use",                       		{"target_game_object", "initiator_game_object"}) 
	ixr_signals.add_intercept("npc_on_item_take",                 		{"npc_game_object", "item_game_object"}) 
	ixr_signals.add_intercept("npc_on_item_take_from_box",        		{"npc_game_object", "box_game_object", "item_game_object"}) 
	ixr_signals.add_intercept("npc_on_item_drop",                  		{"npc_game_object", "item_game_object"}) 
	ixr_signals.add_intercept("npc_on_net_spawn",                  		{"npc_game_object", "npc_server_object"}) 
	ixr_signals.add_intercept("npc_on_net_destroy",                		{"npc_game_object"}) 
	ixr_signals.add_intercept("npc_on_update",                     		{"npc_game_object", "db_storage_table"}) 
	ixr_signals.add_intercept("npc_on_hit_callback",               		{"npc_game_object", "power_number", "hit_direction_vector", "who_game_object", "bone_index_number"}) 
	ixr_signals.add_intercept("npc_on_death_callback",             		{"npc_game_object", "who_game_object"}) 
	ixr_signals.add_intercept("npc_on_fighting_actor",             		{"npc_game_object"}) 
	ixr_signals.add_intercept("npc_on_weapon_strapped",            		{"npc_game_object", "wpn_game_object"}) 
	ixr_signals.add_intercept("npc_on_weapon_unstrapped",          		{"npc_game_object", "wpn_game_object"}) -- мутная логика потом перепроверить позицию коллбека в коде
	ixr_signals.add_intercept("npc_on_weapon_drop",                 	{"npc_game_object", "wpn_game_object"}) 
	ixr_signals.add_intercept("npc_on_hear_callback",              		{"npc_game_object", "who_npc_id_number", "sound_type_number_or_string", "sound_distance_number", "sound_power_number", "sound_position_vector", "raw_sound_type_number"}) 
	ixr_signals.add_intercept("npc_on_get_all_from_corpse",        		{"npc_game_object", "corpse_game_object", "item_game_object", "is_in_loot_table_bool"}) 
	ixr_signals.add_intercept("npc_on_eval_danger",                 	{"npc_game_object", "flags_table"}) -- {ret_value = true} switch to false for npc ignore danger

	ixr_signals.add_intercept("monster_on_update",                 		{"monster_game_object", "self_st_table"}) 
	ixr_signals.add_intercept("monster_on_hit_callback",           		{"monster_game_object", "power_number", "hit_direction_vector", "who_game_object", "bone_index_number"}) 
	ixr_signals.add_intercept("monster_on_net_spawn",             		{"monster_game_object", "monster_server_object"}) 
	ixr_signals.add_intercept("monster_on_net_destroy",            		{"monster_game_object"}) 
	ixr_signals.add_intercept("monster_on_death_callback",         		{"monster_game_object", "who_game_object"}) -- without poltergeist
	ixr_signals.add_intercept("monster_on_death",         				{"monster_game_object", "who_game_object"}) 
	ixr_signals.add_intercept("monster_on_actor_use_callback",     		{"monster_game_object", "who_game_object"}) 
	ixr_signals.add_intercept("monster_on_use",     					{"monster_game_object", "who_game_object", "is_alive_bool"}) 

	ixr_signals.add_intercept("crow_on_net_spawn",             			{"crow_game_object", "monster_server_object"}) 
	ixr_signals.add_intercept("crow_on_net_destroy",            		{"crow_game_object"}) 
	ixr_signals.add_intercept("crow_on_update",                 		{"crow_game_object", "self_st_table"}) 
	ixr_signals.add_intercept("crow_on_death",         					{"crow_game_object", "who_game_object"}) 

	ixr_signals.add_intercept("physic_object_on_death",     			{"game_object", "game_object"}) 
	ixr_signals.add_intercept("physic_object_on_use",     				{"physic_game_object", "who_game_object"}) 
	ixr_signals.add_intercept("physic_object_on_use_callback",     		{"physic_game_object", "who_game_object"}) 
	ixr_signals.add_intercept("physic_object_on_hit",     				{"physic_game_object", "power_number", "hit_direction_vector", "who_game_object", "bone_index_number"}) 
	ixr_signals.add_intercept("physic_object_on_hit_callback",     		{"physic_game_object", "power_number", "hit_direction_vector", "who_game_object", "bone_index_number"}) 
	
	ixr_signals.add_intercept("heli_on_hit_callback",              		{"heli_game_object", "power_number", "nil", "who_game_object", "nil"}) 
	
	ixr_signals.add_intercept("squad_on_npc_creation",             		{"squad_server_object", "npc_server_object", "spawn_smart_server_object"}) 
	ixr_signals.add_intercept("squad_on_enter_smart",              		{"squad_server_object", "smart_server_object"}) 
	ixr_signals.add_intercept("squad_on_leave_smart",              		{"squad_server_object", "old_smart_server_object"}) 
	ixr_signals.add_intercept("squad_on_npc_death",                		{"squad_server_object", "npc_server_object", "killer_server_object"})
	ixr_signals.add_intercept("squad_on_update",                    	{"squad_server_object"}) 
	ixr_signals.add_intercept("squad_on_first_update",              	{"squad_server_object"}) 
	ixr_signals.add_intercept("squad_on_add_npc",                   	{"squad_server_object", "npc_server_object", "spawn_section_string", "spawn_position_vector", "lv_id_number", "gv_id_number"})
	ixr_signals.add_intercept("squad_on_register",                  	{"squad_server_object"}) 
	ixr_signals.add_intercept("squad_on_unregister",                	{"squad_server_object"}) 
	ixr_signals.add_intercept("squad_on_after_game_vertex_change",  	{"squad_server_object", "last_gvid_number", "m_game_vertex_id_number", "is_level_changed_bool"}) 
	ixr_signals.add_intercept("squad_on_after_level_change",        	{"squad_server_object", "level_name_string", "cur_lvl_string"}) 

	ixr_signals.add_intercept("smart_terrain_on_update",            	{"smart_terrain_server_object"}) 
	ixr_signals.add_intercept("on_try_respawn",                      	{"smart_terrain_server_object", "table"}) -- {disabled = false} switch to true for break

	ixr_signals.add_intercept("server_entity_on_register",          	{"server_object", "string"}) -- se_actor, se_artefact, se_car, se_heli, se_outfit, se_helmet, se_weapon, se_weapon_shotgun, se_weapon_automatic_shotgun, se_weapon_magazined, se_weapon_magazined_w_gl, se_item, se_item_torch, se_physic, se_lamp, se_ammo, se_grenade, se_eatable, se_invbox, se_explosive, se_pda, se_detector, se_mgun, se_level_changer, se_monster, se_smart_cover, se_stalker, se_trader, se_zone_anom, se_zone_torrid, se_zone_visual, se_restrictor, sim_squad_scripted, se_smart_terrain
	ixr_signals.add_intercept("server_entity_on_unregister",           	{"server_object", "string"}) -- se_actor", se_artefact, se_car, se_heli, se_outfit, se_helmet, se_weapon, se_weapon_shotgun, se_weapon_automatic_shotgun, se_weapon_magazined, se_weapon_magazined_w_gl, se_item, se_item_torch, se_physic, se_lamp, se_ammo, se_grenade, se_eatable, se_invbox, se_explosive, se_pda, se_detector, se_mgun, se_level_changer, se_monster, se_smart_cover, se_stalker, se_trader, se_zone_anom , se_zone_torrid, se_zone_visual, se_restrictor, sim_squad_scripted, se_smart_terrain                   
	ixr_signals.add_intercept("fill_start_position",                  	 {}) 
	ixr_signals.add_intercept("se_stalker_on_spawn",                   	{"server_object"}) 
	ixr_signals.add_intercept("se_actor_on_register",                  	{"server_object"}) 
	ixr_signals.add_intercept("se_actor_on_unregister",                	{"server_object"}) 
	ixr_signals.add_intercept("se_actor_on_STATE_Write",               	{"server_object", "net_packet"}) 
	ixr_signals.add_intercept("se_actor_on_STATE_Read",                	{"server_object", "net_packet", "size_number"}) 

	ixr_signals.add_intercept("map_spot_menu_add_property",           	{"property_CUIWindow", "id_number", "level_name_string", "hint_string"}) -- возможно есть дуликат вызова
	ixr_signals.add_intercept("map_spot_menu_property_clicked",        	{"property_CUIWindow", "map_spot_property_id_number", "map_spot_property_level_name_string", "prop_string"}) -- возможно есть дуликат вызова
	ixr_signals.add_intercept("main_menu_on_keyboard",                 	{"dik_number", "keyboard_action_number", "CUIScriptWnd", "is_level_present_bool"}) 
	ixr_signals.add_intercept("main_menu_on_init",                     	{"CUIScriptWnd"}) -- 1
	ixr_signals.add_intercept("main_menu_on_init_controlls",    		{"CUIScriptWnd"}) -- 2
	ixr_signals.add_intercept("main_menu_on_init_callbacks",           	{"CUIScriptWnd"}) -- 3
	ixr_signals.add_intercept("main_menu_on_quit",                     	{"CUIScriptWnd"}) -- 4

	ixr_signals.add_intercept("on_game_load",                         	{"binder"}) -- actor net_spawn
	ixr_signals.add_intercept("on_console_execute",                   	{"string", "string", "string", "..."})
	ixr_signals.add_intercept("on_before_save_input",                  	{"number", "number", "table"})
	ixr_signals.add_intercept("on_before_load_input",                  	{"number", "number", "table"})

	ixr_signals.add_intercept("save_state",                           	{"table"}) 
	ixr_signals.add_intercept("load_state",                            	{"table"}) 
	ixr_signals.add_intercept("on_pstor_save_all",                     	{"obj_game_object", "net_packet"}) -- is USE_MARSHAL
	ixr_signals.add_intercept("on_pstor_load_all",                    	{"obj_game_object", "reader"}) -- is USE_MARSHAL

	ixr_signals.add_intercept("on_enemy_eval",                        	{"game_object", "game_object", "table"})
	ixr_signals.add_intercept("on_before_surge",                       	{"table"}) -- {allow = true} switch to false to scip surge
	ixr_signals.add_intercept("on_before_psi_storm",                   	{"table"}) -- {allow = true} switch to false to scip surge

	ixr_signals.add_intercept("opt_menu_on_init",                 		{"CUIScriptWnd"}) 
	ixr_signals.add_intercept("opt_menu_on_accept",             		{"CUIScriptWnd", "opt", "console"}) 
	ixr_signals.add_intercept("opt_menu_on_set_values",					{"CUIScriptWnd", "opt"})  
	
	ixr_signals.add_intercept("CUIActorMenu_OnItemDropped",            	{"first_item_game_object", "second_item_game_object", "from_slot_number", "to_slot_number"}) -- replicated ActorMenu_on_item_drag_drop
	ixr_signals.add_intercept("ActorMenu_on_item_drag_drop",           	{"first_item_game_object", "second_item_game_object", "from_slot_number", "to_slot_number"})	
	ixr_signals.add_intercept("actor_on_nil_drag_drop_item_on_item", 	{"first_item_game_object", "second_item_game_object", "from_slot_number", "to_slot_number"})	
	ixr_signals.add_intercept("actor_on_npc_drag_drop_item_on_item", 	{"first_item_game_object", "second_item_game_object", "from_slot_number", "to_slot_number"})	
	ixr_signals.add_intercept("actor_on_actor_drag_drop_item_on_item",	{"first_item_game_object", "second_item_game_object", "from_slot_number", "to_slot_number"})	
	ixr_signals.add_intercept("on_pda_set_active_subdialog",     		{"ref_pda_script", "section_string", "ui_table"}) -- {ui=nil} is need draw new tab ui set it on variavle ui {ui = ui_pda_encyclopedia_tab.get_ui()}
	
	ixr_signals.add_intercept("ActorMenu_on_item_focus_receive",     	{"item_game_object"}) 
	ixr_signals.add_intercept("CUIActorMenu_OnItemFocusReceive",      	{"item_game_object"}) 
	
	ixr_signals.add_intercept("ActorMenu_on_item_focus_lost",        	{"item_game_object"}) 
	ixr_signals.add_intercept("CUIActorMenu_OnItemFocusLost",         	{"item_game_object"}) 
	
	ixr_signals.add_intercept("CInventory_ItemAvailableToTrade",     	{"npc_game_object", "item_game_object", "flags_table"}) -- { ret_value = true }
	ixr_signals.add_intercept("CInventoryBox_CanTake",     				{"box_game_object", "item_game_object", "flags_table"}) -- { ret_value = true } -- !!! not use !!! bugs in ingine - not all events processed
	ixr_signals.add_intercept("CUIActorMenu_CanMoveToPartner",     		{"npc_gobj", "item_gobj", "itmWeight", "partner_inv_weight", "partner_max_weight", "flags"}) -- { ret_value = true } -- диолог с нпс
	
	ixr_signals.add_intercept("CInventoryBox_OnInvBoxCanTakeItem",     	{"box_game_object", "item_game_object", "flags_table"}) -- { ret_value = true }
	ixr_signals.add_intercept("CInventoryBox_OnInvBoxCanPlaceItem",    	{"box_game_object", "item_game_object", "flags_table"}) -- { ret_value = true }
	
	ixr_signals.add_intercept("main_menu_update", 						{"main_menu_update"})
	
	ixr_signals.add_intercept("on_ixr_autoloader_initialized", 			{"ref_ixr_autoloader"}) -- IXR AUTOLOADER
	ixr_signals.add_intercept("on_init_ixr_options", 					{"ref_ixr_options"}) -- IXR OPTIONS
	
	ixr_signals.add_intercept("on_item_draw_description", 				{"item_game_object", "item_game_object_id", "item_game_object_section", "extend_description_table"}) -- IXR Extend description
end


-- #######################################
-- #	 	 SYSTEM METHODS 	  	 	 #
-- #######################################
function ixr_signals.init()
	if ixr_signals.is_initialized() then
		return true
	end
	
	ixr_signals.toLog("[IXR SIGNALS] PREPARE INIT", true)
	
	if __ixr_override_signals_intercepts then 
		ixr_signals.load_addons_intercepts()
		ixr_signals.toLog("\n[IXR SIGNALS] LOAD OVERRIDED SETTINGS\n", false)
		__ixr_override_signals_intercepts.configure(this)
	else
		ixr_signals.load_default_intercepts()
	end
	
	if ffx_compare_utils.is_empty_flat_or_assoc_table(ixr_signals.intercepts) then
		ffx_dump_utils.AssertWithCaller(3, "IXR Signals", "failed to load intercepts on init")
		return false
	end
	
	ixr_signals.toLog("\n[IXR SIGNALS] SETTINGS LOADED\n", false)
	
	ixr_signals.initialized = true
	
	ixr_signals.toLog("\n[IXR SIGNALS] INITIALIZED\n", false)
	
	return true
end

function ixr_signals.is_initialized()
	return ixr_signals.initialized
end

function ixr_signals.subscribe_to_event(name, func_or_userdata)
	ixr_signals.init()
	
	if (func_or_userdata == nil) then
		ffx_dump_utils.AssertWithCaller(5, "IXR Signals", "Call RegisterCallback on ["..name.."] event without callback function, use format RegisterCallback(event_name, self_callback_function)")
		return false
	end

	if (name == nil) then
		ffx_dump_utils.AssertWithCaller(5, "IXR Signals", "Call RegisterCallback on empty event name, use format RegisterCallback(event_name, self_callback_function)")
		return false
	end
	
	if (ixr_signals.intercepts == nil) then
		ffx_dump_utils.AssertWithCaller(5, "IXR Signals", "failed to load intercepts on call RegisterCallback")
		return false
	end

	if (ixr_signals.intercepts[name]) then
		local caller = tostring(ffx_callable_utils.find_caller_source(4))
		ixr_signals.toLog(ixr_signals.format_subscribe_log("ADD", name, caller), false)
		ixr_signals.intercepts[name][func_or_userdata] = true
	end
end

function ixr_signals.format_subscribe_log(action, name, caller)
    local event_text = "EVENT:[" .. tostring(name) .. "]"
    local script_text = "SCRIPT:[" .. caller .. "]"
    
    return string.format("[IXR SIGNALS] %s SUBSCRIBE: %-50s %s",action, event_text, script_text)
end

function ixr_signals.un_subscribe_from_event(name, func_or_userdata)
	ixr_signals.init()
	
	if (ixr_signals.intercepts[name]) then
		local caller = tostring(ffx_callable_utils.find_caller_source(4))
		ixr_signals.toLog(ixr_signals.format_subscribe_log("REMOVE", name, caller), false)
		ixr_signals.intercepts[name][func_or_userdata] = nil
	end
end

function ixr_signals.send_event(name, ...)
	ixr_signals.init()
	
	if (not ixr_signals.intercepts[name]) then
		return
	end
	
	for func_or_userdata,v in pairs(ixr_signals.intercepts[name]) do 
		if (type(func_or_userdata) == "function") then 
			func_or_userdata(...)
		elseif (func_or_userdata[name]) then
			func_or_userdata[name](func_or_userdata, ...)
		end
	end
end

function ixr_signals.add_intercept(name, args_map)
	-- todo args_map check
	if (ixr_signals.intercepts[name]) then
		return false
	end
	
	if args_map and not ffx_compare_utils.is_empty_flat_or_assoc_table(args_map) then
		ixr_signals.toLog("[IXR SIGNALS] ADD INTERCEPT: ".. tostring(name) .."(".. ffx_json_lib.json_encode(args_map) ..")", false)
	else
		ixr_signals.toLog("[IXR SIGNALS] ADD INTERCEPT: ".. tostring(name) .."()", false)
	end
	
	ixr_signals.intercepts[name] = {}
	
	return true
end

function ixr_signals.remove_intercept(name)
	if (not ixr_signals.intercepts[name]) then
		return false
	end
	
	ixr_signals.intercepts[name] = nil
	ixr_signals.toLog("[IXR SIGNALS] REMOVE INTERCEPT: ".. tostring(name), false)
	
	return true
end

function ixr_signals.toLog(text, overwrite, log_name__auto)
	if ixr_signals.use_file_log then
		ffx_dump_utils.write_to_file_log(text, overwrite, log_name__auto)
	end
	
	if ixr_signals.use_console_log then
		ffx_dump_utils.write_to_console_log(text)
	end
end