
-- IXR FFx0001 Упрощенная система (подписки и отписки) для движковых коллбеков в биндерах
function manage_callbacks(script_name, all_callbacks, _ref, is_set, use_callback_logs, beforeSetAction, beforeUnsetAction)
	if use_callback_logs == nil then
		use_callback_logs = false
	end
	
	local obj_id = _ref.object:id() or nil
	if is_set then
		if beforeSetAction then beforeSetAction(obj_id) end
	else
		if beforeUnsetAction then beforeUnsetAction(obj_id) end
	end
	
	for callback_name, callable_function in pairs(all_callbacks) do 
		if (callback[callback_name]) then 
			if _ref[callable_function] then
				if is_set then 
					_ref.object:set_callback(callback[callback_name], _ref[callable_function], _ref)
					custom_log("set callback:" .. tostring(callback_name), is_set, use_callback_logs, script_name, obj_id)
				else
					_ref.object:set_callback(callback[callback_name], nil)
					custom_log("unset callback:" .. tostring(callback_name), is_set, use_callback_logs, script_name, obj_id)
				end
			else
				custom_log("! WARNING missing callable function [" .. tostring(callable_function) .. "] for callback [" .. tostring(callback_name) .. "]", is_set, use_callback_logs, script_name, obj_id)
			end
		else
			custom_log("! WARNING missing engine callback [" .. tostring(callback_name) .. "]", is_set, use_callback_logs, script_name, obj_id)
		end
	end
end

function custom_log(text, is_set, use_callback_logs, script_name, obj_id)
	if use_callback_logs then
		local prefix = "[-]"
		if is_set then
			prefix = "[+]"
		end
		
		SemiLog(prefix .. " binder:[".. tostring(script_name) .. ".script] object:[" .. tostring(obj_id) .. "] " ..tostring(text))
	end
end