--[[
	IX-Ray override script
	version: 1.0
	author: FFx0001
	script: __ixr_override_signals_intercepts.script
	description: Override configure IXR Signals intercepts
]]


function configure(_ref_ixr_signals)
	--[[ отсуствует по различным причинам
		_ref_ixr_signals.add_intercept("vehicle_on_death_callback",         		{"number"}) -- ph_car.script отсуствует
		_ref_ixr_signals.add_intercept("actor_on_frequency_change",       			{"number", "number"}) -- не имплементирован скрипт item_radio.script
		_ref_ixr_signals.add_intercept("actor_on_achievement_earned",     			{"string", "string"}) -- не имплементирован скрипт game_achievements.script

		_ref_ixr_signals.add_intercept("actor_on_weapon_lower",          			{"game_object"})
		_ref_ixr_signals.add_intercept("actor_on_weapon_raise",          			{"game_object"})
		_ref_ixr_signals.add_intercept("actor_on_item_put_in_box",       			{"game_object", "game_object"})
		_ref_ixr_signals.add_intercept("actor_on_weapon_before_fire",    			{"table"}) 
		_ref_ixr_signals.add_intercept("actor_on_feeling_anomaly",        			{"game_object", "table"}) 
		_ref_ixr_signals.add_intercept("actor_on_jump",                    			{}) 
		_ref_ixr_signals.add_intercept("actor_on_land",                    			{"number"}) 
		_ref_ixr_signals.add_intercept("npc_on_choose_weapon",            			{"game_object", "game_object", "table"}) 
		_ref_ixr_signals.add_intercept("npc_on_before_hit",                 		{"game_object", "SHit", "number", "table"}) -- CAI_Stalker__BeforeHitCallback
		_ref_ixr_signals.add_intercept("anomaly_on_before_activate",         		{"game_object", "game_object"}) 
		_ref_ixr_signals.add_intercept("monster_on_before_hit",             		{"game_object", "SHit", "number", "table"}) 
		_ref_ixr_signals.add_intercept("monster_on_loot_init",              		{"game_object", "table"}) 
		_ref_ixr_signals.add_intercept("burer_on_before_weapon_drop",       		{"game_object", "game_object"}) 
		_ref_ixr_signals.add_intercept("GUI_on_show",                           	{"string", "string"}) -- _G.Register_UI
		_ref_ixr_signals.add_intercept("GUI_on_hide",                   		  	{"string", "string"}) -- _G.Register_UI
		_ref_ixr_signals.add_intercept("on_screen_resolution_changed",          	{})
		_ref_ixr_signals.add_intercept("TrdWndOpened",                          	{})
		_ref_ixr_signals.add_intercept("TrdWndClosed",                          	{})

		_ref_ixr_signals.add_intercept("on_option_change",                     		{})
		_ref_ixr_signals.add_intercept("on_localization_change",                	{})

		_ref_ixr_signals.add_intercept("actor_on_stash_create",           			{"table"})
		_ref_ixr_signals.add_intercept("actor_on_stash_remove",           			{"table"})

		_ref_ixr_signals.add_intercept("ActorMenu_on_before_init_mode",         	{"string", "table", "game_object"})
		_ref_ixr_signals.add_intercept("ActorMenu_on_mode_changed",             	{"number", "number"})
		_ref_ixr_signals.add_intercept("ActorMenu_on_item_before_move",         	{"table", "number", "game_object", "string", "number"})
		_ref_ixr_signals.add_intercept("ActorMenu_on_item_after_move",          	{"number", "game_object", "string", "number"})
		_ref_ixr_signals.add_intercept("ActorMenu_on_trade_started",            	{})
		_ref_ixr_signals.add_intercept("ActorMenu_on_trade_closed",             	{})
	--]]
	
	_ref_ixr_signals.add_intercept("level_input_on_key_press",				{})	
	_ref_ixr_signals.add_intercept("on_key_press",                         	{"dik_key_number"})	
	_ref_ixr_signals.add_intercept("on_key_release",                     	{"dik_key_number"})	
	_ref_ixr_signals.add_intercept("on_key_hold",                          	{"dik_key_number"})	
	
	_ref_ixr_signals.add_intercept("on_mouse_move",                        	{"dx_number", "dy_number"})	
	_ref_ixr_signals.add_intercept("on_mouse_wheel",                      	{"direction_number"})	 
	
	_ref_ixr_signals.add_intercept("on_actor_wnd_mode_switch",          	{"wnd_mode_number"}) -- 0 (Undefined) | 1 (Inventory) | 2 (Trade) | 3 (Upgrade) | 4 (DeadBodySearch) | 10 (Talk dialog  show) | 11 (Talk dialog  hide)

	_ref_ixr_signals.add_intercept("on_actor_wnd_closed",          			{"wnd_mode_number"})
	_ref_ixr_signals.add_intercept("on_actor_wnd_opened",          			{"wnd_mode_number"})	
	
	_ref_ixr_signals.add_intercept("on_actor_inventory_wnd_opened",			{"wnd_mode_number"})
	_ref_ixr_signals.add_intercept("on_actor_inventory_wnd_closed",     	{"wnd_mode_number"})
	
	_ref_ixr_signals.add_intercept("on_actor_trade_wnd_opened",   			{"wnd_mode_number"})
	_ref_ixr_signals.add_intercept("on_actor_trade_wnd_closed",    			{"wnd_mode_number"})
	
	_ref_ixr_signals.add_intercept("on_actor_upgrade_wnd_opened",  			{"wnd_mode_number"})
	_ref_ixr_signals.add_intercept("on_actor_upgrade_wnd_closed",   		{"wnd_mode_number"})
	
	_ref_ixr_signals.add_intercept("on_actor_dead_body_search_wnd_opened",	{"wnd_mode_number"})	
	_ref_ixr_signals.add_intercept("on_actor_dead_body_search_wnd_closed", 	{"wnd_mode_number"})
	
	_ref_ixr_signals.add_intercept("on_actor_dialog_wnd_showed",    		{"wnd_mode_number", "npc_id_number_or_nil"})	
	_ref_ixr_signals.add_intercept("on_actor_dialog_wnd_closed",  			{"wnd_mode_number", "npc_id_number_or_nil"})	
	
	
	_ref_ixr_signals.add_intercept("on_before_level_changing",       		{"net_packet"}) -- engine
	_ref_ixr_signals.add_intercept("on_level_changing",              		{}) -- actor binder
	_ref_ixr_signals.add_intercept("on_item_take",                   		{"item_game_object", "is_actor_exists_bool"}) -- actor
	_ref_ixr_signals.add_intercept("on_item_drop",             				{"item_game_object", "is_actor_exists_bool"}) -- actor
	
	_ref_ixr_signals.add_intercept("actor_on_spawn",                   		{})	
	_ref_ixr_signals.add_intercept("actor_on_init",                   		{"binder_ref"}) 
	_ref_ixr_signals.add_intercept("actor_on_reinit",                 		{"binder_ref"}) 
	
	_ref_ixr_signals.add_intercept("actor_on_hit_fall",                 	{"binder_ref", "g_contact_health_lost", "g_contact_power"})
	_ref_ixr_signals.add_intercept("actor_on_jump_begin",                 	{"binder_ref", "actor_position"})
	_ref_ixr_signals.add_intercept("actor_on_jump_end",                 	{"binder_ref", "g_contact_power", "actor_position"})
	
	_ref_ixr_signals.add_intercept("actor_on_save",                   		{"net_packet"}) 
	_ref_ixr_signals.add_intercept("actor_on_load",                   		{"net_packet"}) 
	_ref_ixr_signals.add_intercept("actor_on_level_changing",              	{}) 
	_ref_ixr_signals.add_intercept("actor_on_before_death",          		{"who_id_number", "flags_table"}) -- { ret_value = true } switch to false for ignore death
	_ref_ixr_signals.add_intercept("actor_on_death",          				{"victim_game_object", "who_game_object"})  
	_ref_ixr_signals.add_intercept("actor_on_net_destroy",           		{"binder_ref"}) 
	_ref_ixr_signals.add_intercept("actor_on_first_update",          		{"binder_ref", "delta_number"}) 
	_ref_ixr_signals.add_intercept("actor_on_update",                 		{"binder_ref", "delta_number"}) 
	_ref_ixr_signals.add_intercept("actor_on_weapon_fired",          		{"npc_game_object", "wpn_game_object", "iAmmoElapsed_bool", "ammo_type_number"}) 
	_ref_ixr_signals.add_intercept("actor_on_weapon_jammed",         		{"wpn_game_object"}) 
	_ref_ixr_signals.add_intercept("actor_on_weapon_no_ammo",        		{"wpn_game_object", "ammo_total_number"}) 
	_ref_ixr_signals.add_intercept("actor_on_weapon_no_avialable_ammo",		{"wpn_game_object", "suitable_ammo_total_number"}) -- eWeaponNoAmmoAvailable
	_ref_ixr_signals.add_intercept("actor_on_weapon_reload",         		{"wpn_game_object", "suitable_ammo_total_number"}) -- eWeaponNoAmmoAvailable копия вызова actor_on_weapon_no_avialable_ammo отсутствие патронов не означает что это перезарядка
	_ref_ixr_signals.add_intercept("actor_on_weapon_zoom_in",        		{"wpn_game_object"}) 
	_ref_ixr_signals.add_intercept("actor_on_weapon_zoom_out",       		{"wpn_game_object"}) 
	_ref_ixr_signals.add_intercept("actor_on_item_take",             		{"item_game_object", "before_transfer_parent_id_number", "is_take_from_ground_bool"}) 
	_ref_ixr_signals.add_intercept("actor_on_item_take_from_box",    		{"box_game_object", "item_game_object"}) 
	_ref_ixr_signals.add_intercept("actor_on_item_take_from_ground", 		{"item_game_object"}) 
	_ref_ixr_signals.add_intercept("actor_on_item_drop",             		{"item_game_object"}) 
	_ref_ixr_signals.add_intercept("on_before_item_use",                    {"npc_game_object", "item_game_object", "table"})  -- { ret_value = true }
	_ref_ixr_signals.add_intercept("actor_on_item_before_use",       		{"npc_game_object", "item_game_object", "table"}) --  { ret_value = true }
	_ref_ixr_signals.add_intercept("actor_on_item_use",              		{"item_game_object", "item_section_string"}) 
	_ref_ixr_signals.add_intercept("actor_item_to_belt",             		{"item_game_object"}) 
	_ref_ixr_signals.add_intercept("actor_item_to_ruck",             		{"item_game_object"}) 
	_ref_ixr_signals.add_intercept("actor_item_to_slot",             		{"item_game_object"}) 
	_ref_ixr_signals.add_intercept("actor_on_trade",                 		{"item_game_object", "sell_bye_bool", "money_number"}) 
	_ref_ixr_signals.add_intercept("actor_on_info_callback",         		{"npc_game_object", "info_id_number"})  
	_ref_ixr_signals.add_intercept("actor_on_before_hit",             		{"sHit_struct", "bone_id_number", "flags_table"}) -- { ret_value = true }  switch to false for ignore hit
	_ref_ixr_signals.add_intercept("actor_on_hit_callback",          		{"binder", "hitted_game_object", "damage_number", "direction_vector", "who_game_object", "bone_id_number", "e_hit_type", "impulse_number", "p_last_hitting_weapon_game_object", "health_lost_number"})
	_ref_ixr_signals.add_intercept("actor_on_torch_enabled",         		{"nil_or_device_torch_game_object"}) 
	_ref_ixr_signals.add_intercept("actor_on_torch_disabled",        		{"nil_or_device_torch_game_object"}) 
	_ref_ixr_signals.add_intercept("actor_on_attach_vehicle",        		{"vechicle_game_object"}) 
	_ref_ixr_signals.add_intercept("actor_on_detach_vehicle",        		{"vechicle_game_object"}) 
	_ref_ixr_signals.add_intercept("actor_on_use_vehicle",           		{"vechicle_game_object"}) 
	_ref_ixr_signals.add_intercept("actor_on_hud_animation_end",     		{"item_game_object", "hud_section_string", "m_current_motion_string", "state_number", "animation_slot_number"}) -- не полностью соответствует варианту из anomaly-coc ("game_object", "string", "bool", "bool", "number")
	_ref_ixr_signals.add_intercept("actor_on_before_sleep",               	{"hours_number"}) 
	_ref_ixr_signals.add_intercept("actor_on_sleep",                  		{"hours_number"}) 
	_ref_ixr_signals.add_intercept("actor_on_interaction",            		{"string", "game_object", "string"}) 
	_ref_ixr_signals.add_intercept("actor_on_leave_dialog",           		{"npc_id_number"}) 
	_ref_ixr_signals.add_intercept("actor_on_foot_step",              		{"alife_game_object", "power_number", "play_bool", "on_ground_bool", "hud_view_bool"}) 
	_ref_ixr_signals.add_intercept("actor_on_footstep",                		{"alife_game_object", "power_number", "play_bool", "on_ground_bool", "hud_view_bool"}) -- replicated actor_on_foot_step

	_ref_ixr_signals.add_intercept("npc_on_use",                       		{"target_game_object", "initiator_game_object"}) 
	_ref_ixr_signals.add_intercept("npc_on_item_take",                 		{"npc_game_object", "item_game_object"}) 
	_ref_ixr_signals.add_intercept("npc_on_item_take_from_box",        		{"npc_game_object", "box_game_object", "item_game_object"}) 
	_ref_ixr_signals.add_intercept("npc_on_item_drop",                  	{"npc_game_object", "item_game_object"}) 
	_ref_ixr_signals.add_intercept("npc_on_net_spawn",                  	{"npc_game_object", "npc_server_object"}) 
	_ref_ixr_signals.add_intercept("npc_on_net_destroy",                	{"npc_game_object"}) 
	_ref_ixr_signals.add_intercept("npc_on_update",                     	{"npc_game_object", "db_storage_table"}) 
	_ref_ixr_signals.add_intercept("npc_on_hit_callback",               	{"npc_game_object", "power_number", "hit_direction_vector", "who_game_object", "bone_index_number"}) 
	_ref_ixr_signals.add_intercept("npc_on_death_callback",             	{"npc_game_object", "who_game_object"}) 
	_ref_ixr_signals.add_intercept("npc_on_fighting_actor",             	{"npc_game_object"}) 
	_ref_ixr_signals.add_intercept("npc_on_weapon_strapped",            	{"npc_game_object", "wpn_game_object"}) 
	_ref_ixr_signals.add_intercept("npc_on_weapon_unstrapped",          	{"npc_game_object", "wpn_game_object"}) -- мутная логика потом перепроверить позицию коллбека в коде
	_ref_ixr_signals.add_intercept("npc_on_weapon_drop",                 	{"npc_game_object", "wpn_game_object"}) 
	_ref_ixr_signals.add_intercept("npc_on_hear_callback",              	{"npc_game_object", "who_npc_id_number", "sound_type_number_or_string", "sound_distance_number", "sound_power_number", "sound_position_vector", "raw_sound_type_number"}) 
	_ref_ixr_signals.add_intercept("npc_on_get_all_from_corpse",        	{"npc_game_object", "corpse_game_object", "item_game_object", "is_in_loot_table_bool"}) 
	_ref_ixr_signals.add_intercept("npc_on_eval_danger",                 	{"npc_game_object", "flags_table"}) -- {ret_value = true} switch to false for npc ignore danger

	_ref_ixr_signals.add_intercept("monster_on_update",                 	{"monster_game_object", "self_st_table"}) 
	_ref_ixr_signals.add_intercept("monster_on_hit_callback",           	{"monster_game_object", "power_number", "hit_direction_vector", "who_game_object", "bone_index_number"}) 
	_ref_ixr_signals.add_intercept("monster_on_net_spawn",             		{"monster_game_object", "monster_server_object"}) 
	_ref_ixr_signals.add_intercept("monster_on_net_destroy",            	{"monster_game_object"}) 
	_ref_ixr_signals.add_intercept("monster_on_death_callback",         	{"monster_game_object", "who_game_object"}) -- without poltergeist
	_ref_ixr_signals.add_intercept("monster_on_death",         				{"monster_game_object", "who_game_object"}) 
	_ref_ixr_signals.add_intercept("monster_on_actor_use_callback",     	{"monster_game_object", "who_game_object"}) 
	_ref_ixr_signals.add_intercept("monster_on_use",     					{"monster_game_object", "who_game_object", "is_alive_bool"}) 

	_ref_ixr_signals.add_intercept("anomaly_field_on_update",     			{"binder_class", "anomaly_zone_game_object"}) 

	_ref_ixr_signals.add_intercept("anomaly_zone_on_init",     				{"binder_class", "anomaly_zone_game_object"}) 
	_ref_ixr_signals.add_intercept("anomaly_zone_on_spawn_artefact_randomly", {"binder_class", "anomaly_zone_game_object", "artefact_server_object"}) 
	_ref_ixr_signals.add_intercept("anomaly_zone_on_update",     			{"binder_class", "anomaly_zone_game_object"}) 
	_ref_ixr_signals.add_intercept("anomaly_zone_on_artefact_take",     	{"binder_class", "anomaly_zone_game_object", "artefact_id", "artefact_object", "parent_zones_by_artefact_id"})
	_ref_ixr_signals.add_intercept("anomaly_zone_on_save",    				{"binder_class", "anomaly_zone_game_object", "thread", "parent_zones_by_artefact_id"}) 
	_ref_ixr_signals.add_intercept("anomaly_zone_on_load",    				{"binder_class", "anomaly_zone_game_object", "thread", "parent_zones_by_artefact_id"}) 
	
	_ref_ixr_signals.add_intercept("physic_object_on_init",     			{"game_object"}) 
	_ref_ixr_signals.add_intercept("physic_object_on_death",     			{"game_object", "game_object"}) 
	_ref_ixr_signals.add_intercept("physic_object_on_use",     				{"physic_game_object", "who_game_object"}) 
	_ref_ixr_signals.add_intercept("physic_object_on_use_callback",     	{"physic_game_object", "who_game_object"}) 
	_ref_ixr_signals.add_intercept("physic_object_on_hit",     				{"physic_game_object", "power_number", "hit_direction_vector", "who_game_object", "bone_index_number"}) 
	_ref_ixr_signals.add_intercept("physic_object_on_hit_callback",     	{"physic_game_object", "power_number", "hit_direction_vector", "who_game_object", "bone_index_number"}) 
	
	_ref_ixr_signals.add_intercept("heli_on_hit_callback",              	{"heli_game_object", "power_number", "nil", "who_game_object", "nil"}) 
	
	_ref_ixr_signals.add_intercept("squad_on_npc_creation",             	{"squad_server_object", "npc_server_object", "spawn_smart_server_object"}) 
	_ref_ixr_signals.add_intercept("squad_on_enter_smart",              	{"squad_server_object", "smart_server_object"}) 
	_ref_ixr_signals.add_intercept("squad_on_leave_smart",              	{"squad_server_object", "old_smart_server_object"}) 
	_ref_ixr_signals.add_intercept("squad_on_npc_death",                	{"squad_server_object", "npc_server_object", "killer_server_object"})
	_ref_ixr_signals.add_intercept("squad_on_update",                    	{"squad_server_object"}) 
	_ref_ixr_signals.add_intercept("squad_on_first_update",              	{"squad_server_object"}) 
	_ref_ixr_signals.add_intercept("squad_on_add_npc",                   	{"squad_server_object", "npc_server_object", "spawn_section_string", "spawn_position_vector", "lv_id_number", "gv_id_number"})
	_ref_ixr_signals.add_intercept("squad_on_register",                  	{"squad_server_object"}) 
	_ref_ixr_signals.add_intercept("squad_on_unregister",                	{"squad_server_object"}) 
	_ref_ixr_signals.add_intercept("squad_on_after_game_vertex_change",  	{"squad_server_object", "last_gvid_number", "m_game_vertex_id_number", "is_level_changed_bool"}) 
	_ref_ixr_signals.add_intercept("squad_on_after_level_change",        	{"squad_server_object", "level_name_string", "cur_lvl_string"}) 

	_ref_ixr_signals.add_intercept("smart_terrain_on_update",            	{"smart_terrain_server_object"}) 
	_ref_ixr_signals.add_intercept("on_try_respawn",                      	{"smart_terrain_server_object", "table"}) -- {disabled = false} switch to true for break

	_ref_ixr_signals.add_intercept("server_entity_on_register",          	{"server_object", "string"}) -- se_actor, se_artefact, se_car, se_heli, se_outfit, se_helmet, se_weapon, se_weapon_shotgun, se_weapon_automatic_shotgun, se_weapon_magazined, se_weapon_magazined_w_gl, se_item, se_item_torch, se_physic, se_lamp, se_ammo, se_grenade, se_eatable, se_invbox, se_explosive, se_pda, se_detector, se_mgun, se_level_changer, se_monster, se_smart_cover, se_stalker, se_trader, se_zone_anom, se_zone_torrid, se_zone_visual, se_restrictor, sim_squad_scripted, se_smart_terrain
	_ref_ixr_signals.add_intercept("server_entity_on_unregister",           {"server_object", "string"}) -- se_actor", se_artefact, se_car, se_heli, se_outfit, se_helmet, se_weapon, se_weapon_shotgun, se_weapon_automatic_shotgun, se_weapon_magazined, se_weapon_magazined_w_gl, se_item, se_item_torch, se_physic, se_lamp, se_ammo, se_grenade, se_eatable, se_invbox, se_explosive, se_pda, se_detector, se_mgun, se_level_changer, se_monster, se_smart_cover, se_stalker, se_trader, se_zone_anom , se_zone_torrid, se_zone_visual, se_restrictor, sim_squad_scripted, se_smart_terrain                   
	_ref_ixr_signals.add_intercept("fill_start_position",                   {}) 
	_ref_ixr_signals.add_intercept("se_stalker_on_spawn",                   {"server_object"}) 
	_ref_ixr_signals.add_intercept("se_actor_on_register",                  {"server_object"}) 
	_ref_ixr_signals.add_intercept("se_actor_on_unregister",                {"server_object"}) 
	_ref_ixr_signals.add_intercept("se_actor_on_STATE_Write",               {"server_object", "net_packet"}) 
	_ref_ixr_signals.add_intercept("se_actor_on_STATE_Read",                {"server_object", "net_packet", "size_number"}) 

	_ref_ixr_signals.add_intercept("map_spot_menu_add_property",           	{"property_CUIWindow", "id_number", "level_name_string", "hint_string"}) -- возможно есть дуликат вызова
	_ref_ixr_signals.add_intercept("map_spot_menu_property_clicked",        {"property_CUIWindow", "map_spot_property_id_number", "map_spot_property_level_name_string", "prop_string"}) -- возможно есть дуликат вызова
	_ref_ixr_signals.add_intercept("main_menu_on_keyboard",                 {"dik_number", "keyboard_action_number", "CUIScriptWnd", "is_level_present_bool"}) 
	_ref_ixr_signals.add_intercept("main_menu_on_init",                     {"CUIScriptWnd"}) -- 1
	_ref_ixr_signals.add_intercept("main_menu_on_init_controlls",    		{"CUIScriptWnd"}) -- 2
	_ref_ixr_signals.add_intercept("main_menu_on_init_callbacks",           {"CUIScriptWnd"}) -- 3
	_ref_ixr_signals.add_intercept("main_menu_on_quit",                     {"CUIScriptWnd"}) -- 4

	_ref_ixr_signals.add_intercept("on_game_load",                          {"binder"}) -- actor net_spawn
	_ref_ixr_signals.add_intercept("on_console_execute",                    {"string", "string", "string", "..."})
	_ref_ixr_signals.add_intercept("on_before_save_input",                  {"number", "number", "table"})
	_ref_ixr_signals.add_intercept("on_before_load_input",                  {"number", "number", "table"})

	_ref_ixr_signals.add_intercept("save_state",                            {"table"}) 
	_ref_ixr_signals.add_intercept("load_state",                            {"table"}) 
	_ref_ixr_signals.add_intercept("on_pstor_save_all",                     {"obj_game_object", "net_packet"}) -- is USE_MARSHAL
	_ref_ixr_signals.add_intercept("on_pstor_load_all",                    	{"obj_game_object", "reader"}) -- is USE_MARSHAL

	_ref_ixr_signals.add_intercept("on_enemy_eval",                         {"game_object", "game_object", "table"})
	_ref_ixr_signals.add_intercept("on_before_surge",                       {"table"}) -- {allow = true} switch to false to scip surge
	_ref_ixr_signals.add_intercept("on_before_psi_storm",                   {"table"}) -- {allow = true} switch to false to scip surge

	_ref_ixr_signals.add_intercept("opt_menu_on_init",                 		{"CUIScriptWnd"}) 
	_ref_ixr_signals.add_intercept("opt_menu_on_accept",             		{"CUIScriptWnd", "opt", "console"}) 
	_ref_ixr_signals.add_intercept("opt_menu_on_set_values",				{"CUIScriptWnd", "opt"})  
	
	_ref_ixr_signals.add_intercept("CUIActorMenu_OnItemDropped",            {"first_item_game_object", "second_item_game_object", "from_slot_number", "to_slot_number"}) -- replicated ActorMenu_on_item_drag_drop
	_ref_ixr_signals.add_intercept("ActorMenu_on_item_drag_drop",           {"first_item_game_object", "second_item_game_object", "from_slot_number", "to_slot_number"})	
	_ref_ixr_signals.add_intercept("actor_on_nil_drag_drop_item_on_item", 	{"first_item_game_object", "second_item_game_object", "from_slot_number", "to_slot_number"})	
	_ref_ixr_signals.add_intercept("actor_on_npc_drag_drop_item_on_item", 	{"first_item_game_object", "second_item_game_object", "from_slot_number", "to_slot_number"})	
	_ref_ixr_signals.add_intercept("actor_on_actor_drag_drop_item_on_item",	{"first_item_game_object", "second_item_game_object", "from_slot_number", "to_slot_number"})	
	_ref_ixr_signals.add_intercept("on_pda_set_active_subdialog",     		{"ref_pda_script", "section_string", "ui_table"}) -- {ui=nil} is need draw new tab ui set it on variavle ui {ui = ui_pda_encyclopedia_tab.get_ui()}
	
	_ref_ixr_signals.add_intercept("ActorMenu_on_item_focus_receive",     	{"item_game_object"}) 
	_ref_ixr_signals.add_intercept("CUIActorMenu_OnItemFocusReceive",      	{"item_game_object"}) 
	
	_ref_ixr_signals.add_intercept("ActorMenu_on_item_focus_lost",        	{"item_game_object"}) 
	_ref_ixr_signals.add_intercept("CUIActorMenu_OnItemFocusLost",         	{"item_game_object"}) 
	
	_ref_ixr_signals.add_intercept("CInventory_ItemAvailableToTrade",     	{"npc_game_object", "item_game_object", "flags_table"}) -- { ret_value = true }
	_ref_ixr_signals.add_intercept("CInventoryBox_CanTake",     			{"box_game_object", "item_game_object", "flags_table"}) -- { ret_value = true } -- !!! not use !!! bugs in ingine - not all events processed
	_ref_ixr_signals.add_intercept("CUIActorMenu_CanMoveToPartner",     	{"npc_gobj", "item_gobj", "itmWeight", "partner_inv_weight", "partner_max_weight", "flags"}) -- { ret_value = true } -- диолог с нпс
	
	_ref_ixr_signals.add_intercept("CInventoryBox_OnInvBoxCanTakeItem",     {"box_game_object", "item_game_object", "flags_table"}) -- { ret_value = true }
	_ref_ixr_signals.add_intercept("CInventoryBox_OnInvBoxCanPlaceItem",    {"box_game_object", "item_game_object", "flags_table"}) -- { ret_value = true }
	
	_ref_ixr_signals.add_intercept("main_menu_update", 						{"main_menu_update"})
	
	_ref_ixr_signals.add_intercept("on_ixr_autoloader_initialized", 		{"ref_ixr_autoloader"}) -- IXR AUTOLOADER
	_ref_ixr_signals.add_intercept("on_init_ixr_options", 					{"ref_ixr_options"}) -- IXR OPTIONS
	
	_ref_ixr_signals.add_intercept("on_item_draw_description", 				{"item_game_object", "item_game_object_id", "item_game_object_section", "extend_description_table"}) -- IXR Extend description
	
	if ffx_death_manager then _ref_ixr_signals.add_intercept("ffx_death_manager_on_corpse_removed",    {"object_id", "population_data"}) end
end