
function on_game_start()
	RegisterScriptCallback("actor_on_item_use", on_actor_item_use)
end

function on_actor_item_use(obj_item, obj_item_section)
	if obj_item_section == "drug_anabiotic" then
		xr_effects.disable_ui_only(db.actor, nil)
		
		level.add_cam_effector("camera_effects\\surge_02.anm", 10, false, script_name() .. ".anabiotic_callback")
		level.add_pp_effector("surge_fade.ppe", 11, false)
		
		give_info("anabiotic_in_process")
		
		_G.mus_vol = get_console():get_float("snd_volume_music")
		_G.amb_vol = get_console():get_float("snd_volume_eff")
		
		get_console():execute("snd_volume_music 0")
		get_console():execute("snd_volume_eff 0")
	end
end

function anabiotic_callback()
	level.add_cam_effector("camera_effects\\surge_01.anm", 10, false, script_name() .. ".anabiotic_callback2")
	
	local rnd = math.random(35,45)
	local m = surge_manager.get_surge_manager()
	
	if(m.started) then
		local tf = level.get_time_factor()
		local diff_sec = math.ceil(game.get_game_time():diffSec(m.inited_time)/tf)
		
		if rnd > (m.surge_time - diff_sec) * tf / 60 then
			m.time_forwarded = true
			m.ui_disabled = true
			m:kill_all_unhided()
			m:end_surge()
		end
	end
	
	SendScriptCallback("anabiotic_callback_before_change_weather")
	
	level.change_game_time(0,0,rnd)
	level_weathers.get_weather_manager():forced_weather_change()
	
	printf("anabiotic_callback: time forwarded on [%d]", rnd)
end

function anabiotic_callback2()
	xr_effects.enable_ui(db.actor, nil)
	
    get_console():execute("snd_volume_music "..tostring(_G.mus_vol))
	get_console():execute("snd_volume_eff "..tostring(_G.amb_vol))
	
	_G.amb_vol = 0
	_G.mus_vol = 0
	
	disable_info("anabiotic_in_process")
end