--'******************************************************
--'*	Биндер объекта костра .
--'******************************************************
campfire_table_by_smart_names = {}
function bind(obj)
	obj:bind_object(campfire_binder(obj))
end

class "campfire_binder" (object_binder)
function campfire_binder:__init(obj) super(obj)
	self.campfire = obj:get_campfire()
end
function campfire_binder:net_spawn(server_object)
	local smart_name = string.gsub(self.object:name(), "_campfire_%d*", "")
	if sim_board.get_sim_board().smarts_by_names[smart_name] then
		self.campfire:turn_off()
		if campfire_table_by_smart_names[smart_name] == nil then
			campfire_table_by_smart_names[smart_name] = {}
		end
		campfire_table_by_smart_names[smart_name][self.object:id()] = self.campfire
	end
	return true
end

function turn_on_campfires_by_smart_name(smart_name)
	local smart_campfires = campfire_table_by_smart_names[smart_name]
	if smart_campfires ~= nil and not empty(smart_campfires) then
		for k,v in pairs (smart_campfires) do
			if not v:is_on() then
				v:turn_on()
			end
		end
	end
end

function turn_off_campfires_by_smart_name(smart_name)
	local smart_campfires = campfire_table_by_smart_names[smart_name]
	if smart_campfires ~= nil and not empty(smart_campfires) then
		for k,v in pairs (smart_campfires) do
			if v:is_on() then
				v:turn_off()
			end
		end
	end
end








