--------------------------------------------------------------------------------
-- Crow binding ----------------------------------------------------------------
-- Made by Peacemaker ----------------------------------------------------------
-- 25.12.07 --------------------------------------------------------------------
--------------------------------------------------------------------------------
crow_storage = {}
crow_counter = 0
-- Standart function for object binding
function bind(obj)
--    local new_binder = crow_binder(obj)
    obj:bind_object(crow_binder(obj))
end
--------------------------------------------------------------------------------
-- Class "crow_binder"
--------------------------------------------------------------------------------
class "crow_binder" (object_binder)
-- Class constructor
function crow_binder:__init(obj) super(obj)
    self.body_timer = 0
end
-- Class update
function crow_binder:update(delta)
-- standart update
 	SendScriptCallback("crow_on_update", self.object, self.st)

    if not(self.object:alive()) and (self.body_timer<=time_global()-120000) and (self.body_timer~=0) then
-- if crow is killed and body lays down for two minutes - release it
        printf("releasing object ["..self.object:name().."]")
        alife():release(alife():object(self.object:id()), true)
    end
end
-- Reinitialize object
function crow_binder:reinit()
    self.body_timer = 0
    db.storage[self.object:id()] = {}
    self.st = db.storage[self.object:id()]
end
-- Net spawn
function crow_binder:net_spawn(sobject)

	local se_obj = alife():object(self.object:id())
	if not (se_obj) then 
		return false 
	end

	SendScriptCallback("crow_on_net_spawn", self.object, se_obj)

    db.add_obj(self.object)
    bind_crow.crow_storage[self.object:id()] = self.object:id()
	bind_crow.crow_counter = bind_crow.crow_counter + 1
    self.object:set_callback(callback.death, self.death_callback, self)
    return true
end
-- Net destroy
function crow_binder:net_destroy()
    self.object:set_callback(callback.death, nil)
   	SendScriptCallback("crow_on_net_destroy", self.object)

    if (bind_crow.crow_storage[self.object:id()] ~= nil) then --*Crow FIX*
        bind_crow.crow_storage[self.object:id()] = nil
        bind_crow.crow_counter = bind_crow.crow_counter - 1
        if (bind_crow.crow_counter < 0) then --*Crow FIX*
            bind_crow.crow_counter = 0 --*Crow FIX*
        end --*Crow FIX*
    end --*Crow FIX*
    db.del_obj(self.object)
end
-- Crow death callback
function crow_binder:death_callback(victim, who)
    self.body_timer = time_global()
    if (bind_crow.crow_storage[self.object:id()] ~= nil) then --*Crow FIX*
        bind_crow.crow_storage[self.object:id()] = nil
        bind_crow.crow_counter = bind_crow.crow_counter - 1
        if (bind_crow.crow_counter < 0) then --*Crow FIX*
            bind_crow.crow_counter = 0 --*Crow FIX*
        end --*Crow FIX*
    end --*Crow FIX*
end
-- Saving crow
function crow_binder:save(package)
	set_save_marker(package, "save", false, "crow_binder")
	xr_logic.save_obj(self.object, package)
	package:w_u32(self.body_timer)
	set_save_marker(package, "save", true, "crow_binder")
end
-- Loading crow
function crow_binder:load(reader)
	set_save_marker(reader, "load", false, "crow_binder")
	xr_logic.load_obj(self.object, reader)
	self.body_timer = reader:r_u32()
	set_save_marker(reader, "load", true, "crow_binder")
end
-- Serializing crow
function crow_binder:Serialize(Object)
    Object:ForChunk("crow_binder", function()
        Object:ForChunk("crow_binder:data", function()
	        xr_logic.Serialize_obj(self.object, Object)
	        self.body_timer = Object:s_u32(self.body_timer)
        end)
    end)
end
