local function empty(container)
	return PROF_EVENT_CLOSURE("empty", function()
        for i,j in pairs(container) do
            return false
        end	
        return true
    end)
end

class "object_collection"
function object_collection:__init()
	self.m_free						= {}
	self.m_given					= {}
	self.m_count					= 0
	self.m_last_id					= 0
end

function object_collection:get_id()	
    return PROF_EVENT_CLOSURE("get_id", function()
        printf("get_id called [%s]", self.m_count)
    
        self.m_count					= self.m_count + 1
    
        if (empty(self.m_free) == true) then
            self.m_last_id				= self.m_last_id + 1
            self.m_given[self.m_last_id] = true
            return self.m_last_id
        end
    
        for i,j in pairs(self.m_free) do
            self.m_free[i]				= nil
            self.m_given[i] 			= true
            return i
        end
    end)
end

function object_collection:remove(id)
    return PROF_EVENT_CLOSURE("remove", function()
        printf("remove called [%s]", tostring(id))
        if self.m_given[id] == true then
            self.m_given[id] = nil
            self.m_free[id] = 1
            self.m_count = self.m_count - 1
        end
    end)
end

function object_collection:size()
	return self.m_count
end

function object_collection:save(packet)
	return PROF_EVENT_CLOSURE("save", function()
        set_save_marker(packet, "save", false, "object_collection")
    
        printf("SAVE OBJECT COLLECTION")
        printf("------- m_count %s  m_last_id %s", self.m_count, self.m_last_id)
        printf("--------  m_free")
        print_table(self.m_free)
        printf("--------  m_given")
        print_table(self.m_given)
        printf("--------")
        
        
        packet:w_u16(self.m_count)	
        packet:w_u32(self.m_last_id)
    
        local n = 0
        for k,v in pairs(self.m_free) do
            n = n + 1		
        end		
        packet:w_u16(n)
        for k,v in pairs(self.m_free) do
            packet:w_u32(k)
        end
    
        n = 0
        for k,v in pairs(self.m_given) do
            n = n + 1		
        end		
        packet:w_u16(n)
        for k,v in pairs(self.m_given) do
            packet:w_u32(k)
        end
        
        set_save_marker(packet, "save", true, "object_collection")
        
    end)
end

function object_collection:load(packet)
	return PROF_EVENT_CLOSURE("load", function()
        set_save_marker(packet, "load", false, "object_collection")
    
        printf("LOAD OBJECT COLLECTION")
        callstack()
    
        self.m_count = packet:r_u16()	
        self.m_last_id = packet:r_u32()
        
        local n = packet:r_u16()
        self.m_free = {}
        for i = 1,n do
            local id = packet:r_u32()
            self.m_free[id] = 1
        end	
    
        n = packet:r_u16()
        self.m_given = {}
        for i = 1,n do
            local id = packet:r_u32()
            self.m_given[id] = true
        end	
        
        printf("------- m_count %s  m_last_id %s", self.m_count, self.m_last_id)
        printf("--------  m_free")
        print_table(self.m_free)
        printf("--------  m_given")
        print_table(self.m_given)
        printf("--------")
        
        set_save_marker(packet, "load", true, "object_collection")
    end)
end
function object_collection:Serialize(Object)
	Object:ForChunk("object_collection", function()
		self.m_count = Object:s_u16(self.m_count)	
		self.m_last_id = Object:s_u32(self.m_last_id)

		if Object:IsSave() then
			local n = 0
			for k,v in pairs(self.m_free) do
				n = n + 1		
			end		
			Object:s_u32(n)
			Object:ForArray(function()
				for k,v in pairs(self.m_free) do
					Object:s_u32(k)
				end
			end)
			
			local n = 0
			for k,v in pairs(self.m_given) do
				n = n + 1		
			end		
			Object:s_u32(n)
			Object:ForArray(function()
				for k,v in pairs(self.m_given) do
					Object:s_u32(k)
				end
			end)
		else
			local n = 0
			n = Object:s_u32(n)
			self.m_free = {}
			Object:ForArray(function()
				for i = 1,n do
					local id = 0
					id = Object:s_u32(id)
					self.m_free[id] = 1
				end	
			end)
			
			local n = 0
			n = Object:s_u32(n)
			self.m_given = {}
			Object:ForArray(function()
				for i = 1,n do
					local id = 0
					id = Object:s_u32(id)
					self.m_given[id] = true
				end	
			end)
		end
	end)
end

