class "se_level_changer" (cse_alife_level_changer)
--------------------
function se_level_changer:__init(section) super (section)
	self.enabled = true
	self.hint = "level_changer_invitation"
end
--------------------
function se_level_changer:on_register()
	cse_alife_level_changer.on_register(self)
	-- Проверяем кастомдату обьекта на наличие стори айди.
	story_objects.check_spawn_ini_for_story_id(self)
	
	SendScriptCallback("server_entity_on_register", self, "se_level_changer")
end
--------------------
function se_level_changer:on_unregister()
	SendScriptCallback("server_entity_on_unregister", self, "se_level_changer")
	unregister_story_object_by_id(self.id)
	cse_alife_level_changer.on_unregister(self)
end
--------------------
function se_level_changer:STATE_Write(packet)
	cse_alife_level_changer.STATE_Write(self, packet)

	set_save_marker(packet, "save", false, "se_level_changer")
	packet:w_bool(self.enabled)
	packet:w_stringZ(self.hint)
	set_save_marker(packet, "save", true, "se_level_changer")
end
--------------------
function se_level_changer:STATE_Read(packet, size)
	cse_alife_level_changer.STATE_Read(self, packet, size)
	-- под LevelEditor не пытаться читать из пакета ничего
	if editor() then
		return
	end

	set_save_marker(packet, "load", false, "se_level_changer")
	self.enabled = packet:r_bool()
	self.hint = packet:r_stringZ()
	set_save_marker(packet, "load", true, "se_level_changer")
end
--------------------
function se_level_changer:STATE_Serialize(Object)
	Object:ForChunk("se_level_changer:STATE", function()
		cse_alife_level_changer.STATE_Serialize(self, Object)
		if not editor() or Object:IsSave() then
			Object:ForChunk("se_level_changer:STATE:data", function()
				self.enabled = Object:s_bool(self.enabled)
				self.hint = Object:s_stringZ(self.hint)
			end)
		end
	end)
end
