class "opt_controls" (CUIWindow)

function opt_controls:__init() super()
end

function opt_controls:__finalize()

end

function opt_controls:InitControls(x, y, xml, handler)

	self:SetWndPos(vector2():set(x,y))
	self:SetWndSize(vector2():set(738,416))
	self:SetAutoDelete(true)
	
	self.focusList = {}

	if xml:NodeExist("frame", 0) then
		self.bk = xml:InitFrame("frame", self)
	end
	self.scroll_v = xml:InitScrollView("main_dialog:scroll_v", self)

    local _st

    _st = xml:InitStatic("video_adv:templ_item", nil)
	local caption = xml:InitStatic		("tab_controls:cap_mousesens",			_st)
	local element = xml:InitTrackBar	("tab_controls:track_mousesens",		_st)
	handler:addControl(self, caption, element, _st)
	
    _st = xml:InitStatic("video_adv:templ_item", nil)
    caption = xml:InitStatic		("tab_controls:cap_mousesens_ui",		_st)
	element = xml:InitTrackBar	("tab_controls:track_mousesens_ui",		_st)
	handler:addControl(self, caption, element, _st)

    _st = xml:InitStatic("video_adv:templ_item", nil)
	caption = xml:InitStatic		("tab_controls:cap_check_mouseinvert",	_st)
	element = xml:InitCheck		("tab_controls:check_mouseinvert",		_st)
	handler:addControl(self, caption, element, _st)
	
	self.kb = xml:InitKeyBinding	("tab_controls:key_binding",			nil)
    handler:addControl(self, nil, nil, self.kb)

	self.default_btn = xml:Init3tButton("tab_controls:btn_default", 			self)
	handler:Register(self.default_btn, "btn_keyb_default")


end