class "opt_sound" (CUIWindow)

function opt_sound:__init() super()
end

function opt_sound:__finalize()

end

function opt_sound:InitControls(x, y, xml, handler)

    self:SetWndPos(vector2():set(x,y))
    self:SetWndSize(vector2():set(738,416))
    self:SetAutoDelete(true)
	if xml:NodeExist("frame", 0) then
		self.bk = xml:InitFrame("frame", self)
	end
 	self.focusList = {}
    self.scroll_v = xml:InitScrollView("main_dialog:scroll_v", self)

	handler:addTrack(self, true, "ui_mm_master_volume", "snd_volume_eff", 0.01, false, "float", true, system_depends.sdNothing, nil, 100)
	--handler:addTrack(self, true, "ui_mm_shoot_volume", "snd_volume_shooting", 0.01, false, "float", true, system_depends.sdNothing, nil, 100)
	handler:addTrack(self, true, "ui_mm_music_volume", "snd_volume_music", 0.01, false, "float", true, system_depends.sdNothing, nil, 100)
	
	handler:addComboBox(self, true, "ui_mm_snd_device", "snd_device", 4, false, system_depends.sdSystemRestart)

	if not is_soc() then
		handler:addCheck(self, true, "ui_mm_dynamic_music", "g_dynamic_music", system_depends.sdNothing)
	end
	
	handler:addCheck(self, true, "ui_mm_eax", "snd_efx", system_depends.sdNothing)
end
