class "opt_video_adv" (CUIWindow)
function opt_video_adv:__init() super()
end

function opt_video_adv:__finalize()
end

function all_modes(render_id)
	return true
end

function mode_1(id)
	return id == "renderer_r1"
end

function mode_2(id)
	return id ~= "renderer_r1"
end

function mode_4(id)
	return id == "renderer_r4"
end

function opt_video_adv:InitControls(x, y, xml, handler)
	self:SetWndPos(vector2():set(x,y))
	self:SetWndSize(vector2():set(738,416))
	self:SetAutoDelete(true)

	if xml:NodeExist("frame_videoadv", 0) then
		xml:InitFrame("frame_videoadv", self)
	end
	self.scroll_v = xml:InitScrollView("video_adv:scroll_v", self)
    handler.scroll_v = self.scroll_v

	btn = xml:Init3tButton("video_adv:btn_to_simply", self)
	handler:Register(btn, "btn_simply_graphic")
	
	local ctl = nil
    local _st = nil
	
    local lineFrame = function (prec, text)
        local static = xml:InitStatic("video_adv:templ_item", nil)
        local temp = xml:InitFrameLine("video_adv:header_setup", static)
        local tempText = xml:InitTextWnd("video_adv:cap_header_setup", temp)
        table.insert(handler.m_preconditions, {func=prec, control=static})
        tempText:SetTextST(text)
    end
	
	local reloadControls = function()
		local pos = handler.scroll_v:GetCurrentScrollPos()
		handler:UpdateDependControls()
		handler.scroll_v:SetScrollPos(pos)
	end
	
	local dependStringToNum = function(input_depend)
		if input_depend == "sdNothing" then
			return 0
		elseif input_depend == "sdVidRestart" then
			return 1
		elseif input_depend == "sdSystemRestart" then
			return 2
		elseif input_depend == "sdSndRestart" then
			return 3
		else
			return 4
		end
	end
	
    local addTrack = function (prec, text, command, step, invert, mode, show_value, depend, reg_name)
        _st = xml:InitStatic("video_adv:templ_item", nil)
        local temp = xml:InitTrackBar("video_adv:track_template_" .. mode, _st)
        local tempText = xml:InitTextWnd("video_adv:cap_template", _st)
        table.insert(handler.m_preconditions, {func=prec, control=_st})
 		temp:SetSystemDepends(dependStringToNum(depend))
		temp:AssignProps(command, "mm_opt_video_adv")
		temp:SetInvert(invert)
		temp:SetDrawingValue(show_value)
		if reg_name then
			handler:Register(temp, reg_name)
		end
		temp:SetStep(step)
        tempText:SetTextST(text)
		return temp
    end

    local addCheck = function (prec, text, command, depend, reg_name)
	_st = xml:InitStatic("video_adv:templ_item", nil)
        local temp = xml:InitCheck("video_adv:check_template", _st)
        local tempText = xml:InitTextWnd("video_adv:cap_template", _st)
		if prec then
			table.insert(handler.m_preconditions, {func=prec, control=_st})
		end
		temp:AssignProps(command, "mm_opt_video_adv")
 		temp:SetSystemDepends(dependStringToNum(depend))
		if reg_name then
			handler:Register(temp, reg_name)
		end
		tempText:SetTextST(text)
		return temp
    end

    local addComboBox = function (prec, text, command, list_length, show_scroll, depend, reg_name)
    _st = xml:InitStatic("video_adv:templ_item", nil)
        local temp = xml:InitComboBox("video_adv:list_template", _st)
        local tempText = xml:InitTextWnd("video_adv:cap_template", _st)
        table.insert(handler.m_preconditions, {func=prec, control=_st})
 		temp:SetListLength(list_length)
		temp:SetVertScroll(show_scroll)
		temp:AssignProps(command, "mm_opt_video_adv")
 		temp:SetSystemDepends(dependStringToNum(depend))
		if reg_name then
			handler:Register(temp, reg_name)
		end
		tempText:SetTextST(text)
		return temp
    end
	
	-----------------------------------------------------------------------------
	-----------------------------------------------------------------------------
	-----------------------------------------------------------------------------
	
	lineFrame(all_modes, "st_common_settings")

	addTrack(all_modes, "ui_mm_detail_density", "r__detail_density", 0.02, true, "float", false, "sdNothing")
	addTrack(all_modes, "ui_mm_grass_distance", "r__detail_radius", 1, false, "int", true, "sdNothing")    
	addTrack(all_modes, "ui_mm_vis_distance", "rs_vis_distance", 0.1, false, "float", false, "sdNothing")
	addTrack(all_modes, "ui_mm_geometry_lod", "r__geometry_lod", 0.1, false, "float", false, "sdNothing")

-----------------------------------------------------------------------------
	-----------------------------------------------------------------------------
	-----------------------------------------------------------------------------
	
	lineFrame(all_modes, "st_surface_options")

	addTrack(all_modes, "ui_mm_texture_quality", "texture_lod", 1, true, "int", false, "sdNothing")
	addTrack(all_modes, "ui_mm_anisotropic", "r__tf_aniso", 1, false, "int", false, "sdNothing")
	
	addCheck(mode_1, "ui_mm_r1_detail_textures", "r1_detail_textures", "sdNothing")
	addCheck(mode_2, "ui_mm_r2_detail_bump", "r2_detail_bump", "sdNothing")
	addCheck(mode_2, "ui_mm_r2_steep_parallax", "r2_steep_parallax", "sdNothing")
	addCheck(mode_4, "ui_mm_r4_enable_tessellation", "r4_enable_tessellation", "sdNothing")
	
	-----------------------------------------------------------------------------
	-----------------------------------------------------------------------------
	-----------------------------------------------------------------------------
	
	lineFrame(all_modes, "st_aa_options")

 	addComboBox(mode_4, "ui_mm_r_scale_mode", "vid_scale_mode", 4, false, "sdVidRestart", "scaleMode")
    handler:AddCallback("scaleMode", ui_events.LIST_ITEM_SELECT, reloadControls, nil)
	
	local scalePresetPrec = function(id)
		if mode_4(id) then
			local current_id = handler:GetComboBox("scaleMode"):CurrentID()
			if current_id > 1 then
				return true
			end
		end
		return false
	end
	
 	addComboBox(scalePresetPrec, "ui_mm_r_scale_preset", "vid_scale_preset", 7, false, "sdVidRestart", "scalePreset")
    handler:AddCallback("scalePreset", ui_events.LIST_ITEM_SELECT, reloadControls, nil)
	
	local vidScalePrec = function(id)
		if mode_4(id) then
			local scale_mode = handler:GetComboBox("scaleMode"):CurrentID()
			if scale_mode > 1 then
				local scale_preset = handler:GetComboBox("scalePreset"):CurrentID()
				local value = handler:GetComboBox("scalePreset"):GetValueOf(scale_preset)
				return value == "st_scale_custom"
			end
			return true
		end
		return false
	end
	
	addTrack(vidScalePrec, "ui_mm_vid_scale", "vid_scale", 0.01, false, "float", true, "sdVidRestart")

	local typeAAPrec = function(id)
		if mode_4(id) then
			local current_id = handler:GetComboBox("scaleMode"):CurrentID()
			if current_id > 1 then
				handler:GetCheck("hashedAlpha"):Enable(true)
				return false
			end
			handler:GetCheck("hashedAlpha"):Enable(false)
			handler:GetCheck("hashedAlpha"):SetCheck(false)
		end
		return true
	end
	
	addTrack(mode_4, "ui_mm_cas_sharpening", "r4_cas_sharpening", 0.01, false, "float", true, "sdNothing")

	addCheck(mode_4, "ui_mm_hashed_alpha_test", "r4_hashed_alpha_test", "sdSystemRestart", "hashedAlpha")
	
	addComboBox(typeAAPrec, "ui_mm_supersample", "r_aa", 4, false, "sdNothing")
	
	-----------------------------------------------------------------------------
	-----------------------------------------------------------------------------
	-----------------------------------------------------------------------------
	
	lineFrame(all_modes, "st_lights_options")

	addTrack(mode_2, "ui_mm_sun_quality", "r2_ls_squality", 0.1, false, "float", false, "sdNothing")
	addTrack(mode_2, "ui_mm_light_distance", "r2_slight_fade", 0.01, false, "float", false, "sdNothing")
	addCheck(all_modes, "ui_mm_npc_torch", "ai_use_torch_dynamic_lights", "sdNothing")
	addCheck(mode_2, "ui_mm_volumetric_light", "r2_volumetric_lights", "sdVidRestart")
	addCheck(mode_4, "ui_mm_r4_hud_shadows", "r4_hud_shadows", "sdVidRestart")
	addCheck(all_modes, "ui_mm_r_actor_shadow", "r_actor_shadow", "sdNothing")
	
	-----------------------------------------------------------------------------
	-----------------------------------------------------------------------------
	-----------------------------------------------------------------------------
	
	lineFrame(mode_2, "st_sunlight_options")

    local sunTable = {}	
	
	handler.enableSun = addCheck(nil, "ui_mm_r2_sun", "r2_sun", "sdSystemRestart", "enableSun")

    local enableSunFunc = function(id)
		if mode_2(id) then
			for _, control in pairs(sunTable) do
				control:Enable(handler.enableSun:GetCheck())
				if control.GetCheck then
					control:SetCheck(control:GetCheck() and handler.enableSun:GetCheck())
				end
			end
			return true
		end
		return false
    end
	
	table.insert(handler.m_preconditions, {func=enableSunFunc, control=_st})
    handler:AddCallback("enableSun", ui_events.BUTTON_CLICKED, reloadControls, nil)

	ctl = addCheck(mode_2, "ui_mm_r2_details_shadows", "r2_sun_details", "sdNothing")
    table.insert(sunTable, ctl)
	
	ctl = addCheck(mode_2, "ui_mm_lights_details", "r2_lights_details", "sdNothing")
    table.insert(sunTable, ctl)
	
	ctl = addCheck(mode_2, "ui_mm_r2_cloud_shadows", "r2_cloud_shadows", "sdVidRestart")
    table.insert(sunTable, ctl)
	
  	ctl = addComboBox(mode_2, "ui_mm_r2_sun_quality", "r2_sun_quality", 6, false, "sdVidRestart")
    table.insert(sunTable, ctl)
	
  	ctl = addComboBox(mode_2, "ui_mm_sun_shafts", "r2_sun_shafts", 5, false, "sdVidRestart")
    table.insert(sunTable, ctl)

  	addComboBox(mode_2, "ui_mm_r__smap_size", "r2_smap_size", 5, false, "sdSystemRestart")
	
	-----------------------------------------------------------------------------
	-----------------------------------------------------------------------------
	-----------------------------------------------------------------------------
	
	lineFrame(mode_2, "st_effects_options")

  	addComboBox(mode_2, "ui_mm_ssao_text", "r2_ssao_mode", 5, false, "sdSystemRestart")

	addCheck(mode_2, "ui_mm_soft_water", "r2_soft_water", "sdVidRestart")
	addCheck(mode_2, "ui_mm_soft_particles", "r2_soft_particles", "sdVidRestart")
	addCheck(mode_4, "ui_mm_r3_dynamic_wet_surfaces", "r3_dynamic_wet_surfaces", "sdNothing")
	addCheck(mode_4, "ui_mm_sslr_water", "r4_sslr_water", "sdSystemRestart")
	addCheck(mode_4, "ui_mm_r3_volumetric_smoke", "r3_volumetric_smoke", "sdNothing")
	addCheck(mode_4, "ui_mm_puddles", "r4_puddles", "sdNothing")
	-----------------------------------------------------------------------------
	-----------------------------------------------------------------------------
	-----------------------------------------------------------------------------
	
	lineFrame(mode_2, "st_postprocess_options")
	
	addCheck(mode_2, "ui_mm_vignette", "r2_vignette", "sdNothing")
	addCheck(mode_2, "ui_mm_aberration", "r2_aberration", "sdNothing")
	addCheck(mode_2, "ui_mm_saturation", "r2_saturation", "sdNothing")
	addCheck(mode_4, "ui_mm_r4_use_gasmask", "r4_use_gasmask", "sdNothing")
	addCheck(mode_2, "ui_mm_r2_use_rain_drops", "r2_use_rain_drops", "sdNothing")

	handler.enableDof = addCheck(mode_2, "ui_mm_dof", "r2_dof_enable", "sdVidRestart", "enableDof")
    handler:AddCallback("enableDof", ui_events.BUTTON_CLICKED, reloadControls, nil)

	handler.reloadDof = addCheck(nil, "ui_mm_dof_reload", "enable_dof_reload", "sdNothing")
    
    local enableReloadDofFunc = function(id)
		if mode_2(id) then
			handler.reloadDof:Enable(handler.enableDof:GetCheck())
			handler.reloadDof:SetCheck(handler.reloadDof:GetCheck() and handler.enableDof:GetCheck())
			return true
		end
		return false
    end
	
    table.insert(handler.m_preconditions, {func=enableReloadDofFunc, control=_st})

   	handler.talkDof = addCheck(nil, "ui_mm_dof_talk", "enable_dof_talk", "sdNothing")
    
    local enableTalkDofFunc = function(id)
		if mode_2(id) then
			handler.talkDof:Enable(handler.enableDof:GetCheck())
			handler.talkDof:SetCheck(handler.talkDof:GetCheck() and handler.enableDof:GetCheck())
			return true
		end
		return false
    end
	
    table.insert(handler.m_preconditions, {func=enableTalkDofFunc, control=_st})
end
