class "opt_video" (CUIWindow)

function opt_video:__init() super()
end

function opt_video:__finalize()

end

function opt_video:InitControls(x, y, xml, handler)

	self:SetWndPos(vector2():set(x,y))
	self:SetWndSize(vector2():set(738,416))
	self:SetAutoDelete(true)
	if xml:NodeExist("frame", 0) then
		self.bk = xml:InitFrame			("frame", self)
	end
	
	self.focusList = {}
	self.scroll_v = xml:InitScrollView("main_dialog:scroll_v", self)

	local _st

    _st = xml:InitStatic("video_adv:templ_item", nil)
	local caption = xml:InitStatic("tab_video:cap_renderer", _st)
	handler.combo_renderer = xml:InitComboBox("tab_video:list_renderer", _st)
	handler:Register(handler.combo_renderer, "combo_renderer")
	handler:addControl(self, caption, handler.combo_renderer, _st)

	_st = xml:InitStatic("video_adv:templ_item", nil)
	caption = xml:InitStatic("tab_video:cap_preset", _st)
	handler.combo_preset = xml:InitComboBox("tab_video:list_presets", _st)
	handler:Register(handler.combo_preset, "combo_preset")
	handler:addControl(self, caption, handler.combo_preset, _st)

    _st = xml:InitStatic("video_adv:templ_item", nil)
	caption = xml:InitStatic("tab_video:cap_resolution",_st)
	local element = xml:InitComboBox("tab_video:list_resolution",_st)
	handler:addControl(self, caption, element, _st)

	_st = xml:InitStatic("video_adv:templ_item", nil)
	caption = xml:InitStatic("tab_video:cap_brightness", _st)
	element = xml:InitTrackBar("tab_video:track_brightness", _st)
	handler:addControl(self, caption, element, _st)

	_st = xml:InitStatic("video_adv:templ_item", nil)
	caption = xml:InitStatic("tab_video:cap_contrast", _st)
	element = xml:InitTrackBar("tab_video:track_contrast", _st)
	handler:addControl(self, caption, element, _st)

	_st = xml:InitStatic("video_adv:templ_item", nil)
	caption = xml:InitStatic("tab_video:cap_gamma", _st)
	element = xml:InitTrackBar("tab_video:track_gamma", _st)
	handler:addControl(self, caption, element, _st)

	_st = xml:InitStatic("video_adv:templ_item", nil)
	caption = xml:InitStatic ("tab_video:cap_fullscreen", _st)
	element = xml:InitCheck ("tab_video:check_fullscreen", _st)
	handler:addControl(self, caption, element, _st)

	_st = xml:InitStatic("video_adv:templ_item", nil)
	caption = xml:InitStatic("tab_video:cap_rs_device_active", _st)
	element = xml:InitCheck("tab_video:check_rs_device_active", _st)
	handler:addControl(self, caption, element, _st)

	_st = xml:InitStatic("video_adv:templ_item", nil)
	caption = xml:InitStatic("tab_video:cap_vsync", _st)
	element = xml:InitCheck("tab_video:check_vsync", _st)
	handler:addControl(self, caption, element, _st)

	_st = xml:InitStatic("video_adv:templ_item", nil)
	caption = xml:InitStatic("tab_video:cap_screenshot_format", _st)
	element = xml:InitComboBox("tab_video:list_screenshot_format", _st)
	handler:addControl(self, caption, element, _st)

	self.btn_advanced = xml:Init3tButton("tab_video:btn_advanced", self)
	handler:Register(self.btn_advanced, "btn_advanced_graphic")
end
