
-- Каждая функция в этом файле используется как условие xr_logic: {=функция !функция}
-- Если в функцию необходимо передавать параметры, то:  {=функция(парам1:парам2:...) !функция(парам1:парам2:...)}
-- Формат: function f(actor, npc). В случае передачи параметров: function f(actor, npc, p).
-- ----------------------------------------------------------------------------------------------------
-- Функции для работы с combat_ignore_cond
-- ----------------------------------------------------------------------------------------------------


function is_enemy_actor(enemy, object)
	--printf_xrscript("caller=%s object=%s", convert_class_name(enemy), convert_class_name(object))
	return enemy:id() == db.actor:id()
end

-- текущий враг на расстоянии больше или равном заданному расстоянию
-- для combat_ignore
function fighting_dist_ge(enemy, npc, p)
	local d = p[1]
	--printf_xrscript("caller=%s npc=%s", convert_class_name(enemy), convert_class_name(npc))
	return enemy:position():distance_to_sqr(npc:position()) >= d * d
end

-- расстояние до текущего реального врага меньше или равно заданного значения
function fighting_dist_le(enemy, npc, p)
	local d = p[1]
	--printf_xrscript("caller=%s npc=%s", convert_class_name(enemy), convert_class_name(npc))
	return enemy:position():distance_to_sqr(npc:position()) <= d * d
end

function enemy_in_zone(enemy, npc, p)
	local zone = db.zone_by_name[p[1]]
	if zone == nil then
		abort("Wrong zone name %s in enemy_in_zone function. NPC [%s]", tostring(p[1]), npc:name())
	end
	--printf_xrscript("caller=%s npc=%s", convert_class_name(enemy), convert_class_name(npc))
	return utils.npc_in_zone(enemy, zone)
end


-- ----------------------------------------------------------------------------------------------------
-- Общие функции
-- ----------------------------------------------------------------------------------------------------
-- видим ли мы еще "черный экран" или нет?
function black_screen(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return device().precache_frame > 1
end
--Проверка, встречается ли в имени чувака одна из строк .
function check_npc_name (actor , npc , p)
	if npc:name() == nil then return false end
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local name_exist = false
	for k,v in pairs(p) do
		if string.find( npc:name(), v ) ~= nil then
			name_exist = true
		end
	end
	return name_exist
end

function check_enemy_name (actor , npc , p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local enemy_id = db.storage[npc:id()].enemy_id
	local enemy = db.storage[enemy_id] and db.storage[enemy_id].object
	local name
	if enemy and enemy:alive() then
		name = enemy:name()
		for i, v in pairs(p) do
			if string.find( name, v ) ~= nil then
				return true
			end
		end
	end
	return false
end

function is_playing_sound (actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return xr_sound.sound_table[npc:id()] ~= nil
end

-- проверка, что актер жив
function actor_alive(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	if db.actor and db.actor:alive() then
		return true
	end
	return false
end

function see_npc(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local npc1 = get_story_object(p[1])
	if npc and npc1 then
		----printf_xrscript("cond <see_npc>: [%s]->[%s]", npc:name(), npc1:name())
		return npc:see(npc1)
	else
		return false
	end
end

function actor_see_npc(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return db.actor:see(npc)
end

function npc_in_actor_frustum(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return npc_in_actor_frustrum(npc)
end

function is_wounded(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return xr_wounded.is_wounded(npc)
end

function dist_to_actor_le(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local d = p[1]
	if d == nil then
		abort("Wrong parameter in 'dist_to_actor_le' function!!!")
	end
	return d and npc:position():distance_to_sqr(actor:position()) <= d * d
end

function dist_to_actor_ge(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local d = p[1]
	if d == nil then
		abort("Wrong parameter in 'dist_to_actor_ge' function!!!")
	end
	return d and npc:position():distance_to_sqr(actor:position()) >= d * d
end

-- Проверка выполняет ли кто указанную работу
function is_obj_on_job(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local smart
	if p and p[2] then
		smart = sim_board.get_sim_board():get_smart_by_name(p[2])
	else
		smart = xr_gulag.get_npc_smart(npc)
	end
	if smart == nil then
		return false
	end
	for k,v in pairs(smart.npc_info) do
		local npc_job = smart.job_data[v.job_id]
		--printf_xrscript("section [%s]", tostring(npc_job.section))
		if npc_job.section == p[1] then
			return true
		end
	end
	return false
end

-- проверка того что дистанция до обьекта <= заданной
-- параметры: [sid,dist]
function distance_to_obj_on_job_le(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local smart = xr_gulag.get_npc_smart(npc)
	for k,v in pairs(smart.npc_info) do
		local npc_job = smart.job_data[v.job_id]
		if npc_job.section == p[1] then
			return npc:position():distance_to_sqr(v.se_obj.position) <= p[2]*p[2]
		end
	end
	return false
end

-- проверка того что npc находится в заданной зоне
-- !!! ВЫЗЫВАТЬ ТОЛЬКО ИЗ SPACE RESTRICTOR !!!
-- параметры: [sid1:sid2:...]
-- !!! НЕКОРРЕКТНО РАБОТАЕТ ДЛЯ ОБЬЕКТОВ В offline'e !!!
-- !!! ДЛЯ ГАРАНТИИ ИСПОЛЬЗОВАТЬ one_obj_in_zone !!!
function obj_in_zone(actor, zone, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(zone))
	local npc1, i, v = 0, 0, 0
	for i, v in pairs(p) do
		npc1 = get_story_object_id(v)
		if npc1 and zone:inside(alife():object(npc1).position) then
			return true
		end
	end
	return false
end

-- параметры: [sid:def*] def=true|false
-- * параметр не обязателен
function one_obj_in_zone(actor, zone, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(zone))
	--local def_offline = (p[2] ~= "false") -- default (true) result if npc in offline
	local obj1 = get_story_object_id(p[1])

	if obj1 then -- npc is online
		return zone:inside(alife():object(obj1).position)
	else -- npc is offline
		return (p[2] ~= "false") -- default (true) result if npc in offline
	end
end

function story_obj_in_zone_by_name (actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local obj = get_story_object_id(p[1])
	local zone = db.zone_by_name[p[2]]
	if obj and zone then -- npc is online
		return zone:inside(alife():object(obj).position)
	end
	return false
end

function actor_in_zone(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local zone = db.zone_by_name[p[1]]
	return utils.npc_in_zone(db.actor, zone)
end

function npc_in_zone(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local zone = db.zone_by_name[p[1]]

	if type(npc.id) ~= "function" then
		npc_obj = db.storage[npc.id] and db.storage[npc.id].object
		if zone == nil then
			return true
		end

		if npc_obj == nil then
			return zone:inside(npc.position)
		end
	else
		npc_obj = npc
	end

	return utils.npc_in_zone(npc_obj, zone)
end

-- true, если здоровье npc <= заданному значению
-- false в противном случае
function health_le(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return p[1] and npc.health < tonumber(p[1])
end

-- true, если здоровье актера  <= заданному значению
-- false в противном случае
function actor_health_le(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return p[1] and actor.health < tonumber(p[1])
end

--[[
-- true, если здоровье вертолёта <= заданному значению
-- false в противном случае
function heli_health_le(actor, obj, p)
	return p[1] and obj:get_helicopter():GetfHealth() < p[1]
end

-- видит ли вертолёт npc (по story id)
function heli_see_npc(actor, obj, p)
	if p[1] then
		local o = get_story_object( p[1] )
		return o ~= nil and obj:get_helicopter():isVisible( o )
	else
		return false
	end
end

function heli_see_actor(actor, obj)
	return actor ~= nil and obj:get_helicopter():isVisible( actor )
end

-- Проверка на принадлежность врага к одной из групп
-- (можно задавать несколько через двоеточие)
function enemy_group(actor, npc, p)
	local enemy_id = db.storage[npc:id()].enemy_id
	local enemy = db.storage[enemy_id] and db.storage[enemy_id].object
	local g = enemy:group()
	local i, v = 0, 0
	for i, v in pairs(p) do
		if v == g then
			----printf_xrscript("_bp: [%s]'s enemy is from group [%d]", npc:name(), v)
			return true
		end
	end
	return false
end

function gulag_state(actor, npc, p)
	if xr_gulag.getGulagState(p[1]) == p[2] then
		return true
	end
	return false
end
]]--

function npc_community(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local npc_obj

	if p[1] == nil then
		abort("Wrong number of params in npc_community")
	end

	if type(npc.id) ~= "function" then
		npc_obj = db.storage[npc.id] and db.storage[npc.id].object

		if npc_obj == nil then return npc:community() == p[1] end
	else
		npc_obj = npc
	end

	if character_community(npc_obj) == p[1] then
		return true
	end
	return false
end

--[[
function npc_rank(actor, npc, p)
	if p[1] == nil then
		abort("Wrong number of params in npc_rank")
	end

	if ranks.get_obj_rank_name(npc) == p[1] then
		return true
	end
	return false
end

function npc_profile(actor, npc, p)
	if p[1] == nil then
		abort("Wrong number of params in npc_profile")
	end
	if npc:profile_name() == p[1] then
		return true
	end
	return false
end
]]--

-- Проверка того что удар был нанесен кем-то из npc указанных в списке.
-- Параметры это story_id персонажей. Можно задавать несколько story_id.
function hitted_by(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local npc1
	local t = db.storage[npc:id()].hit
	if t then
		for i, v in pairs(p) do
			npc1 = get_story_object(v)
			if npc1 and t.who == npc1:id() then
				return true
			end
		end
	end
	return false
end
-- Функция проверки попадания в кость по её индексу.(Проверка только для секции hit)
function hitted_on_bone(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	for k,v in pairs (p) do
		if db.storage[npc:id()].hit.bone_index == npc:get_bone_id(v) then
			return true
		end
	end
	return false
end

-- Проверка, что лучшее оружие персонажа - пистолет
function best_pistol(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local pistol = npc:item_in_slot(1)
	if pistol ~= nil then
		return true
	else
		return false
	end
end

-- Проверка, что персонажу нанесли смертельный хит. Проверять ТОЛЬКО на on_hit
function deadly_hit(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	if db.storage[npc:id()] == nil or db.storage[npc:id()].hit == nil then
		----printf_xrscript("deadly hit false")
		return false
	end

	----printf_xrscript("deadly hit [%s]", tostring(db.storage[npc:id()].hit.deadly_hit == true))
	return db.storage[npc:id()].hit.deadly_hit == true
end



-- Проверка того что персонаж был убит кем-то из npc указанных в списке.
-- Параметры это story_id персонажей. Можно задавать несколько story_id.
function killed_by(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local npc1
	local t = db.storage[npc:id()].death
	if t then
		for i, v in pairs(p) do
			npc1 = get_story_object(v)
			if npc1 and t.killer == npc1:id() then
				--printf_xrscript("_bp: killed_by(%d)", v)
				return true
			end
		end
	end
	return false
end

-- проверка (по story_id) все ли проверяемые сталкеры живы
-- TODO: исправить ситуацию, когда выдается неправильный результат для обьектов, которые
--       не успели проспавниться.
function is_alive_all(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local npc1
	for i, v in pairs(p) do
		npc1 = get_story_object_id(v)
		if npc1 == nil then
			return false
		end
		npc1 = alife():object(npc1)
		if npc1 and (not IsStalker(npc1) or not npc1:alive()) then
			return false
		end
	end
	return true
end

-- проверка (по story_id) того, что чотя бы один из проверяемых сталкеров жив
-- TODO: исправить ситуацию, когда выдается неправильный результат для обьектов, которые
--       не успели проспавниться.
function is_alive_one(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local npc1
	for i, v in pairs(p) do
		npc1 = get_story_object_id(v)
		if npc1 == nil then
			return false
		end
		npc1 = alife():object(npc1)
		if npc1 and IsStalker(npc1) and npc1:alive() then
			return true
		end
	end
	return false
end

-- проверка (по story_id) того, что проверяемыq npc жив
-- TODO: исправить ситуацию, когда выдается неправильный результат для обьектов, которые
--       не успели проспавниться.
function is_alive(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local npc1

	if npc == nil or (p and p[1]) then
		npc1 = get_story_object_id(p[1])
	elseif (type(npc.id) == "number") then
		npc1 = npc.id
	else
		npc1 = npc:id()
	end

	if npc1 == nil then
		return false
	end

	npc1 = alife():object(npc1)

	if npc1 and IsStalker(npc1) and npc1:alive() then
		return true
	end

	return false
end

-- проверка (по story_id) все ли проверяемые сталкеры мертвы
-- TODO: исправить ситуацию, когда выдается неправильный результат для обьектов, которые
--       не успели проспавниться.
function is_dead_all(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local npc1
	for i, v in pairs(p) do
		npc1 = get_story_object(v)
		if npc1 then
			if npc1:alive() then
				return false
			else
				--printf_xrscript("_bp: is_dead_all(%d) = true", v)
				return true
			end
		end
		return false
	end
	return true
end

-- проверка (по story_id) того, что хотя бы один из проверяемых сталкеров мертв
-- TODO: исправить ситуацию, когда выдается неправильный результат для обьектов, которые
--       не успели проспавниться.
function is_dead_one(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local npc1
	for i, v in pairs(p) do
		npc1 = get_story_object(v)
		if not npc1 or not npc1:alive() then
			--printf_xrscript("_bp: is_dead_one(%d) = true", v)
			return true
		end
	end
	return false
end

-- проверка (по story_id) того, что хотя бы один из проверяемых сталкеров мертв
-- TODO: исправить ситуацию, когда выдается неправильный результат для обьектов, которые
--       не успели проспавниться.
function is_dead(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local npc1
	npc1 = get_story_object(p[1])
	return not npc1 or not npc1:alive()
end

-- Проверяет , существует ли обьект с заданным стори айди.
function story_object_exist(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local npc1 = get_story_object(p[1])
	return npc1 ~= nil
end

--[[
-- проверка (по story_id) того, что нашим врагом есть хотя бы кото-то один из списка
function check_fighting(actor, npc, p)
	local enemy_id = db.storage[npc:id()].enemy_id
	local enemy = db.storage[enemy_id] and db.storage[enemy_id].object
	local sid
	if enemy and enemy:alive() then
			sid = enemy:story_id()
			for i, v in pairs(p) do
					----printf_xrscript("_bp: %s.check_fighting(%d)", npc:name(), v)
				if type(v) == 'number' and sid == v then
					----printf_xrscript("TRUE")
					return true
				end
			end
	end
	----printf_xrscript("_bp: check_fighting() = false")
	return false
end
]]--


-- true, если у актёра в инвентаре есть указанный предмет
-- false, если нету, либо не задана секция предмета
function actor_has_item(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local story_actor  = get_story_object("actor")
	return p[1] ~= nil and story_actor and story_actor:object( p[1] ) ~= nil
end

function npc_has_item(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return p[1] ~= nil and npc:object( p[1] ) ~= nil
end
-- проверяет наличие заданого количества предметов в инвентаре игрока.
function actor_has_item_count(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local item_section 	= p[1]
	local need_count 	= tonumber(p[2])
	local has_count 	= 0
	local function calc(temp, item)
		----printf_xrscript("item [%s]",tostring(item:section()))
		if item:section() == item_section then
			has_count = has_count + 1
		end
	end
	actor:iterate_inventory(calc, actor)
	return has_count >= need_count
end

-- возвращает true, если в текущей схеме персонажа взведён указанный сигнал.
function signal(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	if p[1] then
		local st   = db.storage[npc:id()]
		local sigs = st[st.active_scheme].signals
--		--printf_xrscript( "xr_conditions.signal: npc=%s, scheme=%s", npc:name(), tostring(st.active_scheme) )
		return sigs ~= nil and sigs[p[1]] == true
	else
		return false
	end
end

-- возвращает true, если значение указанного счётчика актёра больше указанного числа
function counter_greater(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	if p[1] and p[2] then
		local c = xr_logic.pstor_retrieve(actor, p[1], 0)
--		if  c > p[2] then --printf_xrscript("pl: counter [%s]  greater [%s]", p[1], p[2]) end
		return tonumber(c) > tonumber(p[2])
	else
		return false
	end
end
function counter_equal(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	if p[1] and p[2] then
		local c = xr_logic.pstor_retrieve(actor, p[1], 0)
		return c == tonumber(p[2])
	else
		return false
	end
end

--[[
-- определяет нечётность интервала игрового времени. интервал нужно передать в p[1]
function odd_time_interval(actor, npc, p)
	return odd( game.time() / p[1] )
end
]]--
-------------------------------------------------------------------------------------------------------
-- Функции поддержки kamp
function _kamp_talk(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	if xr_kamp.kamp_stalkers[npc:id()] then
		return xr_kamp.kamp_stalkers[npc:id()]
	end
	return false
end

function _used(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return npc:is_talking()
end
-------------------------------------------------------------------------------------------------------

-------------------------------------------------------------------------------------------------------
local alarm_statuses = {
	normal = smart_terrain_control.NORMAL,
	danger = smart_terrain_control.DANGER,
	alarm = smart_terrain_control.ALARM
}

-- Функции поддержки безопасности баз
function check_smart_alarm_status(actor, npc, p)

	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local smart_name = p[1]
	local status = alarm_statuses[p[2]]

	if status == nil then
		abort("Wrong status[%s] in 'check_smart_alarm_status'", tostring(p[2]))
	end

	local smart = sim_board.get_sim_board():get_smart_by_name(smart_name)

	local smart_control = smart.base_on_actor_control

	if smart_control == nil then
		abort("Cannot calculate 'check_smart_alarm_status' for smart %s", tostring(smart_name))
	end

	return smart_control:get_status() == status
end

-------------------------------------------------------------------------------------------------------
function has_enemy(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return npc:best_enemy() ~= nil
end

function has_actor_enemy(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local best_enemy = npc:best_enemy()
	return best_enemy ~= nil and best_enemy:id() == db.actor:id()
end

function see_enemy(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local enemy = npc:best_enemy()

	if enemy ~= nil then
			return npc:see(enemy)
	end
	return false
end

function has_enemy_in_current_loopholes_fov(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return npc:in_smart_cover() and npc:best_enemy() ~= nil and npc:in_current_loophole_fov( npc:best_enemy():position())
end

function talking(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return actor:is_talking()
end

function npc_talking(actor, npc)

	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return npc:is_talking()
end

function see_actor(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return npc:alive() and npc:see(actor)
end

function actor_enemy(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local t = db.storage[npc:id()].death
	return npc:relation(actor) == game_object.enemy or (t ~= nil and t.killer == actor:id())
end

function actor_friend(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return npc:relation(actor) == game_object.friend
end

function actor_neutral(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return npc:relation(actor) == game_object.neutral
end

function is_factions_enemies(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	if(p[1]~=nil) then
		return game_relations.is_factions_enemies(character_community(actor), p[1])
	else
		return false
	end
end

function is_factions_neutrals(actor, npc, p)

	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return not(is_factions_enemies(actor, npc, p) or is_factions_friends(actor, npc, p))
end

function is_factions_friends(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	if(p[1]~=nil) then
		return game_relations.is_factions_friends(character_community(actor), p[1])
	else
		return false
	end
end

function is_faction_enemy_to_actor(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	if(p[1]~=nil) then
--        return db.actor:community_goodwill(p[1])<-1000
		return relation_registry.community_goodwill(p[1], db.actor:id())<=-1000
	else
		return false
	end
end

function is_faction_friend_to_actor(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	if(p[1]~=nil) then
--		return db.actor:community_goodwill(p[1])>1000
		return relation_registry.community_goodwill(p[1], db.actor:id())>=1000
	else
		return false
	end
end

function is_faction_neutral_to_actor(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return not(is_faction_enemy_to_actor(actor, npc, p) or is_faction_friend_to_actor(actor, npc, p))
end

function is_squad_friend_to_actor(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	if(p[1]~=nil) then
--	   --printf_xrscript("squad check goodwill1 [%s]", p[1])
		return game_relations.check_all_squad_members(p[1], "friend")
	else
--	   --printf_xrscript("squad check goodwill5 [%s]", p[1])
		return false
	end
end

function is_squad_enemy_to_actor(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	if not p then
		abort("Not enough arguments in 'is_squad_enemy_to_actor' funciton!")
	end

	for k,v in pairs(p) do
--   	--printf_xrscript("squad check goodwill1 [%s]", v)
		if game_relations.check_all_squad_members(v, "enemy") then
			return true
		end
	end

	return false
end

function is_squad_neutral_to_actor(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return not(is_squad_enemy_to_actor(actor, npc, p) or is_squad_friend_to_actor(actor, npc, p))
end

-- текущий враг актёр?
function fighting_actor(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local enemy_id = db.storage[npc:id()].enemy_id
	local enemy = db.storage[enemy_id] and db.storage[enemy_id].object
	return enemy and enemy:id() == actor:id()
end


function hit_by_actor(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local t = db.storage[npc:id()].hit
	local hit_by_actor = (t ~= nil and t.who == actor:id())
	--printf_xrscript("_bp: hit_by_actor: %s", if_then_else(hit_by_actor, "true", "false"))
	return hit_by_actor
end

function killed_by_actor(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local t = db.storage[npc:id()].death
	local killed_by_actor = t ~= nil and t.killer == actor:id()
	--printf_xrscript("_bp: killed_by_actor: %s", if_then_else(killed_by_actor, "true", "false"))
	return killed_by_actor
end

function actor_has_weapon (actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local obj = actor:active_item ()
	if obj == nil or isWeapon (obj) == false then return false end
	return true
end

function actor_active_detector(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local detector_section = p and p[1]
	if detector_section == nil then abort("Wrong parameters in function 'actor_active_detector'") end
	local actor_detector = db.actor:active_detector()
	return (actor_detector ~= nil) and actor_detector:section() == detector_section
end

function heavy_wounded(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return xr_wounded.is_heavy_wounded_by_id( npc:id() )
end

--[[
Проверка на заданный период времени
Время задается в минутах
Параметры: (time_shift:period_min)
					 time_shift - периодичность срабатывания
					 period - период срабатывания на котором мы получаем true

Примеры:
time_period(60:10) - возвращает true каждый час на протяжении первых 10 минут
--]]
function time_period(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local tshift, period = p[1], p[2]
	if tshift ~= nil and period ~= nil and db.actor ~= nil then
		return tshift > period and level.get_time_minutes() % tshift <= period
	end
	return false
end

function is_rain (actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return db.actor ~= nil and level.rain_factor() > 0
end

function is_heavy_rain (actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return db.actor ~= nil and level.rain_factor() >= 0.5
end

function is_day (actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return db.actor ~= nil and level.get_time_hours() >= 6 and level.get_time_hours() < 21
end

function is_dark_night (actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return db.actor ~= nil and (level.get_time_hours() < 3 or level.get_time_hours() > 22)
end

function is_jup_a12_mercs_time (actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return db.actor ~= nil and (level.get_time_hours() >= 1 and level.get_time_hours() < 5)
end

function zat_b7_is_night (actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return db.actor ~= nil and (level.get_time_hours() >= 23 or level.get_time_hours() < 5)
end

function zat_b7_is_late_attack_time (actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return db.actor ~= nil and (level.get_time_hours() >= 23 or level.get_time_hours() < 9)
end

function mob_has_enemy(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	-- return false
	if npc == nil then return false end
	--if npc:get_enemy () then --printf_xrscript ("ENEMY PRESENT") else --printf_xrscript ("ENEMY NOT PRESENT") end
	return npc:get_enemy() ~= nil
end

function mob_was_hit(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local h = npc:get_monster_hit_info()
	if h.who and h.time ~= 0 then
		return true
	end
	return false
end

function actor_on_level(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	for k,v in pairs (p) do
		----printf_xrscript("level name: [%s], needed level name: [%s]", level.name(), v`)
		if v == level.name() then
			return true
		end
	end
	return false
end

function treasure_exist(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	----printf_xrscript("%s %s", actor:name(), npc:name())
	return true
end

--[[
--'-----------------------------------------------------------------------------------
--' Cover support
--'-----------------------------------------------------------------------------------
--' Если возвращает true, то солдаты за каверами начинают стрелять.
function cover_attack(actor, npc)
	--' Берем сквад объекта
	local squad = get_object_squad(npc)

	if squad == nil then
		return false
	end

	return squad:cover_attack()
end
]]--

--'-----------------------------------------------------------------------------------
--' Squad support
--'-----------------------------------------------------------------------------------
function squad_in_zone(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local story_id = p[1]
	local zone_name = p[2]
	if story_id == nil then
		abort("Insufficient params in squad_in_zone function. story_id[%s], zone_name[%s]", tostring(story_id), tostring(zone_name))
	end
	if zone_name == nil then
		zone_name = npc:name()
	end

	local sim_board = sim_board.get_sim_board()

	local squad = get_story_squad(story_id)
	if squad == nil then
		--abort("There is no squad with id[%s]", tostring(squad_id))
		return false
	end

	local zone = db.zone_by_name[zone_name]
	if zone == nil then
		--abort("There is no squad with id[%s]", tostring(zone_name))
		return false
	end

	for k in squad:squad_members() do
		local position = (db.storage[k.id] and db.storage[k.id].object and db.storage[k.id].object:position()) or k.object.position
		if zone:inside(position) then
			return true
		end
	end
	return false
end

function squad_has_enemy(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local story_id = p[1]

	if story_id == nil then
		abort("Insufficient params in squad_has_enemy function. story_id [%s]", tostring(story_id))
	end

	local squad = get_story_squad(story_id)
	if squad == nil then
		--abort("There is no squad with id[%s]", tostring(story_id))
		return false
	end

	local al = alife()
	for k in squad:squad_members() do
		local npc_obj = level.object_by_id(k.object.id)
		if npc_obj == nil then
			return false
		end
		if npc_obj:best_enemy() ~= nil then
			return true
		end
	end

	return false
end

-- Functions for Yantar
function squad_in_zone_all(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local story_id = p[1]
	local zone_name = p[2]
	if story_id == nil or zone_name == nil then
		abort("Insufficient params in squad_in_zone_all function. story_id[%s], zone_name[%s]", tostring(story_id), tostring(zone_name))
	end
	local squad = get_story_squad(story_id)
	if squad == nil then
		--abort("There is no squad with id[%s]", tostring(story_id))
		return false
	end
	local zone = db.zone_by_name[zone_name]
	if zone == nil then
		--abort("There is no squad with id[%s]", tostring(zone_name))
		return false
	end
	local al = alife()
	for k in squad:squad_members() do
		local position = (db.storage[k.id] and db.storage[k.id].object and db.storage[k.id].object:position()) or k.object.position
		if not zone:inside(position) then
			return false
		end
	end
	return true
end

function squads_in_zone_b41(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local smart = sim_board.get_sim_board():get_smart_by_name("jup_b41")
	local zone = db.zone_by_name["jup_b41_sr_light"]
	local al = alife()

	if zone == nil then
		return false
	end
	if smart == nil then
		return false
	end

	for k,v in pairs(sim_board.get_sim_board().smarts[smart.id].squads) do
		if v ~= nil then
			for j in v:squad_members() do
				if not zone:inside(j.object.position) then
					return false
				end
			end
		end
	end

	return true
end


--' Проверка в таргет кондлисте задания, соответствует ли имя сквада переданному
function target_squad_name(actor, obj, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(obj))
	if p[1] == nil then
		abort("Wrong parameters")
	end
	if not(obj) then
		return false
	end
	--callstack()
	if IsStalker(obj) or IsMonster(obj) then
		if alife():object(obj.group_id) == nil then
			return false
		end
		if string.find( alife():object(obj.group_id):section_name(), p[1] ) ~= nil then
			return true
		end
		--return alife():object(obj.group_id):section_name() == p[1]
	end
	return obj:section_name() == p[1]
end

--' Проверка в таргет кондлисте задания, соответствует ли имя смарта переданному
function target_smart_name(actor, smart, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(smart))
	if p[1] == nil then
		abort("Wrong parameters")
	end
	--callstack()
	return smart:name() == p[1]
end

--' Проверяет жив ли отряд с указанным ID
function squad_exist(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local story_id = p[1]
	if story_id == nil then
		abort("Wrong parameter story_id[%s] in squad_exist function", tostring(story_id))
	end
	local squad = get_story_squad(story_id)

--	if squad == nil then
--		return false
--	end
	return squad ~= nil
	--	return squad.squad_power > 0
end

function is_squad_commander(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	if (type(npc.id) == "number") then
		npc_id = npc.id
	else
		npc_id = npc:id()
	end
	local squad = get_object_squad(npc)
	return squad ~= nil and squad:commander_id() == npc_id
end

function squad_npc_count_ge(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local story_id = p[1]
	if story_id == nil then
		abort("Wrong parameter squad_id[%s] in 'squad_npc_count_ge' function", tostring(squad_id))
	end
	local squad = get_story_squad(story_id)

	if squad then
		return squad:npc_count() > tonumber(p[2])
	else
		return false
	end
end

function surge_complete()
	return surge_manager.is_finished()
end

function surge_started()
	return surge_manager.is_started()
end

function surge_kill_all()
	return surge_manager.is_killing_all()
end

function signal_rocket_flying(actor, npc, p)

	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	if p==nil then
		abort("Signal rocket name is not set!")
	end
	if db.signal_light[p[1]] then
		return db.signal_light[p[1]]:is_flying()
	else
		abort("No such signal rocket: [%s] on level", tostring(p[1]))
	end
	return false
end

function quest_npc_enemy_actor(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	if p[1] == nil then
		abort("wrong story id")
	else
		local obj = get_story_object(p[1])
		if obj and IsStalker(obj) then
			if db.actor and obj:general_goodwill(db.actor)<=-1000 then
				return true
			end
		end
	end
	return false
end

function animpoint_reached(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local animpoint_storage = db.storage[npc:id()].animpoint

	if animpoint_storage == nil then
		return false
	end

	local animpoint_class = animpoint_storage.animpoint

	return animpoint_class:position_riched()
end

--[[
function npc_stay_offline(actor, npc, p)
	if p == nil then
		abort("Wrong parameter!!!")
	end
	if npc and db.actor then
		if is_smart_in_combat(actor, npc, p) then
			if npc.position:distance_to(db.actor:position())>=30 or game_relations.get_gulag_relation_actor(p[1], "enemy") then
				return true
			end
		end
	end
	return false
end
]]--

-- проверка того что дистанция до обьекта >= заданной
-- параметры: [sid,dist]
function distance_to_obj_ge(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local npc_id = get_story_object_id(p[1])
	local npc1 = npc_id and alife():object(npc_id)
	if npc1 then
		return db.actor:position():distance_to_sqr(npc1.position) >= p[2]*p[2]
	end
	return false
end

function distance_to_obj_le(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local npc_id = get_story_object_id(p[1])
	local npc1 = npc_id and alife():object(npc_id)
	if npc1 then
		return db.actor:position():distance_to_sqr(npc1.position) < p[2]*p[2]
	end
	return false
end

function in_dest_smart_cover(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return npc:in_smart_cover()
end

function active_item(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	if p and p[1] then
		for k,v  in pairs(p) do
			if actor:item_in_slot(3) ~= nil and actor:item_in_slot(3):section() == v then return true end
		end
	end
	return false
end

function actor_nomove_nowpn()
	if (not isWeapon(db.actor:active_item())) or db.actor:is_talking() then
		return true
	end
	return false
end

function jup_b16_is_zone_active(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return has_alife_info(npc:name())
end

--Функция проверки состояния видимости кровососа.
-- Возможный набор параметров --> story_id:visibility_state(можно вызывать откуда угодно) или visibility_state(если вызывается из кастомдаты кровососа)
--  visibility_state -->
--						0 - невидимый
--						1 - полувидимый
--						2 - полностью видимый

function check_bloodsucker_state(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	if (p and p[1]) == nil then abort("Wrong parameters in function 'check_bloodsucker_state'!!!") end
	local state = p[1]
	if p[2] ~= nil then
		state = p[2]
		npc = get_story_object(p[1])
	end
	if npc ~= nil then
		return npc:get_visibility_state () == tonumber(state)
	end
	return false
end

function dist_to_story_obj_ge(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local story_id = p and p[1]
	local story_obj_id = get_story_object_id(story_id)
	if story_obj_id == nil then return true end
	local se_obj = alife():object(story_obj_id)
	return se_obj.position:distance_to(db.actor:position()) > tonumber(p[2])
end

function actor_has_nimble_weapon(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local need_item = {}
	need_item["wpn_groza_nimble"] = true
	need_item["wpn_desert_eagle_nimble"] = true
	need_item["wpn_fn2000_nimble"] = true
	need_item["wpn_g36_nimble"] = true
	need_item["wpn_protecta_nimble"] = true
	need_item["wpn_mp5_nimble"] = true
	need_item["wpn_sig220_nimble"] = true
	need_item["wpn_spas12_nimble"] = true
	need_item["wpn_usp_nimble"] = true
	need_item["wpn_vintorez_nimble"] = true
	need_item["wpn_svu_nimble"] = true
	need_item["wpn_svd_nimble"] = true
	for k,v in pairs(need_item) do
		if actor:object(k) ~= nil then
			return true
		end
	end
	return false
end

function actor_has_active_nimble_weapon(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local need_item = {}
	need_item["wpn_groza_nimble"] = true
	need_item["wpn_desert_eagle_nimble"] = true
	need_item["wpn_fn2000_nimble"] = true
	need_item["wpn_g36_nimble"] = true
	need_item["wpn_protecta_nimble"] = true
	need_item["wpn_mp5_nimble"] = true
	need_item["wpn_sig220_nimble"] = true
	need_item["wpn_spas12_nimble"] = true
	need_item["wpn_usp_nimble"] = true
	need_item["wpn_vintorez_nimble"] = true
	need_item["wpn_svu_nimble"] = true
	need_item["wpn_svd_nimble"] = true

	if actor:item_in_slot(2) ~= nil and need_item[actor:item_in_slot(2):section()] == true then
		return true
	end
	if actor:item_in_slot(3) ~= nil and need_item[actor:item_in_slot(3):section()] == true then
		return true
	end
	return false
end

function jup_b202_inventory_box_empty(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local inv_box = get_story_object("jup_b202_actor_treasure")
	return inv_box:is_inv_box_empty()
end
--[[
function jup_b46_actor_has_active_science_detector(actor, npc)
	if actor:item_in_slot(9) ~= nil and actor:item_in_slot(9):section() == "detector_scientific" then return true end
	return false
end
]]--
function is_in_danger(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	if p and p[1] then
		npc = get_story_object(p[1])
	end
	----printf_xrscript("npc: [%s] is in danger [%s]", tostring(npc:id()), tostring(db.storage[npc:id()].danger_flag))
	return db.storage[npc:id()].danger_flag
end

function object_exist(actor , npc , p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return get_story_object(p[1]) ~= nil
end

function squad_curr_action(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local squad = get_object_squad(npc)
	return squad.current_action and squad.current_action.name == p[1]
end

function is_monster_snork(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return npc:clsid() == clsid.snork_s
end

function is_monster_dog(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return npc:clsid() == clsid.dog_s
end

function is_monster_psy_dog(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return npc:clsid() == clsid.psy_dog_s
end

function is_monster_polter(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return npc:clsid() == clsid.poltergeist_s
end

function is_monster_tushkano(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return npc:clsid() == clsid.tushkano_s
end

function is_monster_burer(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return npc:clsid() == clsid.burer_s
end

function is_monster_controller(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return npc:clsid() == clsid.controller_s
end

function is_monster_flesh(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return npc:clsid() == clsid.flesh_s
end

function is_monster_boar(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return npc:clsid() == clsid.boar_s
end


function dead_body_searching(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return actor_menu.dead_body_searching
end

function jup_b47_npc_online(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
--	--printf_xrscript("function jup_b47_npc_online: story_obj[%s]", tostring(p[1]))
	local story_obj = get_story_object(p[1])
	if story_obj == nil then
		return false
	end
	local obj = alife():object(story_obj:id())
	return obj ~= nil
end

function anomaly_has_artefact(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local az_name = p and p[1]
	local af_name = p and p[2]

	local anomal_zone = db.anomaly_by_name[az_name]
	if anomal_zone == nil then
		return false
	end

	if anomal_zone.spawned_count < 1 then
		return false
	end

	if af_name == nil then
		local af_table = {}
		for k,v in pairs(anomal_zone.artefact_ways_by_id) do
			if alife():object(tonumber(k)) then
				table.insert(af_table, alife():object(tonumber(k)):section_name())
			end
		end
		return true, af_table
	end

	for k,v in pairs(anomal_zone.artefact_ways_by_id) do
		if alife():object(tonumber(k)) and af_name == alife():object(tonumber(k)):section_name() then
			return true
		end
	end

	return false
end

function zat_b29_anomaly_has_af(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local az_name = p and p[1]
	local af_name

	local anomal_zone = db.anomaly_by_name[az_name]
	if anomal_zone == nil then
		return false
	end

	if anomal_zone.spawned_count < 1 then
		return false
	end

	for i = 16, 23 do
		if has_alife_info(dialogs_zaton.zat_b29_infop_bring_table[i]) then
			af_name = dialogs_zaton.zat_b29_af_table[i]
			break
		end
	end

	for k,v in pairs(anomal_zone.artefact_ways_by_id) do
		if alife():object(tonumber(k)) and af_name == alife():object(tonumber(k)):section_name() then
			db.actor:give_info_portion(az_name)
			return true
		end
	end

	return false
end

function jup_b221_who_will_start(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc)) -- доступные параметры: ability - проверить есть ли доступные темы, choose - выбрать групировку которая начнет перепалку
	local reachable_theme = {}
	local faction_table = {}
	local info_table = {
---------duty
		[1] = "jup_b25_freedom_flint_gone",
		[2] = "jup_b25_flint_blame_done_to_duty",
		[3] = "jup_b4_monolith_squad_in_duty",
		[4] = "jup_a6_duty_leader_bunker_guards_work",
		[5] = "jup_a6_duty_leader_employ_work",
		[6] = "jup_b207_duty_wins",
---------freedom
		[7] = "jup_b207_freedom_know_about_depot",
		[8] = "jup_b46_duty_founder_pda_to_freedom",
		[9] = "jup_b4_monolith_squad_in_freedom",
		[10] = "jup_a6_freedom_leader_bunker_guards_work",
		[11] = "jup_a6_freedom_leader_employ_work",
		[12] = "jup_b207_freedom_wins"
	}
--Составляем таблицу достыпных тем(тлько номера тем).
	for k,v in pairs(info_table) do
		if k <= 6 then
			faction_table[1] = "duty"
			faction_table[2] = "0"
		else
			faction_table[1] = "freedom"
			faction_table[2] = "6"
		end
		if (has_alife_info(v)) and (not has_alife_info("jup_b221_" .. faction_table[1] .. "_main_" .. tostring(k - tonumber(faction_table[2])) .. "_played")) then
			table.insert(reachable_theme,k)
			--printf_xrscript("jup_b221_who_will_start: table reachable_theme ------------------------------> [%s]", tostring(k))
		end
	end
	if (p and p[1]) == nil then
		abort("No such parameters in function 'jup_b221_who_will_start'")
	end
	if tostring(p[1]) == "ability" then
		return #reachable_theme ~= 0 -- если таблица пуста значит нет доступных тем и ненадо играть сцену
	elseif  tostring(p[1]) == "choose" then
---------Выберем рандомам елемент составленой таблицы и проверим к какой груперовки он пренадлежит :)
		return reachable_theme[math.random(1, #reachable_theme)] <= 6 -- если меньше 6-ти значит ДОЛГ если больше 6-ти значит СВОБОДА
	else
		abort("Wrong parameters in function 'jup_b221_who_will_start'")
	end
end

function pas_b400_actor_far_forward(actor, npc)
	local fwd_obj = get_story_object("pas_b400_fwd")

	if fwd_obj then
		if distance_between(fwd_obj, db.actor) > distance_between(fwd_obj, npc) then
			return false
		end
	else
		return false
	end

	local distance = 70 * 70
	local self_dist = npc:position():distance_to_sqr(actor:position())
	if self_dist < distance then
		return false
	end

	local squad = alife():object(alife():object(npc:id()).group_id)

	for k in squad:squad_members() do
		local other_dist = k.object.position:distance_to_sqr(actor:position())
		if other_dist < distance then
			return false
		end
	end

	----printf_xrscript("npc: [%s], actor is far forward - self_dist [%s] distance [%s]", tostring(npc:name()), self_dist, distance)

	return true
end

function pas_b400_actor_far_backward(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local bwd_obj = get_story_object("pas_b400_bwd")

	if bwd_obj then
		if distance_between(bwd_obj, db.actor) > distance_between(bwd_obj, npc) then
			return false
		end
	else
		return false
	end

	local distance = 70 * 70
	local self_dist = npc:position():distance_to_sqr(actor:position())
	if self_dist < distance then
		return false
	end

	local squad = alife():object(alife():object(npc:id()).group_id)

	for k in squad:squad_members() do
		local other_dist = k.object.position:distance_to_sqr(actor:position())
		if other_dist < distance then
			return false
		end
	end

	----printf_xrscript("npc: [%s], actor is far backward - self_dist [%s] distance [%s]", tostring(npc:name()), self_dist, distance)

	return true
end

function pri_a28_actor_is_far(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local distance = 150 * 150
	local squad = get_story_squad("pri_a16_military_squad")

	for k in squad:squad_members() do
		local npc_dist = k.object.position:distance_to_sqr(actor:position())
		if npc_dist < distance then
			return false
		end
	end

	return true
end

function check_enemy_smart(actor , npc , p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local enemy_id = db.storage[npc:id()].enemy_id
	local enemy = db.storage[enemy_id] and db.storage[enemy_id].object
	if enemy == nil or enemy_id == alife():actor().id then
		return false
	end
	local enemy_smart = xr_gulag.get_npc_smart(enemy)

	if (enemy_smart ~= nil) and (enemy_smart:name() == p[1]) then
		return true
	end
	return false
end

function zat_b103_actor_has_needed_food(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return (dialogs_zaton.zat_b103_actor_has_needed_food(actor, npc)) or (has_alife_info("zat_b103_merc_task_done"))
end

function zat_b29_rivals_dialog_precond(actor, npc)
	local squads_table = {
						"zat_b29_stalker_rival_default_1_squad",
						"zat_b29_stalker_rival_default_2_squad",
						"zat_b29_stalker_rival_1_squad",
						"zat_b29_stalker_rival_2_squad"
						}

	local zones_table = {
						"zat_b29_sr_1",
						"zat_b29_sr_2",
						"zat_b29_sr_3",
						"zat_b29_sr_4",
						"zat_b29_sr_5",
						}

	local f_squad = false

	for k,v in pairs(squads_table) do
		if alife():object(alife():object(npc:id()).group_id):section_name() == v then
			f_squad = true
			break
		end
	end

	if not f_squad then
		return false
	end

	for k,v in pairs(zones_table) do
		if utils.npc_in_zone(npc, db.zone_by_name[v]) then
			return true
		end
	end

	return false
end

function polter_ignore_actor(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return npc:poltergeist_get_actor_ignore()
end

function burer_gravi_attack(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return npc:burer_get_force_gravi_attack()
end

-- burer_get_force_anti_aim doesn't exist at all, means outdated function
function burer_anti_aim(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return npc:burer_get_force_anti_aim()
end

function jup_b202_actor_treasure_not_in_steal(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local before = ((not has_alife_info("jup_b52_actor_items_can_be_stolen")) and (not has_alife_info("jup_b202_actor_items_returned")))
	local after  = (has_alife_info("jup_b52_actor_items_can_be_stolen") and has_alife_info("jup_b202_actor_items_returned"))
	return (before or after)
end

function jup_b25_senya_spawn_condition(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return (has_alife_info("jup_b16_oasis_found") or has_alife_info("zat_b57_bloodsucker_lair_clear") or has_alife_info("jup_b6_complete_end") or has_alife_info("zat_b215_gave_maps")) and has_alife_info("zat_b106_search_soroka")
end

function jup_b25_flint_gone_condition(actor, npc)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return has_alife_info("jup_b25_flint_blame_done_to_duty") or has_alife_info("jup_b25_flint_blame_done_to_freedom") or has_alife_info("zat_b106_found_soroka_done")
end

-------------------------------------------------------------------------------------------------------------------------------------------
--	STALKER TRADE FUNCTIONS
-------------------------------------------------------------------------------------------------------------------------------------------
function has_tradable_stuff(actor, npc)


end


-------------------------------------------------------------------------------------------------------------------------------------------
--	end of STALKER TRADE FUNCTIONS
-------------------------------------------------------------------------------------------------------------------------------------------


pioneer_functor = xr_statistic.pioneer_functor

mutant_hunter_functor = xr_statistic.mutant_hunter_functor

detective_functor = xr_statistic.detective_functor

one_of_the_lads_functor = xr_statistic.one_of_the_lads_functor

kingpin_functor = xr_statistic.kingpin_functor

herald_of_justice_functor = xr_statistic.herald_of_justice_functor

seeker_functor = xr_statistic.seeker_functor

battle_systems_master_functor = xr_statistic.battle_systems_master_functor

high_tech_master_functor = xr_statistic.high_tech_master_functor

skilled_stalker_functor = xr_statistic.skilled_stalker_functor

leader_functor = xr_statistic.leader_functor

diplomat_functor = xr_statistic.diplomat_functor

research_man_functor = xr_statistic.research_man_functor

friend_of_duty_functor = xr_statistic.friend_of_duty_functor

friend_of_freedom_functor = xr_statistic.friend_of_freedom_functor

balance_advocate_functor = xr_statistic.balance_advocate_functor

wealthy_functor = xr_statistic.wealthy_functor

keeper_of_secrets_functor = xr_statistic.keeper_of_secrets_functor

marked_by_zone_functor = xr_statistic.marked_by_zone_functor

information_dealer_functor = xr_statistic.information_dealer_functor

friend_of_stalkers_functor = xr_statistic.friend_of_stalkers_functor


--------------------------------------------------------------------------------
function check_deimos_phase(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	if(p[1] and p[2]) then
		local obj = db.storage[npc:id()]
		local delta = sr_deimos.check_intensity_delta(obj)
				if(p[2]=="increasing" and delta) then
						return false
				elseif(p[2]=="decreasing" and not(delta)) then
						return false
				end
		if(p[1]=="disable_bound") then
			if(p[2]=="increasing") then
								if not(sr_deimos.check_disable_bound(obj)) then
					return true
				end
			elseif(p[2]=="decreasing") then
								return sr_deimos.check_disable_bound(obj)
			end
		elseif(p[1]=="lower_bound") then
			if(p[2]=="increasing") then
								if not(sr_deimos.check_lower_bound(obj)) then
					return true
				end
			elseif(p[2]=="decreasing") then
								return sr_deimos.check_lower_bound(obj)
			end
		elseif(p[1]=="upper_bound") then
			if(p[2]=="increasing") then
								if not(sr_deimos.check_upper_bound(obj)) then
					return true
				end
			elseif(p[2]=="decreasing") then
								return sr_deimos.check_upper_bound(obj)
			end
		end
	end
end

--------------------------------------------------------------------------------

function actor_in_surge_cover(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	return surge_manager.actor_in_cover()
end

function is_door_blocked_by_npc(actor, obj)

	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(obj))
	return obj:is_door_blocked_by_npc()
end

function has_active_tutorial()
	return game.has_active_tutorial()
end

function upgrade_hint_kardan(actor, npc, p)
	--printf_xrscript("caller=%s npc=%s", convert_class_name(actor), convert_class_name(npc))
	local hint_table = {}
	local can_upgrade = 0
	local tools = (p and tonumber(p[1])) or 0

	if not has_alife_info("zat_b3_all_instruments_brought") then
		if not has_alife_info("zat_b3_tech_instrument_1_brought") and (tools == 0 or tools == 1) then
			table.insert(hint_table, "st_upgr_toolkit_1")
		elseif tools == 1 then
			can_upgrade = can_upgrade + 1
		end
		if not has_alife_info("zat_b3_tech_instrument_2_brought") and (tools == 0 or tools == 2) then
			table.insert(hint_table, "st_upgr_toolkit_2")
		elseif tools == 2 then
			can_upgrade = can_upgrade + 1
		end
		if not has_alife_info("zat_b3_tech_instrument_3_brought") and (tools == 0 or tools == 3) then
			table.insert(hint_table, "st_upgr_toolkit_3")
		elseif tools == 3 then
			can_upgrade = can_upgrade + 1
		end
	else
		can_upgrade = can_upgrade + 1
	end

	if not has_alife_info("zat_b3_tech_see_produce_62") then
		if (tools == 1) and not has_alife_info("zat_b3_tech_have_one_dose") then
			table.insert(hint_table, "st_upgr_vodka")
		elseif (tools ~= 1) and (not has_alife_info("zat_b3_tech_have_couple_dose")) then
			table.insert(hint_table, "st_upgr_vodka")
		else
			can_upgrade = can_upgrade + 1
		end
	else
		can_upgrade = can_upgrade + 1
	end

	inventory_upgrades.cur_hint = hint_table

	return can_upgrade >= 2
end

function zat_b29_stalkers_rivals_suitable(actor, npc)
	return check_npc_name(actor, npc, {"zat_b29_stalker_rival"}) and not has_alife_info("zat_b29_linker_take_af_from_rival") and has_alife_info("zat_b29_adv_task_given") and has_alife_info("zat_b29_stalkers_rivals_found_af")
end

function pri_a16_recon_squad_suitable(actor, npc)
	return not has_alife_info("pri_a17_actor_has_gauss_rifle") and not has_alife_info("pri_b305_fifth_cam_end") and target_squad_name(actor, npc, {"pri_a17_recon_squad"}) and not check_npc_name(actor, npc, {"pri_a17_military_captain_tarasov"})
end

function zat_b38_quest_line_on_info(actor, npc)
	return has_alife_info("zat_b38_disappearance_stalkers_find_to_be_missing_hunter_give") and not has_alife_info("zat_b38_disappearance_stalkers_find_to_be_missing_hunter_give_task")
end

function zat_b29_sr_rival_on_info(actor, npc)
	return has_alife_info("zat_b29_adv_task_given") and has_alife_info("zat_b29_exclusive_conditions") and not has_alife_info("zat_b29_second_rival_taken_out") and not story_object_exist(actor, npc, {"zat_b29_stalker_rival_2"})
end

function zat_b29_sr_rival_on_info2(actor, npc)
	return has_alife_info("zat_b29_adv_task_given") and not has_alife_info("zat_b29_exclusive_conditions") and not has_alife_info("zat_b29_second_rival_taken_out") and not story_object_exist(actor, npc, {"zat_b29_stalker_rival_default_2"})
end

function zat_b29_sr_rival_1_on_info2(actor, npc)
	return has_alife_info("zat_b29_adv_task_given") and not has_alife_info("zat_b29_exclusive_conditions") and not has_alife_info("zat_b29_first_rival_taken_out") and not story_object_exist(actor, npc, {"zat_b29_stalker_rival_default_1"})
end

function zat_b14_quest_line_on_info2(actor, npc)
	return not has_alife_info("zat_b14_recon_place") and has_alife_info("zat_b14_take_item") and not has_alife_info("zat_b14_learn_about_strange_occurrence_by_stalkers_give_task") and actor_has_item(actor, npc, {"af_quest_b14_twisted"})
end

function zat_b14_bar_zone_on_info(actor, npc)
	return not has_alife_info("zat_b14_cut_scene_1_start") and not has_alife_info("zat_b14_stalker_death") and has_alife_info("zat_b14_give_item_stalker") and has_alife_info("zat_b14_stalker_cut_scene_ready") and not actor_has_item(actor, npc, {"af_quest_b14_twisted"}) and actor_in_zone(actor, npc, {"zat_b14_bar_zone"})
end

function zat_b103_logic_on_info1(actor, npc)
	return has_alife_info("zat_b103_lost_merc_leader_bunker_guards_work") and distance_to_obj_ge(actor, npc, {"zat_b103_lost_merc_squad1","100"}) and squad_exist(actor, npc, {"zat_b103_lost_merc_squad1"}) and not has_alife_info("zat_b103_lost_merc_leader_destroed_for_bunker_guards_work1")
end

function zat_b103_logic_on_info1_1(actor, npc)
	return has_alife_info("zat_b103_lost_merc_leader_bunker_guards_work") and has_alife_info("zat_b215_guide_to_jupiter") and squad_exist(actor, npc, {"zat_b103_lost_merc_squad1"}) and not has_alife_info("zat_b103_lost_merc_leader_destroed_for_bunker_guards_work1")
end

function zat_b103_logic_on_info2(actor, npc)
	return has_alife_info("zat_b7_stalker_squad_leader_bunker_guards_work") and distance_to_obj_ge(actor, npc, {"zat_b7_stalkers_base_squad","100"}) and squad_exist(actor, npc, {"zat_b7_stalkers_base_squad"}) and not has_alife_info("zat_b7_stalker_squad_leader_destroed_for_bunker_guards_work")
end

function zat_b103_logic_on_info2_1(actor, npc)
	return has_alife_info("zat_b7_stalker_squad_leader_bunker_guards_work") and has_alife_info("zat_b215_guide_to_jupiter") and squad_exist(actor, npc, {"zat_b7_stalkers_base_squad"}) and not has_alife_info("zat_b7_stalker_squad_leader_destroed_for_bunker_guards_work")
end

function zat_b103_logic_on_info6(actor, npc)
	return has_alife_info("zat_b7_stalker_squad_leader_bunker_guards_work") and distance_to_obj_ge(actor, npc, {"zat_b7_stalkers_victims_1", "100"}) and squad_exist(actor, npc, {"zat_b7_stalkers_victims_1"}) and not has_alife_info("zat_b7_stalker_squad_leader_destroed_for_bunker_guards_work")
end

function zat_b103_logic_on_info6_1(actor, npc)
	return has_alife_info("zat_b7_stalker_squad_leader_bunker_guards_work") and has_alife_info("zat_b215_guide_to_jupiter") and squad_exist(actor, npc, {"zat_b7_stalkers_victims_1"}) and not has_alife_info("zat_b7_stalker_squad_leader_destroed_for_bunker_guards_work")
end

function zat_b103_logic_on_info3(actor, npc)
	return has_alife_info("zat_b103_lost_merc_leader_bunker_guards_work") and squad_exist(actor, npc, {"zat_b103_lost_merc_squad1"}) and not has_alife_info("zat_b103_lost_merc_relation_friend_set")
end

function zat_b103_logic_oni4(actor, npc)
	return has_alife_info("zat_b103_merc_fight") and has_alife_info("zat_b103_lost_merc_leader_bunker_guards_work")
end

function zat_b103_logic_oni4_1(actor, npc)
	return is_squad_enemy_to_actor(actor, npc, {"zat_b103_lost_merc_squad1"}) and has_alife_info("zat_b103_lost_merc_leader_bunker_guards_work")
end

function zat_b103_logic_oni5(actor, npc)
	return is_squad_enemy_to_actor(actor, npc, {"zat_b7_stalkers_base_squad"}) and has_alife_info("zat_b7_stalker_squad_leader_bunker_guards_work")
end

function zat_b107_logic_1(actor, npc)
	return has_alife_info("zat_b28_heli_3_searched") and not has_alife_info("jup_b9_blackbox_decrypted") and not has_alife_info("zat_b107_evacuation_info_partial")
end

function zat_b107_logic_5(actor, npc)
	return has_alife_info("zat_b107_evacuation_info_full") and not has_alife_info("jup_a9_actor_found_main_documents") and not has_alife_info("jup_a9_way_to_pripyat_search_started")
end

function zat_b107_logic_4(actor, npc)
	return has_alife_info("zat_b107_evacuation_info_full") and has_alife_info("jup_a9_way_info") and has_alife_info("jup_a9_conservation_info") and has_alife_info("jup_a9_power_info") and not has_alife_info("jup_a9_actor_found_main_documents")
end

function zat_b107_logic_2(actor, npc)
	return has_alife_info("jup_b9_blackbox_decrypted") and not has_alife_info("zat_b28_heli_3_searched") and not has_alife_info("zat_b107_evacuation_info_partial")
end

function zat_b7_stalker_victim_1(actor, npc)
	return not has_alife_info("zat_b7_attack_started") and squad_in_zone(actor, npc, {"zat_b7_stalkers_raiders","zat_b7_sr_stalkers_victims_attack"})
end

function zat_b38_quest_line_1(actor, npc)
	return has_alife_info("zat_b38_den_of_the_bloodsucker_inform_stalkers_give_task") and not squad_exist(actor, npc, {"zat_b38_bloodsuckers_sleepers"}) and counter_equal(actor, npc, {"zat_b57_terminated", "9"}) and not has_alife_info("zat_b57_den_of_the_bloodsucker_wait_destroy_give") and not has_alife_info("zat_b57_den_of_the_bloodsucker_tell_stalkers_about_destroy_lair_give")
end

function zat_b5_stalker_commander_1(actor, npc)
	return not has_alife_info("zat_b5_task_end") and target_squad_name(actor, npc, {"zat_b5_stalkers_squad"}) and not is_alive(actor, npc, {"zat_b5_stalker_commander_id"}) and not is_alive(actor, npc, {"zat_b5_stalker_commander_b7_id"}) and is_squad_commander(actor, npc)
end

function zat_b33_stalker_snag_1(actor, npc)
	return has_alife_info("zat_b52_reputation_task_open") and actor_has_active_nimble_weapon(actor, npc) and not has_alife_info("zat_b33_stalker_snag_b52_my_gun_dialog_done") and actor_in_zone(actor, npc, {"zat_b52_actor_restr"})
end

function zat_b33_stalker_snag_2(actor, npc)
	return has_alife_info("zat_b33_refuse_task") and actor_has_active_nimble_weapon(actor, npc) and not has_alife_info("zat_b33_stalker_snag_b52_my_gun_dialog_done") and actor_in_zone(actor, npc, {"zat_b52_actor_restr"})
end

function zat_b33_stalker_snag_3(actor, npc)
	return not has_alife_info("zat_b7_actor_killed_victims_self") and has_alife_info("zat_b7_actor_help_bandits") and has_alife_info("zat_b7_stalkers_raiders_reward_given") and has_alife_info("zat_b7_actor_really_helped_bandits")
end

function zat_b33_stalker_snag_4(actor, npc)
	return not has_alife_info("zat_b7_actor_killed_victims_self") and has_alife_info("zat_b7_actor_help_bandits") and has_alife_info("zat_b7_stalkers_raiders_reward_given") and not has_alife_info("zat_b7_actor_really_helped_bandits")
end

function zat_b7_sr_sra_1(actor, npc)
	return has_alife_info("zat_b7_stalkers_victims_know_about_raid") and not has_alife_info("zat_b7_victims_disappeared") and not has_alife_info("zat_b7_actor_with_stalkers") and has_alife_info("zat_b7_stalkers_raiders_attack") and dist_to_story_obj_ge(actor, npc, {"zat_b7_stalkers_victims_1","75"})
end

function zat_b7_stalkers_victims_1(actor, npc)
	return has_alife_info("zat_b7_actor_help_stalkers") and has_alife_info("zat_b7_stalkers_victims_reward_1_given") and not has_alife_info("zat_b7_actor_really_helped_stalkers") and not has_alife_info("zat_b7_victims_disappeared")
end

function zat_b7_sr_sra_2(actor, npc)
	return not is_alive(actor, npc, {"zat_b7_stalker_raider_leader"}) and target_squad_name(actor, npc, {"zat_b7_stalkers_raiders"}) and has_alife_info("zat_b7_stalkers_raiders_attack") and is_squad_commander(actor, npc)
end

function zat_b7_sr_sra_3(actor, npc)
	return target_squad_name(actor, npc, {"zat_b7_stalkers_raiders"}) and not check_npc_name(actor, npc, {"zat_b7_stalker_raider_leader"}) and has_alife_info("zat_b7_stalkers_raiders_attack") and not is_squad_commander(actor, npc)
end

function zat_b7_sr_sra_4(actor, npc)
	return target_squad_name(actor, npc, {"zat_b7_stalkers_raiders"}) and not check_npc_name(actor, npc, {"zat_b7_stalker_raider_leader"}) and has_alife_info("zat_b7_stalkers_raiders_attack") and not is_squad_commander(actor, npc)
end

function zat_b7_sr_sra_5(actor, npc)
	return target_squad_name(actor, npc, {"zat_b7_stalkers_raiders"}) and not check_npc_name(actor, npc, {"zat_b7_stalker_raider_leader"}) and has_alife_info("zat_b7_stalkers_raiders_attack") and not is_squad_commander(actor, npc)
end

function zat_b7_stalker_raider_1(actor, npc)
	return not squad_exist(actor, npc, {"zat_b7_stalkers_victims_1"}) and not has_alife_info("zat_b7_victims_disappeared") and not has_alife_info("zat_b7_actor_killed_victims_self") and not has_alife_info("zat_b7_stalkers_raiders_meet")
end

function zat_b7_sr_sra_6(actor, npc)
	return not is_squad_enemy_to_actor(actor, npc, {"zat_b7_stalkers_victims_1"}) and not has_alife_info("zat_b7_stalkers_victims_know_about_raid") and not has_alife_info("zat_b7_actor_really_helped_stalkers")
end

function zat_b7_sr_sra_7(actor, npc)
	return not is_squad_enemy_to_actor(actor, npc, {"zat_b7_stalkers_victims_1"}) and not has_alife_info("zat_b7_stalkers_victims_know_about_raid") and has_alife_info("zat_b7_actor_really_helped_stalkers")
end

function zat_b7_sr_sra_8(actor, npc)
	return not squad_exist(actor, npc, {"zat_b7_stalkers_victims_1"}) and not is_squad_enemy_to_actor(actor, npc, {"zat_b7_stalkers_raiders"}) and not has_alife_info("zat_b7_victims_disappeared") and has_alife_info("zat_b7_actor_with_bandits") and not has_alife_info("zat_b7_actor_killed_victims_self")
end

function zat_b7_sr_sra_9(actor, npc)
	return not squad_exist(actor, npc, {"zat_b7_stalkers_victims_1"}) and not is_squad_enemy_to_actor(actor, npc, {"zat_b7_stalkers_raiders"}) and not has_alife_info("zat_b7_victims_disappeared") and not has_alife_info("zat_b7_actor_with_bandits")
end

function zat_b7_sr_sra_10(actor, npc)
	return not has_alife_info("zat_b5_actor_stalker_go_to_trader") and not has_alife_info("zat_b5_stalker_attack_dealer") and not has_alife_info("zat_b5_destroy_enemy") and not has_alife_info("zat_b7_actor_now_duty_illicit_dealer") and not has_alife_info("zat_b5_actor_help_stalkers_pric") and not has_alife_info("zat_b5_meat")
end

function zat_b7_sr_sra_11(actor, npc)
	return not has_alife_info("zat_b5_stalker_attack_dealer") and not has_alife_info("zat_b5_destroy_enemy") and not has_alife_info("zat_b7_actor_now_duty_illicit_dealer") and not has_alife_info("zat_b5_actor_help_stalkers_pric") and not has_alife_info("zat_b5_meat")
end

function zat_b7_sr_sra_12(actor, npc)
	return not has_alife_info("zat_b5_actor_stalker_go_to_trader") and not has_alife_info("zat_b5_stalker_attack_dealer") and not has_alife_info("zat_b5_destroy_enemy") and not has_alife_info("zat_b7_actor_now_duty_illicit_dealer") and not has_alife_info("zat_b5_actor_help_stalkers_pric") and not has_alife_info("zat_b5_meat")
end

function zat_b7_sr_sra_13(actor, npc)
	return is_alive(actor, npc, {"zat_b5_stalker_commander_id"}) and not has_alife_info("zat_b5_actor_stalker_go_to_trader") and not has_alife_info("zat_b5_stalker_attack_dealer") and not has_alife_info("zat_b5_destroy_enemy") and not has_alife_info("zat_b7_actor_now_duty_illicit_dealer") and not has_alife_info("zat_b5_actor_help_stalkers_pric") and not has_alife_info("zat_b5_meat")
end

function zat_b7_sr_sra_14(actor, npc)
	return is_alive(actor, npc, {"zat_b5_stalker_commander_b7_id"}) and not has_alife_info("zat_b5_actor_stalker_go_to_trader") and not has_alife_info("zat_b5_stalker_attack_dealer") and not has_alife_info("zat_b5_destroy_enemy") and not has_alife_info("zat_b7_actor_now_duty_illicit_dealer") and not has_alife_info("zat_b5_actor_help_stalkers_pric") and not has_alife_info("zat_b5_meat")
end

function zat_b7_sr_sra_15(actor, npc)
	return not has_alife_info("zat_b5_stalker_attack_dealer") and not has_alife_info("zat_b5_destroy_enemy") and not has_alife_info("zat_b7_actor_now_duty_illicit_dealer") and not has_alife_info("zat_b5_actor_help_stalkers_pric") and not has_alife_info("zat_b5_meat")
end

function zat_b5_c_t_s_1(actor, npc)
	return not has_alife_info("zat_b5_stalker_attack_dealer") and not has_alife_info("zat_b5_destroy_enemy") and not has_alife_info("zat_b7_actor_now_duty_illicit_dealer") and not has_alife_info("zat_b5_actor_help_stalkers_pric") and not has_alife_info("zat_b5_meat")
end

function zat_b5_s_r_1_1(actor, npc)
	return has_alife_info("zat_b5_actor_with_stalkers") and not has_alife_info("zat_b5_stalker_death") and check_enemy_name(actor, npc, {"zat_b7_duty_illicit_dealer","zat_b5_dealer_assistant_2","zat_b5_dealer_assistant_1","zat_b5_actor_with_bandits","zat_b5_actor_with_dealer"})
end

function zat_b5_s_r_2_1(actor, npc)
	return has_alife_info("zat_b5_actor_with_stalkers") and not has_alife_info("zat_b5_stalker_death") and check_enemy_name(actor, npc, {"zat_b7_duty_illicit_dealer","zat_b5_dealer_assistant_2","zat_b5_dealer_assistant_1","zat_b5_actor_with_bandits","zat_b5_actor_with_dealer"})
end

function zat_b5_s_r_3_1(actor, npc)
	return has_alife_info("zat_b5_actor_with_stalkers") and not has_alife_info("zat_b5_stalker_death") and check_enemy_name(actor, npc, {"zat_b7_duty_illicit_dealer","zat_b5_dealer_assistant_2","zat_b5_dealer_assistant_1","zat_b5_actor_with_bandits","zat_b5_actor_with_dealer"})
end

function zat_b5_s_r_4_1(actor, npc)
	return has_alife_info("zat_b5_actor_with_stalkers") and not has_alife_info("zat_b5_stalker_death") and check_enemy_name(actor, npc, {"zat_b7_duty_illicit_dealer","zat_b5_dealer_assistant_2","zat_b5_dealer_assistant_1","zat_b5_actor_with_bandits","zat_b5_actor_with_dealer"})
end

function zat_b5_d_a_1_1(actor, npc)
	return not has_alife_info("zat_b5_stalker_death") and has_alife_info("zat_b5_actor_with_stalkers") and check_enemy_name(actor, npc, {"zat_b5_stalker_raider","zat_b7_bandit_boss","zat_b5_actor_with_bandits","zat_b5_actor_with_dealer"})
end

function zat_b5_d_a_2_1(actor, npc)
	return not has_alife_info("zat_b5_stalker_death") and has_alife_info("zat_b5_actor_with_stalkers") and check_enemy_name(actor, npc, {"zat_b5_stalker_raider","zat_b7_bandit_boss","zat_b5_actor_with_bandits","zat_b5_actor_with_dealer"})
end

function zat_b51_o_p_1(actor, npc)
	return has_alife_info("zat_b51_finished_category_1") and has_alife_info("zat_b51_finished_category_2") and has_alife_info("zat_b51_finished_category_3") and has_alife_info("zat_b51_finished_category_4") and has_alife_info("zat_b51_finished_category_5") and has_alife_info("zat_b51_finished_category_7")
end

function zat_b51_o_p_2(actor, npc)
	return has_alife_info("zat_b51_finished_category_1") and has_alife_info("zat_b51_finished_category_2") and has_alife_info("zat_b51_finished_category_3") and has_alife_info("zat_b51_finished_category_4") and has_alife_info("zat_b51_finished_category_5") and has_alife_info("zat_b51_finished_category_6") and has_alife_info("zat_b51_finished_category_7")
end

function zat_b100_h_2_c_1(actor, npc)
	return has_alife_info("zat_b100_heli_2_searched") and not is_obj_on_job(actor, npc, {"logic@zat_b100_poltergeist_02","zat_b100"}) and not squad_exist(actor, npc, {"zat_b100_poltergeist_squad_01"}) and distance_to_obj_ge(actor, npc, {"zat_b100_heli_2", "100"})
end

function zat_b29_sr_r_1_1(actor, npc)
	return has_alife_info("zat_b29_exclusive_conditions") and not has_alife_info("zat_b29_adv_task_given") and has_alife_info("zat_b29_first_rival_taken_out") and dist_to_story_obj_ge(actor, npc, {"zat_b29_stalker_rival_1", "150"})
end

function zat_b29_s_r_1_2(actor, npc)
	return has_alife_info("zat_b29_exclusive_conditions") and not has_alife_info("zat_b29_adv_task_given") and squad_exist(actor, npc, {"zat_b29_stalker_rival_1_squad"}) and dist_to_story_obj_ge(actor, npc, {"zat_b29_stalker_rival_1","150"})
end

function zat_b29_s_r_1_3(actor, npc)
	return not has_alife_info("zat_b29_exclusive_conditions") and not has_alife_info("zat_b29_adv_task_given") and has_alife_info("zat_b29_first_rival_taken_out") and dist_to_story_obj_ge(actor, npc, {"zat_b29_stalker_rival_default_1","150"})
end

function zat_b29_s_r_1_4(actor, npc)
	return not has_alife_info("zat_b29_exclusive_conditions") and not has_alife_info("zat_b29_adv_task_given") and squad_exist(actor, npc, {"zat_b29_stalker_rival_default_1_squad"}) and dist_to_story_obj_ge(actor, npc, {"zat_b29_stalker_rival_default_1","150"})
end

function zat_b29_sr_r_1_5(actor, npc)
	return has_alife_info("zat_b29_exclusive_conditions") and not has_alife_info("zat_b29_adv_task_given") and has_alife_info("zat_b29_first_rival_taken_out") and dist_to_story_obj_ge(actor, npc, {"zat_b29_stalker_rival_1","150"})
end

function zat_b29_sr_r_1_6(actor, npc)
	return has_alife_info("zat_b29_exclusive_conditions") and not has_alife_info("zat_b29_adv_task_given") and squad_exist(actor, npc, {"zat_b29_stalker_rival_1_squad"}) and dist_to_story_obj_ge(actor, npc, {"zat_b29_stalker_rival_1","150"})
end

function zat_b29_sr_r_1_7(actor, npc)
	return not has_alife_info("zat_b29_exclusive_conditions") and not has_alife_info("zat_b29_adv_task_given") and has_alife_info("zat_b29_first_rival_taken_out") and dist_to_story_obj_ge(actor, npc, {"zat_b29_stalker_rival_default_1","150"})
end

function zat_b29_sr_r_1_8(actor, npc)
	return not has_alife_info("zat_b29_exclusive_conditions") and not has_alife_info("zat_b29_adv_task_given") and squad_exist(actor, npc, {"zat_b29_stalker_rival_default_1_squad"}) and dist_to_story_obj_ge(actor, npc, {"zat_b29_stalker_rival_default_1","150"})
end

function zat_b29_sr_r_1_9(actor, npc)
	return has_alife_info("zat_b29_exclusive_conditions") and has_alife_info("zat_b29_stalker_rival_1_found_af") and squad_in_zone(actor, npc, {"zat_b29_stalker_rival_1_squad","zat_b29_sr_stalkers_base"})
end

function zat_b29_sr_r_1_10(actor, npc)
	return not has_alife_info("zat_b29_exclusive_conditions") and has_alife_info("zat_b29_stalker_rival_1_found_af") and squad_in_zone(actor, npc, {"zat_b29_stalker_rival_default_1_squad","zat_b29_sr_stalkers_base"})
end

function zat_b29_sr_r_2_1(actor, npc)
	return has_alife_info("zat_b29_exclusive_conditions") and not has_alife_info("zat_b29_adv_task_given") and has_alife_info("zat_b29_second_rival_taken_out") and dist_to_story_obj_ge(actor, npc, {"zat_b29_stalker_rival_2","150"})
end

function zat_b29_sr_r_2_2(actor, npc)
	return has_alife_info("zat_b29_exclusive_conditions") and not has_alife_info("zat_b29_adv_task_given") and squad_exist(actor, npc, {"zat_b29_stalker_rival_2_squad"}) and dist_to_story_obj_ge(actor, npc, {"zat_b29_stalker_rival_2","150"})
end

function zat_b29_sr_r_2_3(actor, npc)
	return not has_alife_info("zat_b29_exclusive_conditions") and not has_alife_info("zat_b29_adv_task_given") and has_alife_info("zat_b29_second_rival_taken_out") and dist_to_story_obj_ge(actor, npc, {"zat_b29_stalker_rival_default_2","150"})
end

function zat_b29_sr_r_2_4(actor, npc)
	return not has_alife_info("zat_b29_exclusive_conditions") and not has_alife_info("zat_b29_adv_task_given") and squad_exist(actor, npc, {"zat_b29_stalker_rival_default_2_squad"}) and dist_to_story_obj_ge(actor, npc, {"zat_b29_stalker_rival_default_2","150"})
end

function zat_b29_sr_r_2_5(actor, npc)
	return has_alife_info("zat_b29_exclusive_conditions") and not has_alife_info("zat_b29_adv_task_given") and has_alife_info("zat_b29_second_rival_taken_out") and dist_to_story_obj_ge(actor, npc, {"zat_b29_stalker_rival_2","150"})
end

function zat_b29_sr_r_2_6(actor, npc)
	return has_alife_info("zat_b29_exclusive_conditions") and not has_alife_info("zat_b29_adv_task_given") and squad_exist(actor, npc, {"zat_b29_stalker_rival_2_squad"}) and dist_to_story_obj_ge(actor, npc, {"zat_b29_stalker_rival_2","150"})
end

function zat_b29_sr_r_2_7(actor, npc)
	return not has_alife_info("zat_b29_exclusive_conditions") and not has_alife_info("zat_b29_adv_task_given") and has_alife_info("zat_b29_second_rival_taken_out") and dist_to_story_obj_ge(actor, npc, {"zat_b29_stalker_rival_default_2","150"})
end

function zat_b29_sr_r_2_8(actor, npc)
	return not has_alife_info("zat_b29_exclusive_conditions") and not has_alife_info("zat_b29_adv_task_given") and squad_exist(actor, npc, {"zat_b29_stalker_rival_default_2_squad"}) and dist_to_story_obj_ge(actor, npc, {"zat_b29_stalker_rival_default_2","150"})
end

function zat_b29_sr_r_2_9(actor, npc)
	return has_alife_info("zat_b29_exclusive_conditions") and has_alife_info("zat_b29_stalker_rival_2_found_af") and squad_in_zone(actor, npc, {"zat_b29_stalker_rival_2_squad","zat_b29_sr_stalkers_base"})
end

function zat_b29_sr_r_2_10(actor, npc)
	return not has_alife_info("zat_b29_exclusive_conditions") and has_alife_info("zat_b29_stalker_rival_2_found_af") and squad_in_zone(actor, npc, {"zat_b29_stalker_rival_default_2_squad","zat_b29_sr_stalkers_base"})
end

function zat_b29_sr_t_1(actor, npc)
	return squad_in_zone(actor, npc, {"zat_b29_stalker_rival_default_1_squad","zat_b29_sr_1"}) and not is_squad_enemy_to_actor(actor, npc, {"zat_b29_stalker_rival_default_1_squad"}) and not distance_to_obj_le(actor, npc, {"zat_b29_stalker_rival_default_1","30"}) and zat_b29_anomaly_has_af(actor, npc, {"zat_b55_anomal_zone"})
end

function zat_b29_sr_t_2(actor, npc)
	return squad_in_zone(actor, npc, {"zat_b29_stalker_rival_default_1_squad","zat_b29_sr_2"}) and not is_squad_enemy_to_actor(actor, npc, {"zat_b29_stalker_rival_default_1_squad"}) and not distance_to_obj_le(actor, npc, {"zat_b29_stalker_rival_default_1","30"}) and zat_b29_anomaly_has_af(actor, npc, {"zat_b54_anomal_zone"})
end

function zat_b29_sr_t_3(actor, npc)
	return squad_in_zone(actor, npc, {"zat_b29_stalker_rival_default_1_squad","zat_b29_sr_3"}) and not is_squad_enemy_to_actor(actor, npc, {"zat_b29_stalker_rival_default_1_squad"}) and not distance_to_obj_le(actor, npc, {"zat_b29_stalker_rival_default_1","30"}) and zat_b29_anomaly_has_af(actor, npc, {"zat_b53_anomal_zone"})
end


function zat_b29_sr_t_4(actor, npc)
	return squad_in_zone(actor, npc, {"zat_b29_stalker_rival_default_2_squad","zat_b29_sr_1"}) and not is_squad_enemy_to_actor(actor, npc, {"zat_b29_stalker_rival_default_2_squad"}) and not distance_to_obj_le(actor, npc, {"zat_b29_stalker_rival_default_2","30"}) and zat_b29_anomaly_has_af(actor, npc, {"zat_b55_anomal_zone"})
end

function zat_b29_sr_t_5(actor, npc)
	return squad_in_zone(actor, npc, {"zat_b29_stalker_rival_default_2_squad","zat_b29_sr_2"}) and not is_squad_enemy_to_actor(actor, npc, {"zat_b29_stalker_rival_default_2_squad"}) and not distance_to_obj_le(actor, npc, {"zat_b29_stalker_rival_default_2","30"}) and zat_b29_anomaly_has_af(actor, npc, {"zat_b54_anomal_zone"})
end

function zat_b29_sr_t_6(actor, npc)
	return squad_in_zone(actor, npc, {"zat_b29_stalker_rival_default_2_squad","zat_b29_sr_3"}) and not is_squad_enemy_to_actor(actor, npc, {"zat_b29_stalker_rival_default_2_squad"}) and not distance_to_obj_le(actor, npc, {"zat_b29_stalker_rival_default_2","30"}) and zat_b29_anomaly_has_af(actor, npc, {"zat_b53_anomal_zone"})
end

function zat_b29_sr_t_7(actor, npc)
	return squad_in_zone(actor, npc, {"zat_b29_stalker_rival_default_1_squad","zat_b29_sr_4"}) and not is_squad_enemy_to_actor(actor, npc, {"zat_b29_stalker_rival_default_1_squad"}) and not distance_to_obj_le(actor, npc, {"zat_b29_stalker_rival_default_1","30"}) and zat_b29_anomaly_has_af(actor, npc, {"zat_b39_anomal_zone"})
end

function zat_b29_sr_t_8(actor, npc)
	return squad_in_zone(actor, npc, {"zat_b29_stalker_rival_default_1_squad","zat_b29_sr_5"}) and not is_squad_enemy_to_actor(actor, npc, {"zat_b29_stalker_rival_default_1_squad"}) and not distance_to_obj_le(actor, npc, {"zat_b29_stalker_rival_default_1","30"}) and zat_b29_anomaly_has_af(actor, npc, {"zaton_b56_anomal_zone"})
end


function zat_b29_sr_t_9(actor, npc)
	return squad_in_zone(actor, npc, {"zat_b29_stalker_rival_default_2_squad","zat_b29_sr_4"}) and not is_squad_enemy_to_actor(actor, npc, {"zat_b29_stalker_rival_default_2_squad"}) and not distance_to_obj_le(actor, npc, {"zat_b29_stalker_rival_default_2","30"}) and zat_b29_anomaly_has_af(actor, npc, {"zat_b39_anomal_zone"})
end

function zat_b29_sr_t_10(actor, npc)
	return squad_in_zone(actor, npc, {"zat_b29_stalker_rival_default_2_squad","zat_b29_sr_5"}) and not is_squad_enemy_to_actor(actor, npc, {"zat_b29_stalker_rival_default_2_squad"}) and not distance_to_obj_le(actor, npc, {"zat_b29_stalker_rival_default_2","30"}) and zat_b29_anomaly_has_af(actor, npc, {"zaton_b56_anomal_zone"})
end

function zat_b29_sr_t_11(actor, npc)
	return squad_in_zone(actor, npc, {"zat_b29_stalker_rival_1_squad","zat_b29_sr_1"}) and not is_squad_enemy_to_actor(actor, npc, {"zat_b29_stalker_rival_1_squad"}) and not distance_to_obj_le(actor, npc, {"zat_b29_stalker_rival_1","30"}) and zat_b29_anomaly_has_af(actor, npc, {"zat_b55_anomal_zone"})
end

function zat_b29_sr_t_12(actor, npc)
	return squad_in_zone(actor, npc, {"zat_b29_stalker_rival_1_squad","zat_b29_sr_2"}) and not is_squad_enemy_to_actor(actor, npc, {"zat_b29_stalker_rival_1_squad"}) and not distance_to_obj_le(actor, npc, {"zat_b29_stalker_rival_1","30"}) and zat_b29_anomaly_has_af(actor, npc, {"zat_b54_anomal_zone"})
end

function zat_b29_sr_t_13(actor, npc)
	return squad_in_zone(actor, npc, {"zat_b29_stalker_rival_1_squad","zat_b29_sr_3"}) and not is_squad_enemy_to_actor(actor, npc, {"zat_b29_stalker_rival_1_squad"}) and not distance_to_obj_le(actor, npc, {"zat_b29_stalker_rival_1","30"}) and zat_b29_anomaly_has_af(actor, npc, {"zat_b53_anomal_zone"})
end

function zat_b29_sr_t_14(actor, npc)
	return squad_in_zone(actor, npc, {"zat_b29_stalker_rival_2_squad","zat_b29_sr_1"}) and not is_squad_enemy_to_actor(actor, npc, {"zat_b29_stalker_rival_2_squad"}) and not distance_to_obj_le(actor, npc, {"zat_b29_stalker_rival_2","30"}) and zat_b29_anomaly_has_af(actor, npc, {"zat_b55_anomal_zone"})
end

function zat_b29_sr_t_15(actor, npc)
	return squad_in_zone(actor, npc, {"zat_b29_stalker_rival_2_squad","zat_b29_sr_2"}) and not is_squad_enemy_to_actor(actor, npc, {"zat_b29_stalker_rival_2_squad"}) and not distance_to_obj_le(actor, npc, {"zat_b29_stalker_rival_2","30"}) and zat_b29_anomaly_has_af(actor, npc, {"zat_b54_anomal_zone"})
end

function zat_b29_sr_t_16(actor, npc)
	return squad_in_zone(actor, npc, {"zat_b29_stalker_rival_2_squad","zat_b29_sr_3"}) and not is_squad_enemy_to_actor(actor, npc, {"zat_b29_stalker_rival_2_squad"}) and not distance_to_obj_le(actor, npc, {"zat_b29_stalker_rival_2","30"}) and zat_b29_anomaly_has_af(actor, npc, {"zat_b53_anomal_zone"})
end

function zat_b29_sr_t_17(actor, npc)
	return squad_in_zone(actor, npc, {"zat_b29_stalker_rival_1_squad","zat_b29_sr_4"}) and not is_squad_enemy_to_actor(actor, npc, {"zat_b29_stalker_rival_1_squad"}) and not distance_to_obj_le(actor, npc, {"zat_b29_stalker_rival_1","30"}) and zat_b29_anomaly_has_af(actor, npc, {"zat_b39_anomal_zone"})
end

function zat_b29_sr_t_18(actor, npc)
	return squad_in_zone(actor, npc, {"zat_b29_stalker_rival_1_squad","zat_b29_sr_5"}) and not is_squad_enemy_to_actor(actor, npc, {"zat_b29_stalker_rival_1_squad"}) and not distance_to_obj_le(actor, npc, {"zat_b29_stalker_rival_1","30"}) and zat_b29_anomaly_has_af(actor, npc, {"zaton_b56_anomal_zone"})
end

function zat_b29_sr_t_19(actor, npc)
	return squad_in_zone(actor, npc, {"zat_b29_stalker_rival_2_squad","zat_b29_sr_4"}) and not is_squad_enemy_to_actor(actor, npc, {"zat_b29_stalker_rival_2_squad"}) and not distance_to_obj_le(actor, npc, {"zat_b29_stalker_rival_2","30"}) and zat_b29_anomaly_has_af(actor, npc, {"zat_b39_anomal_zone"})
end

function zat_b29_sr_t_20(actor, npc)
	return squad_in_zone(actor, npc, {"zat_b29_stalker_rival_2_squad","zat_b29_sr_5"}) and not is_squad_enemy_to_actor(actor, npc, {"zat_b29_stalker_rival_2_squad"}) and not distance_to_obj_le(actor, npc, {"zat_b29_stalker_rival_2","30"}) and zat_b29_anomaly_has_af(actor, npc, {"zaton_b56_anomal_zone"})
end

function jup_a12_s_d_1(actor, npc)
	return not has_alife_info("jup_a12_stalker_assaulter_told_story") and has_alife_info("jup_b217_welcome_tech_talked") and actor_in_zone(actor, npc, {"jup_a12_sr_stalkers_argue"}) and has_alife_info("jup_a12_stalker_assaulter_argued")
end

function jup_a9_l_1(actor, npc)
	return has_alife_info("zat_b107_evacuation_info_full") and has_alife_info("jup_a9_way_info") and not has_alife_info("jup_a9_conservation_info") and not has_alife_info("jup_a9_power_info") and not has_alife_info("jup_a9_way_to_pripyat_gas_info_started") and not has_alife_info("jup_a9_way_to_pripyat_power_info_started")
end

function jup_a9_l_2(actor, npc)
	return has_alife_info("zat_b107_evacuation_info_full") and not has_alife_info("jup_a9_way_info") and has_alife_info("jup_a9_conservation_info") and not has_alife_info("jup_a9_power_info") and not has_alife_info("jup_a9_way_to_pripyat_way_info_started") and not has_alife_info("jup_a9_way_to_pripyat_power_info_started")
end

function jup_a9_l_3(actor, npc)
	return has_alife_info("zat_b107_evacuation_info_full") and not has_alife_info("jup_a9_way_info") and not has_alife_info("jup_a9_conservation_info") and has_alife_info("jup_a9_power_info") and not has_alife_info("jup_a9_way_to_pripyat_way_info_started") and not has_alife_info("jup_a9_way_to_pripyat_gas_info_started")
end

function jup_a6_h_c_1(actor, npc)
	return jup_b202_actor_treasure_not_in_steal(actor, npc) and distance_to_obj_ge(actor, npc, {"jup_b202_actor_treasure","100"}) and counter_greater(actor, npc, {"jup_a6_actor_help_duty","1"}) and not has_alife_info("jup_a6_duty_leader_give_first_reward")
end

function jup_a6_h_c_2(actor, npc)
	return jup_b202_actor_treasure_not_in_steal(actor, npc) and distance_to_obj_ge(actor, npc, {"jup_b202_actor_treasure","100"}) and counter_greater(actor, npc, {"jup_a6_actor_help_freedom", "1"}) and not has_alife_info("jup_a6_freedom_leader_give_first_reward")
end

function jup_a6_h_c_3(actor, npc)
	return jup_b202_actor_treasure_not_in_steal(actor, npc) and distance_to_obj_ge(actor, npc, {"jup_b202_actor_treasure","100"}) and counter_greater(actor, npc, {"jup_a6_actor_help_duty","3"}) and not has_alife_info("jup_a6_duty_leader_give_second_reward")
end

function jup_a6_h_c_4(actor, npc)
	return jup_b202_actor_treasure_not_in_steal(actor, npc) and distance_to_obj_ge(actor, npc, {"jup_b202_actor_treasure","100"}) and counter_greater(actor, npc, {"jup_a6_actor_help_freedom","3"}) and not has_alife_info("jup_a6_freedom_leader_give_second_reward")
end

function jup_a6_h_c_5(actor, npc)
	return has_alife_info("jup_b46_counted") and has_alife_info("zat_b106_counted") and has_alife_info("jup_b4_counted") and has_alife_info("jup_b207_counted") and distance_to_obj_ge(actor, npc, {"jup_b202_actor_treasure","200"}) and jup_b202_actor_treasure_not_in_steal(actor, npc)
end

function jup_b6_c_1(actor, npc)
	return has_alife_info("jup_b6_anom_2_count_1_end") and has_alife_info("jup_b6_anom_2_count_2_end") and has_alife_info("jup_b6_anom_2_count_3_end") and has_alife_info("jup_b6_anom_2_count_4_end") and not has_alife_info("jup_b6_anom_2_reward_given")
end

function jup_b6_c_2(actor, npc)
	return has_alife_info("jup_b6_anom_1_count_1_end") and has_alife_info("jup_b6_anom_1_count_2_end") and has_alife_info("jup_b6_anom_1_count_3_end") and has_alife_info("jup_b6_anom_1_count_4_end") and not has_alife_info("jup_b6_anom_1_reward_given")
end

function jup_b6_t_1(actor, npc)
	return has_alife_info("jup_b6_two_anomaly_learned") and has_alife_info("jup_b6_start") and has_alife_info("jup_b6_st_mission") and squad_in_zone(actor, npc, {"jup_b6_stalker_freedom_squad","jup_b6_st_return_controller"})
end

function jup_b6_t_2(actor, npc)
	return has_alife_info("jup_b6_two_anomaly_learned") and has_alife_info("jup_b6_start") and has_alife_info("jup_b6_st_mission") and squad_in_zone(actor, npc, {"jup_b6_stalker_exprisoner_squad","jup_b6_st_return_controller"})
end

function jup_b6_t_3(actor, npc)
	return has_alife_info("jup_b6_two_anomaly_learned") and has_alife_info("jup_b6_start") and has_alife_info("jup_b6_st_mission") and squad_in_zone(actor, npc, {"jup_b6_stalker_duty_squad","jup_b6_st_return_controller"})
end

function jup_b6_t_4(actor, npc)
	return has_alife_info("jup_b6_two_anomaly_learned") and has_alife_info("jup_b6_start") and has_alife_info("jup_b6_st_mission") and squad_in_zone(actor, npc, {"jup_b6_stalker_gonta_squad","jup_b6_st_return_controller"})
end

function jup_b202_a_t_1(actor, npc)
	return distance_to_obj_ge(actor, npc, {"jup_b202_actor_treasure","200"}) and distance_to_obj_ge(actor, npc, {"jup_b202_snag_treasure","200"}) and not has_alife_info("jup_b202_inventory_box_empty") and not has_alife_info("jup_b52_actor_items_can_be_stolen") and has_alife_info("zat_b52_nimble_clear")
end

function jup_b202_a_t_2(actor, npc)
	return not has_alife_info("jup_b212_jupiter_chimera_hunt_mentioned") and not has_alife_info("jup_b212_jupiter_chimera_hunt_told") and has_alife_info("jup_b220_trapper_about_retire_told") and has_alife_info("jup_b208_burers_hunt_done") and not has_alife_info("jup_b212_trapper_found_chimera_play") and dist_to_actor_ge(actor, npc, {"100"})
end

function jup_b207_sr_c_1(actor, npc)
	return has_alife_info("jup_b207_attack_started") and has_alife_info("jup_b207_freedom_knows_about_depot") and not squad_exist(actor, npc, {"jup_b207_freedom_depot"}) and not squad_exist(actor, npc, {"jup_b207_freedom_base"})
end

function jup_b47_l_1(actor, npc)
	return has_alife_info("jup_b47_merc_leader_regret") and dist_to_story_obj_ge(actor, npc, {"jup_b47_merc_guard_squad","180"}) and squad_exist(actor, npc, {"jup_b47_merc_guard_squad"}) and not has_alife_info("jup_b47_attack_squad_removed")
end

function jup_a12_s_a_1(actor, npc)
	return has_alife_info("jup_b200_tech_materials_has") and not actor_has_item(actor, npc, {"jup_b200_tech_materials_wire"}) and not actor_has_item(actor, npc, {"jup_b200_tech_materials_acetone"}) and not actor_has_item(actor, npc, {"jup_b200_tech_materials_textolite"}) and not actor_has_item(actor, npc, {"jup_b200_tech_materials_transistor"}) and not actor_has_item(actor, npc, {"jup_b200_tech_materials_capacitor"})
end

function jup_a12_s_a_2(actor, npc)
	return has_alife_info("jup_b200_tech_materials_has") and not actor_has_item(actor, npc, {"jup_b200_tech_materials_wire"}) and not actor_has_item(actor, npc, {"jup_b200_tech_materials_acetone"}) and not actor_has_item(actor, npc, {"jup_b200_tech_materials_textolite"}) and not actor_has_item(actor, npc, {"jup_b200_tech_materials_transistor"}) and not actor_has_item(actor, npc, {"jup_b200_tech_materials_capacitor"})
end

function jup_b19_f_y_k_1(actor, npc)
	return not squad_exist(actor, npc, {"jup_b19_merc_squad"}) and has_alife_info("jup_b19_actor_damaged_zombied") and not squad_exist(actor, npc, {"jup_b19_kopatci_zombied_squad"}) and not has_alife_info("jup_b19_freedom_yar_explanations_done")
end

function jup_b19_f_y_k_2(actor, npc)
	return not squad_exist(actor, npc, {"jup_b19_merc_squad"}) and has_alife_info("jup_b19_actor_damaged_zombied") and not squad_exist(actor, npc, {"jup_b19_kopatci_zombied_squad"}) and has_alife_info("jup_b19_freedom_yar_explanations_done")
end

function jup_b32_sr_s_1(actor, npc)
	return not actor_in_zone(actor, npc, {"jup_b32_sr_scanner_place_1"}) and not actor_in_zone(actor, npc, {"jup_b32_sr_scanner_place_2"}) and not actor_in_zone(actor, npc, {"jup_b32_sr_scanner_place_3"}) and not actor_in_zone(actor, npc, {"jup_b32_sr_scanner_place_4"}) and not actor_in_zone(actor, npc, {"jup_b32_sr_scanner_place_5"})
end

function jup_b25_t_s_c_1(actor, npc)
	return is_obj_on_job(actor, npc, {"logic@jup_b221_duty_01","jup_a6"}) and is_obj_on_job(actor, npc, {"logic@jup_b221_duty_02","jup_a6"}) and is_obj_on_job(actor, npc, {"logic@jup_b221_duty_03","jup_a6"}) and is_obj_on_job(actor, npc, {"logic@jup_b221_freedom_01","jup_a6"}) and is_obj_on_job(actor, npc, {"logic@jup_b221_freedom_02","jup_a6"}) and is_obj_on_job(actor, npc, {"logic@jup_b221_freedom_02","jup_a6"})
end

function jup_b25_t_s_c_2(actor, npc)
	return is_obj_on_job(actor, npc, {"logic@jup_b221_duty_01","jup_a6"}) and is_obj_on_job(actor, npc, {"logic@jup_b221_duty_02","jup_a6"}) and is_obj_on_job(actor, npc, {"logic@jup_b221_duty_03","jup_a6"}) and is_obj_on_job(actor, npc, {"logic@jup_b221_freedom_01","jup_a6"}) and is_obj_on_job(actor, npc, {"logic@jup_b221_freedom_02","jup_a6"})
end

function jup_b6_t_1(actor, npc)
	return has_alife_info("jup_b6_two_anomaly_learned") and has_alife_info("jup_b6_st_mission") and squad_exist(actor, npc, {"jup_b6_stalker_freedom_squad"}) and has_alife_info("jup_b6_give_task") and has_alife_info("jup_b6_freedom_employed")
end

function jup_b6_t_2(actor, npc)
	return has_alife_info("jup_b6_two_anomaly_learned") and has_alife_info("jup_b6_st_mission") and squad_exist(actor, npc, {"jup_b1_stalker_squad"}) and has_alife_info("jup_b6_give_task") and not has_alife_info("jup_b6_freedom_employed") and not has_alife_info("jup_b6_duty_employed") and not has_alife_info("jup_b6_gonta_employed") and not has_alife_info("jup_b6_exprisoner_work_on_sci") and not has_alife_info("jup_b1_squad_is_dead")
end

function jup_b6_t_3(actor, npc)
	return not squad_exist(actor, npc, {"jup_b1_stalker_squad"}) and has_alife_info("jup_b6_give_task") and not has_alife_info("jup_b6_freedom_employed") and not has_alife_info("jup_b6_duty_employed") and not has_alife_info("jup_b6_gonta_employed") and not has_alife_info("jup_b6_exprisoner_work_on_sci") and has_alife_info("jup_b1_squad_is_dead")
end

function jup_b6_t_4(actor, npc)
	return is_squad_enemy_to_actor(actor, npc, {"jup_b1_stalker_squad"}) and has_alife_info("jup_b6_give_task") and not has_alife_info("jup_b6_freedom_employed") and not has_alife_info("jup_b6_duty_employed") and not has_alife_info("jup_b6_gonta_employed") and not has_alife_info("jup_b6_exprisoner_work_on_sci") and not has_alife_info("jup_b1_squad_is_dead")
end

function jup_b6_t_5(actor, npc)
	return has_alife_info("jup_b6_two_anomaly_learned") and has_alife_info("jup_b6_st_mission") and squad_exist(actor, npc, {"jup_b6_stalker_exprisoner_squad"}) and has_alife_info("jup_b6_give_task") and has_alife_info("jup_b6_exprisoner_work_on_sci")
end

function jup_b6_t_6(actor, npc)
	return squad_exist(actor, npc, {"jup_b1_stalker_squad"}) and has_alife_info("jup_b6_give_task") and not has_alife_info("jup_b6_freedom_employed") and not has_alife_info("jup_b6_duty_employed") and not has_alife_info("jup_b6_gonta_employed") and not has_alife_info("jup_b6_exprisoner_work_on_sci") and not has_alife_info("jup_b1_squad_is_dead")
end

function jup_b6_t_7(actor, npc)
	return has_alife_info("jup_b6_task_done") and not has_alife_info("jup_b1_stalker_1_is_dead") and not has_alife_info("jup_b1_stalker_2_is_dead") and not has_alife_info("jup_b1_stalker_3_is_dead") and not has_alife_info("jup_b1_stalker_4_is_dead") and dist_to_story_obj_ge(actor, npc, {"jup_b1_stalker_squad","140"})
end

function jup_b209_l_1(actor, npc)
	return has_alife_info("jup_b209_snork_7_death") and has_alife_info("jup_b209_snork_6_death") and has_alife_info("jup_b209_snork_5_death") and has_alife_info("jup_b209_snork_4_death") and has_alife_info("jup_b209_snork_3_death") and has_alife_info("jup_b209_snork_2_death") and has_alife_info("jup_b209_snork_1_death")
end

function jup_b4_f_l_1(actor, npc)
	return has_alife_info("jup_b4_freedom_monolit_soldier_2_near_fire") and has_alife_info("jup_b4_freedom_monolit_soldier_3_near_fire") and has_alife_info("jup_b4_freedom_monolit_leader_near_fire") and not has_alife_info("jup_b4_freedom_squad_leader_speech_sound")
end

function jup_b219_sr_c_1(actor, npc)
	return has_alife_info("jup_b219_azot_on_pos") and has_alife_info("jup_b219_zulus_on_pos") and has_alife_info("jup_b219_actor_on_pos") and has_alife_info("jup_b219_soldier_on_pos") and has_alife_info("jup_b219_monolith_on_pos") and has_alife_info("jup_b219_vano_on_pos")
end

function pas_b400_sr_s_n_1(actor, npc)
	return squad_exist(actor, npc, {"pas_b400_stalkers_squad"}) and is_squad_enemy_to_actor(actor, npc, {"pas_b400_stalkers_squad"}) and not counter_greater(actor, npc, {"pas_b400_actor_zulus_hit","2"}) and not counter_greater(actor, npc, {"pas_b400_actor_vano_hit","2"}) and not counter_greater(actor, npc, {"pas_b400_actor_sokolov_hit","2"}) and not counter_greater(actor, npc, {"pas_b400_actor_wanderer_hit","2"})
end

function pas_b400_sr_c_1(actor, npc)
	return not squad_has_enemy(actor, npc, {"pas_b400_stalkers_squad"}) and not squad_exist(actor, npc, {"pas_b400_snork_tunnel_5"}) and has_alife_info("pas_b400_zulus_about_train_gates_2") and has_alife_info("pas_b400_tunnel_gates_opened")
end

function pas_b400_sr_c_2(actor, npc)
	return not squad_has_enemy(actor, npc, {"pas_b400_stalkers_squad"}) and not squad_exist(actor, npc, {"pas_b400_snork_tunnel_5"}) and not is_alive(actor, npc, {"pas_b400_zulus"}) and has_alife_info("pas_b400_tunnel_gates_opened")
end

function pas_b400_sr_c_3(actor, npc)
	return has_alife_info("pas_b400_hall_monolith_squad_attacked") and not has_alife_info("pas_b400_hall_monolith_squad_dead") and not squad_exist(actor, npc, {"pas_b400_hall_monolith_squad"}) and not squad_exist(actor, npc, {"pas_b400_hall_monolith_2_squad"})
end

function pas_b400_sr_c_4(actor, npc)
	return has_alife_info("pas_b400_hall_monolith_snipers_attacked") and not has_alife_info("pas_b400_hall_monolith_snipers_dead") and not squad_exist(actor, npc, {"pas_b400_hall_monolith_sniper_1"}) and not squad_exist(actor, npc, {"pas_b400_hall_monolith_sniper_2"})
end

function pas_b400_g_1(actor, npc)
	return not has_alife_info("pas_b400_vano_dead") and not is_playing_sound(actor, npc) and is_alive(actor, npc) and not has_enemy(actor, npc) and hit_by_actor(actor, npc) and counter_equal(actor, npc, {"pas_b400_actor_vano_hit","2"}) and squad_exist(actor, npc, {"pas_b400_stalkers_squad"})
end

function pas_b400_g_2(actor, npc)
	return not has_alife_info("pas_b400_vano_dead") and not is_playing_sound(actor, npc) and is_alive(actor, npc) and not has_enemy(actor, npc) and hit_by_actor(actor, npc) and counter_equal(actor, npc, {"pas_b400_actor_vano_hit","1"}) and squad_exist(actor, npc, {"pas_b400_stalkers_squad"})
end

function pas_b400_g_3(actor, npc)
	return not has_alife_info("pas_b400_vano_dead") and not is_playing_sound(actor, npc) and is_alive(actor, npc) and not has_enemy(actor, npc) and hit_by_actor(actor, npc) and counter_equal(actor, npc, {"pas_b400_actor_vano_hit","0"}) and squad_exist(actor, npc, {"pas_b400_stalkers_squad"})
end

function pas_b400_g_4(actor, npc)
	return not has_alife_info("pas_b400_sokolov_dead") and not is_playing_sound(actor, npc) and is_alive(actor, npc) and not has_enemy(actor, npc) and hit_by_actor(actor, npc) and counter_equal(actor, npc, {"pas_b400_actor_sokolov_hit","2"}) and squad_exist(actor, npc, {"pas_b400_stalkers_squad"})
end

function pas_b400_g_5(actor, npc)
	return not has_alife_info("pas_b400_sokolov_dead") and not is_playing_sound(actor, npc) and is_alive(actor, npc) and not has_enemy(actor, npc) and hit_by_actor(actor, npc) and counter_equal(actor, npc, {"pas_b400_actor_sokolov_hit","1"}) and squad_exist(actor, npc, {"pas_b400_stalkers_squad"})
end

function pas_b400_g_6(actor, npc)
	return not has_alife_info("pas_b400_sokolov_dead") and not is_playing_sound(actor, npc) and is_alive(actor,npc) and not has_enemy(actor, npc) and hit_by_actor(actor, npc) and counter_equal(actor, npc, {"pas_b400_actor_sokolov_hit","0"}) and squad_exist(actor, npc, {"pas_b400_stalkers_squad"})
end

function pas_b400_g_7(actor, npc)
	return not has_alife_info("pas_b400_wanderer_dead") and not is_playing_sound(actor, npc) and is_alive(actor, npc) and not has_enemy(actor, npc) and hit_by_actor(actor, npc) and counter_equal(actor, npc, {"pas_b400_actor_wanderer_hit","2"}) and squad_exist(actor, npc, {"pas_b400_stalkers_squad"})
end

function pas_b400_g_8(actor, npc)
	return not has_alife_info("pas_b400_wanderer_dead") and not is_playing_sound(actor, npc) and is_alive(actor, npc) and not has_enemy(actor, npc) and hit_by_actor(actor, npc) and counter_equal(actor, npc, {"pas_b400_actor_wanderer_hit","1"}) and squad_exist(actor, npc, {"pas_b400_stalkers_squad"})
end

function pas_b400_g_9(actor, npc)
	return not has_alife_info("pas_b400_wanderer_dead") and not is_playing_sound(actor, npc) and is_alive(actor, npc) and not has_enemy(actor, npc) and hit_by_actor(actor, npc) and counter_equal(actor, npc, {"pas_b400_actor_wanderer_hit","0"}) and squad_exist(actor, npc, {"pas_b400_stalkers_squad"})
end

function pas_b400_g_10(actor, npc)
	return not has_alife_info("pas_b400_zulus_dead") and not is_playing_sound(actor, npc) and is_alive(actor, npc) and not has_enemy(actor, npc) and hit_by_actor(actor, npc) and counter_equal(actor, npc, {"pas_b400_actor_zulus_hit","2"}) and squad_exist(actor, npc, {"pas_b400_stalkers_squad"})
end

function pas_b400_g_11(actor, npc)
	return not has_alife_info("pas_b400_zulus_dead") and not is_playing_sound(actor, npc) and is_alive(actor, npc) and not has_enemy(actor, npc) and hit_by_actor(actor, npc) and counter_equal(actor, npc, {"pas_b400_actor_zulus_hit","1"}) and squad_exist(actor, npc, {"pas_b400_stalkers_squad"})
end

function pas_b400_g_12(actor, npc)
	return not has_alife_info("pas_b400_zulus_dead") and not is_playing_sound(actor, npc) and is_alive(actor, npc) and not has_enemy(actor, npc) and hit_by_actor(actor, npc) and counter_equal(actor, npc, {"pas_b400_actor_zulus_hit","0"}) and squad_exist(actor, npc, {"pas_b400_stalkers_squad"})
end

function pas_b400_sr_p_p_1(actor, npc)
	return not actor_in_zone(actor, npc, {"pas_b400_field_elevator"}) and not actor_in_zone(actor, npc, {"pas_b400_field_track"}) and not actor_in_zone(actor, npc, {"pas_b400_field_downstairs"}) and not actor_in_zone(actor, npc, {"pas_b400_field_tunnel"})
end

function pas_b400_t_1(actor, npc)
	return not has_alife_info("pas_b400_zulus_about_train_gates_1_can") and not squad_exist(actor, npc, {"pas_b400_snork_tunnel_3"}) and not squad_exist(actor, npc, {"pas_b400_snork_tunnel_4"}) and not has_alife_info("pas_b400_zulus_about_train_gates_1") and not has_alife_info("pas_b400_tunnel_gates_opened")
end

function pas_b400_h_1(actor, npc)
	return not has_alife_info("pas_b400_sokolov_about_door_1") and not is_alive_one(actor, npc, {"pas_b400_zulus","pas_b400_sokolov","pas_b400_wanderer"}) and has_alife_info("pas_b400_hall_door_opened") and has_alife_info("pas_b400_hall_monolith_snipers_dead")
end

function pas_b400_h_2(actor, npc)
	return not has_alife_info("pas_b400_about_cover") and npc_in_zone(actor, npc, {"pas_b400_sr_hall_6"}) and actor_in_zone(actor, npc, {"pas_b400_sr_control_stairs"}) and not squad_has_enemy(actor, npc, {"pas_b400_stalkers_squad"})
end

function pas_b400_h_3(actor, npc)
	return not has_alife_info("pas_b400_hall_door_opened") and has_alife_info("pas_b400_control_down_door_opened") and npc_in_zone(actor, npc, {"pas_b400_sr_hall_12"}) and not squad_has_enemy(actor, npc, {"pas_b400_stalkers_squad"}) and not has_alife_info("pas_b400_about_control_gates")
end

function pas_b400_h_4(actor, npc)
	return has_alife_info("pas_b400_about_railway") and not is_alive_one(actor, npc, {"pas_b400_zulus","pas_b400_wanderer"}) and npc_in_zone(actor, npc, {"pas_b400_sr_hall_11"}) and not squad_has_enemy(actor, npc, {"pas_b400_stalkers_squad"}) and not has_alife_info("pas_b400_about_transformer")
end

function pas_b400_h_5(actor, npc)
	return not has_alife_info("pas_b400_hall_door_opened") and has_alife_info("pas_b400_control_down_door_opened") and npc_in_zone(actor,npc,{"pas_b400_sr_hall_12"}) and not is_alive_one(actor, npc, {"pas_b400_sokolov","pas_b400_zulus"}) and not squad_has_enemy(actor, npc, {"pas_b400_stalkers_squad"}) and not has_alife_info("pas_b400_about_control_gates")
end

function pas_b400_h_6(actor, npc)
	return not has_alife_info("pas_b400_control_down_door_opened") and npc_in_zone(actor, npc, {"pas_b400_sr_hall_12"}) and not is_alive_one(actor, npc, {"pas_b400_zulus","pas_b400_sokolov","pas_b400_wanderer"}) and not has_alife_info("pas_b400_vano_about_railway_1")
end

function pas_b400_h_7(actor, npc)
	return not has_alife_info("pas_b400_about_cover") and not is_alive_one(actor, npc, {"pas_b400_zulus","pas_b400_vano"}) and npc_in_zone(actor, npc, {"pas_b400_sr_hall_6"}) and actor_in_zone(actor, npc, {"pas_b400_sr_control_stairs"}) and not squad_has_enemy(actor, npc, {"pas_b400_stalkers_squad"})
end

function pas_b400_h_8(actor, npc)
	return not has_alife_info("pas_b400_sokolov_about_transformer_1") and actor_in_zone(actor, npc, {"pas_b400_sr_hall_transformer"}) and npc_in_zone(actor, npc, {"pas_b400_sr_hall_11"}) and not squad_has_enemy(actor, npc, {"pas_b400_stalkers_squad"})
end

function pas_b400_h_9(actor, npc)
	return not has_alife_info("pas_b400_hall_door_opened") and has_alife_info("pas_b400_control_down_door_opened") and npc_in_zone(actor, npc, {"pas_b400_sr_hall_12"}) and not is_alive(actor, npc, {"pas_b400_zulus"}) and not squad_has_enemy(actor, npc, {"pas_b400_stalkers_squad"}) and not has_alife_info("pas_b400_about_control_gates")
end

function pas_b400_h_10(actor, npc)
	return not has_alife_info("pas_b400_about_cover") and not is_alive_one(actor, npc, {"pas_b400_zulus","pas_b400_vano","pas_b400_sokolov"}) and npc_in_zone(actor, npc, {"pas_b400_sr_hall_6"}) and actor_in_zone(actor, npc, {"pas_b400_sr_control_stairs"}) and not squad_has_enemy(actor, npc, {"pas_b400_stalkers_squad"})
end

function pas_b400_h_11(actor, npc)
	return has_alife_info("pas_b400_about_railway") and not is_alive(actor, npc, {"pas_b400_zulus"}) and npc_in_zone(actor, npc, {"pas_b400_sr_hall_11"}) and not squad_has_enemy(actor, npc, {"pas_b400_stalkers_squad"}) and not has_alife_info("pas_b400_about_transformer")
end

function pas_b400_h_12(actor, npc)
	return not has_alife_info("pas_b400_hall_door_opened") and has_alife_info("pas_b400_control_down_door_opened") and npc_in_zone(actor, npc, {"pas_b400_sr_hall_12"}) and not is_alive_one(actor, npc, {"pas_b400_zulus","pas_b400_sokolov","pas_b400_vano"}) and not squad_has_enemy(actor, npc, {"pas_b400_stalkers_squad"}) and not has_alife_info("pas_b400_about_control_gates")
end

function pas_b400_h_13(actor, npc)
	return has_alife_info("pas_b400_control_down_door_opened") and npc_in_zone(actor, npc, {"pas_b400_sr_hall_12"}) and not is_alive_one(actor, npc, {"pas_b400_sokolov","pas_b400_zulus"}) and not has_alife_info("pas_b400_about_railway")
end

function pas_b400_sr_c_5(actor, npc)
	return has_alife_info("pas_b400_canalisation_tushkano_attacked") and not has_alife_info("pas_b400_canalisation_snork_rl_spawned") and not actor_in_zone(actor, npc, {"pas_b400_sr_canalisation_tushkano_revert"})
end

function pri_a18_useidol_1(actor, npc)
	return actor_in_zone(actor, npc, {"pri_a18_use_idol_restrictor"}) and not squad_exist(actor, npc, {"pri_a18_monolith_idol_squad"}) and not squad_exist(actor, npc, {"pri_a18_monolith_post_guard_squad"}) and not squad_exist(actor, npc, {"pri_a18_monolith_corridor_squad"}) and not squad_exist(actor, npc, {"pri_a18_monolith_2nd_corridor_squad"}) and not has_alife_info("pri_a18_koval_go_on") and not surge_started(actor, npc)
end

function pri_a18_cam_r_1(actor, npc)
	return not has_alife_info("pri_a18_actor_enemy") and is_squad_enemy_to_actor(actor, npc, {"pri_a16_sokolov_squad","pri_a16_vano_squad","pri_a22_military_merkulov_squad","pri_a22_military_skelja_squad"})
end

function pri_b35_sr_c_1(actor, npc)
	return has_alife_info("pri_b35_attack_started") and not has_alife_info("pri_b35_envoy_escape") and not has_alife_info("pri_b35_envoy_out") and squad_exist(actor, npc, {"pri_b35_envoy_squad"}) and not actor_in_zone(actor, npc, {"pri_b35_sr_actor_position"})
end

function pri_b35_sr_c_2(actor, npc)
	return has_alife_info("pri_b35_attack_started") and not has_alife_info("pri_b35_merc_leader_escape") and not has_alife_info("pri_b35_merc_leader_out") and squad_exist(actor, npc, {"pri_b35_mercs_squad"}) and not actor_in_zone(actor, npc, {"pri_b35_sr_actor_position"})
end

function pri_a16_k_s_1(actor, npc)
	return has_alife_info("zat_a23_actor_has_gauss_rifle_documentation") and has_alife_info("pri_a20_talk_with_colonel_complete") and not has_alife_info("pri_a21_colonel_lets_talk") and not has_alife_info("pri_a21_give_task_no_base")
end

function pri_b35_h_l_1(actor, npc)
	return not has_alife_info("pri_a20_way_to_pripyat_2_sound_end") and not
	has_alife_info("pri_a20_talk_with_colonel_complete") and
	squad_in_zone(actor, npc, {"pri_a16_sokolov_squad","pri_a16_sr_noweap"}) and 
	has_alife_info("pri_a16_sokolov_on_pripyat")
end

function pri_b35_h_l_2(actor, npc)
	return not has_alife_info("pri_a25_rfi_source_eliminated") and
	has_alife_info("pri_a16_stalker_guide_met_done")  and
	has_alife_info("zat_a23_actor_has_gauss_rifle_documentation") and not
	has_alife_info("pri_b35_assistant_start_dialog_done") and not
	talking(actor, npc) and
	dist_to_actor_le(actor, npc, {"6"}) and
	see_actor(actor, npc) and not
	actor_enemy(actor, npc)
end

function pri_a18_i_m_1(actor, npc)
	return not squad_exist(actor, npc, {"pri_a18_monolith_idol_squad"}) 
	and not squad_exist(actor, npc, {"pri_a18_monolith_post_guard_squad"}) 
	and not squad_exist(actor, npc, {"pri_a18_monolith_corridor_squad"}) 
	and not squad_exist(actor, npc, {"pri_a18_monolith_2nd_corridor_squad"}) 
	and has_alife_info("pri_a18_find_antena")
end

function pri_a18_i_m_2(actor, npc)
	return not squad_exist(actor, npc, {"pri_a18_monolith_idol_squad"}) 
	and not squad_exist(actor, npc, {"pri_a18_monolith_post_guard_squad"}) 
	and not squad_exist(actor, npc, {"pri_a18_monolith_corridor_squad"}) 
	and not squad_exist(actor, npc, {"pri_a18_monolith_2nd_corridor_squad"}) 
	and has_alife_info("pri_a18_find_antena")
end

function pri_a18_i_m_3(actor, npc)
	return not squad_exist(actor, npc, {"pri_a18_monolith_idol_squad"}) 
	and not squad_exist(actor, npc, {"pri_a18_monolith_post_guard_squad"}) 
	and not squad_exist(actor, npc, {"pri_a18_monolith_corridor_squad"}) 
	and not squad_exist(actor, npc, {"pri_a18_monolith_2nd_corridor_squad"}) 
	and has_alife_info("pri_a18_find_antena")
end

function pri_a18_s_t_1(actor, npc)
	return not has_alife_info("pri_a18_vano_exist") 
	and not has_alife_info("pri_a18_sokolov_exist") 
	and squad_exist(actor, npc, {"pri_a22_military_merkulov_squad"}) 
	and squad_exist(actor, npc, {"pri_a22_military_skelja_squad"}) 
	and not has_alife_info("pri_a18_once_merkulov_and_skelja_remove")
end

function pri_a18_s_t_2(actor, npc)
	return has_alife_info("pri_a18_actor_enemy") 
	and has_alife_info("pri_a18_once_skelja_create") 
	and squad_exist(actor, npc, {"pri_a22_military_skelja_squad"}) 
	and dist_to_story_obj_ge(actor, npc, {"pri_a22_military_skelja_squad","100"})
end

function pri_a18_s_t_3(actor, npc)
	return has_alife_info("pri_a18_actor_enemy") 
	and has_alife_info("pri_a18_sokolov_exist")
	and squad_exist(actor, npc, {"pri_a16_sokolov_squad_strong"}) 
	and dist_to_story_obj_ge(actor, npc, {"pri_a16_sokolov_squad_strong","100"})
end

function pri_a18_s_t_4(actor, npc)
	return has_alife_info("pri_a18_actor_enemy") 
	and has_alife_info("pri_a18_once_skelja_create") 
	and squad_exist(actor, npc, {"pri_a22_military_skelja_squad_strong"}) 
	and dist_to_story_obj_ge(actor, npc, {"pri_a22_military_skelja_squad_strong","100"})
end

function pri_a18_s_t_5(actor, npc)
	return has_alife_info("pri_a18_actor_enemy") 
	and has_alife_info("pri_a18_vano_exist") 
	and squad_exist(actor, npc, {"pri_a16_vano_squad_strong"}) 
	and dist_to_story_obj_ge(actor, npc, {"pri_a16_vano_squad_strong","100"})
end

function pri_a18_s_t_6(actor, npc)
	return has_alife_info("pri_a18_actor_enemy") 
	and has_alife_info("pri_a18_once_merkulov_create") 
	and squad_exist(actor, npc, {"pri_a22_military_merkulov_squad"}) 
	and dist_to_story_obj_ge(actor, npc, {"pri_a22_military_merkulov_squad","100"})
end

function pri_a18_s_t_7(actor, npc)
	return has_alife_info("pri_a18_actor_enemy") 
	and has_alife_info("pri_a18_once_merkulov_create") 
	and squad_exist(actor, npc, {"pri_a22_military_merkulov_squad_strong"}) 
	and dist_to_story_obj_ge(actor, npc, {"pri_a22_military_merkulov_squad_strong","100"})
end

function pri_a28_k_1(actor, npc)
	return not has_alife_info("pri_a28_supply_done") 
	and not has_alife_info("pri_a25_actor_needs_medikit_supply")
	and has_alife_info("pri_a22_army_signaller_supply_outfit_done")
	and not has_alife_info("pri_a22_actor_needs_ammo_supply") 
	and not has_alife_info("pri_a22_actor_needs_grenade_supply")
end

function pri_a28_b_1(actor, npc)
	return not has_alife_info("pri_a28_base_done") 
	and target_squad_name(actor, npc, {"pri_a16_military_squad"}) 
	and not check_npc_name(actor, npc, {"strelok"}) 
	and not check_npc_name(actor, npc, {"army_signaller"}) 
	and not check_npc_name(actor, npc, {"kovalski"})
end

function pri_a28_s_1(actor, npc)
	return not has_alife_info("pri_a28_shop_done") 
	and target_squad_name(actor, npc, {"pri_a16_military_squad"}) 
	and not check_npc_name(actor, npc, {"strelok"}) 
	and not check_npc_name(actor, npc, {"base_medic"}) 
	and not check_npc_name(actor, npc, {"kovalski"})
end

function pri_a28_school_1(actor, npc)
	return not has_alife_info("pri_a28_school_done") 
	and target_squad_name(actor, npc, {"pri_a16_military_squad"}) 
	and not check_npc_name(actor, npc, {"strelok"}) 
	and not check_npc_name(actor, npc, {"kovalski"}) 
	and not check_npc_name(actor, npc, {"base_medic"})
end

function pri_a28_e_1(actor, npc)
	return not has_alife_info("pri_a28_evac_done") 
	and target_squad_name(actor, npc, {"pri_a16_military_squad"}) 
	and not check_npc_name(actor, npc, {"strelok"}) 
	and not check_npc_name(actor, npc, {"base_medic"}) 
	and not check_npc_name(actor, npc, {"kovalski"})
end