local actor_exists = false

function has_actor()
	if actor_exists then
		return true
	end
	
	actor_exists = db.actor ~= nil
	
	return actor_exists
end

-- Вернуть серверный обьект по ид если валидный или false
function se_object_by_id_or_false(id)
	return se_object_or_false(alife():object(id))
end

-- Вернуть серверный обьект если валидный или false
function se_object_or_false(se_obj)
	if se_obj and se_obj.id then
		return se_obj
	end

	return false
end

-- Вернуть клиентский обьект если валидный или false
function game_object_or_false(g_obj)
	if g_obj and g_obj:id() then
		return g_obj
	end

	return false
end

function is_actor_alive()
	return has_actor() and db.actor:alive()
end

function safe_release(p,force)
	local sim = alife()
	local se_obj = p[1] and sim:object(p[1])
	if not (se_obj) then
		return true
	end
	
	if (force) then 
		sim:release(se_obj,true)
	end

	if (se_obj.online) then
		if (se_obj:can_switch_offline()) then
			se_obj:switch_offline()
		end
		return false
	end
	
	sim:release(se_obj,true)

	return true
end


function release(se_obj)
	if (se_obj) then
		local sim = alife()
		sim:release(se_obj,true)
	end
end

function create(tbl)
	alife():create(tbl[1] ,tbl[2], tbl[3], tbl[4])
end

function get_inv_name(section)
	local ini = system_ini()

	return game.translate_string(ini:section_exist(section) and ini:line_exist(section, "inv_name") and ini:r_string(section, "inv_name") or section) or section
end 

function safe_bone_pos(npc, bone)
    if not (npc) then
		printf("safe_bone_pos: npc is nil!")
		return
    end
	
	local pos
	if (IsStalker(npc)) then
		pos = npc:bone_position(bone or "bip01_spine")
		pos = pos and vector():set(pos) or nil
	end

	if not (pos) then
		pos = vector():set(npc:position())
		pos.y = pos.y + 0.5
	end

	return pos
end

function safe_release_by_id(id)
	if id then
		local sobj = alife():object(id)
		if sobj and sobj.id then
			alife():release(sobj, true)
		end
	end
end

--safe
function set_condition_by_id(id, float_condition)
	level.client_spawn_manager():add(id, -1, function (id_gobj, gobj_client)
		set_condition(gobj_client, float_condition)
		return ;
	end)
end

--safe
function set_condition(gobj_client, float_condition)
	if gobj_client and gobj_client:id() then
		if float_condition <= 0 then
			float_condition = 0.0
		end
		
		if float_condition >= 1.0 then
			float_condition = 1.0
		end
		
		gobj_client:set_condition(float_condition)
	end
end