
-- IXR FFx0001 Упрощенная система (подписки и отписки) для движковых коллбеков в биндерах
function manage_callbacks(script_name, all_callbacks, _ref, is_set, use_callback_logs, beforeSetAction, beforeUnsetAction)
	if use_callback_logs == nil then
		use_callback_logs = false
	end
	
	local obj_id = _ref.object:id() or nil
	if is_set then
		if beforeSetAction then beforeSetAction(obj_id) end
	else
		if beforeUnsetAction then beforeUnsetAction(obj_id) end
	end
	
	for callback_name, callable_function in pairs(all_callbacks) do 
		if (callback[callback_name]) then 
			if _ref[callable_function] then 
				if is_set then 
					local wrapper = function(...)
                        return _proxy_call(callback_name, script_name, _ref, callable_function, ...)
                    end
					local msg = "binder ["..script_name.."] register callback:[" .. tostring(callback_name).."]"
					PROF_EVENT_CLOSURE("+ " .. msg, function()
						_ref.object:set_callback(callback[callback_name], wrapper, _ref)
					end)
					
					custom_log(msg, is_set, use_callback_logs, script_name, obj_id)
				else
					local msg = "binder ["..script_name.."] unregister callback:[" .. tostring(callback_name).."]"
					PROF_EVENT_CLOSURE("- ".. msg, function()
						_ref.object:set_callback(callback[callback_name], nil)
					end)
					
					custom_log(msg, is_set, use_callback_logs, script_name, obj_id)
				end
			else
				custom_log("! WARNING missing callable function [" .. tostring(callable_function) .. "] for callback [" .. tostring(callback_name) .. "] in binder script name:[" .. tostring(script_name) .. "]", is_set, use_callback_logs, script_name, obj_id)
			end
		else
			custom_log("! WARNING missing callback:[" .. tostring(callback_name) .. "] in engine", is_set, use_callback_logs, script_name, obj_id)
		end
	end
end

function custom_log(text, is_set, use_callback_logs, script_name, obj_id)
	if use_callback_logs then
		local prefix = "[-]"
		if is_set then
			prefix = "[+]"
		end
		
		SemiLog(prefix .. " binder:[".. tostring(script_name) .. ".script] object:[" .. tostring(obj_id) .. "] " ..tostring(text))
	end
end

function _proxy_call(callback_name, script_name, _ref, callable_function, ...)
	local args = {...}
	return PROF_EVENT_CLOSURE("engine call binder:[" .. tostring(script_name) .. "] callback:[" .. tostring(callback_name) .. "]", function()
		return _ref[callable_function](unpack(args))
	end)
end