#include "stdafx.h"
#include "DetailManager.h"

// Sparse user paint masks layered on top of the baked/generated fields.
//
// Files live in the same $level$\detail_layers\ folder as the precomputed bake,
// prefixed "user_mask_" so a bake/level reload never regenerates the user strokes
// out of existence:
//   user_mask_detail_fmb_noise.bin     - u32 corner idx + float fmb DELTA (signed)
//   user_mask_detail_perlin_scale.bin  - u32 slot idx + u8 cluster asset idx (255 = native / no mix)
//
// FMB semantics: an entry stores a signed DELTA added on top of the baked base field
// at every cache_ReInitialize (view the fold in DetailLayers_ApplyUserMasks). Painting
// writes the delta needed to reach the painted value, so it can push the field BELOW
// the baked grass (negative delta, down to clear/bare at 0) or ABOVE it - the final
// value is clamped to the grass height range [0..1]. Cells without an entry keep
// whatever the generator/bake produced. Applying masks never touches the base arrays,
// so bakes stay clean and can be regenerated by console commands while the user
// artwork is simply re-laid on top at every cache_ReInitialize.
//
// Naming matches the bake files (precomputed_detail_fmb_noise.bin /
// precomputed_detail_perlin_scale.bin) with the user_mask_ prefix.

#ifndef _EDITOR

namespace
{
constexpr u32 UM_MK_FMB = u32('U') | (u32('F') << 8) | (u32('M') << 16) | (u32('B') << 24);
constexpr u32 UM_MK_CLU = u32('U') | (u32('C') << 8) | (u32('L') << 16) | (u32('U') << 24);
constexpr u32 UM_VERSION = 2; // v2: FMB entries store signed deltas vs the baked base

constexpr const char* UM_FMB_FILE = "detail_layers\\user_mask_detail_fmb_noise.bin";
constexpr const char* UM_CLU_FILE = "detail_layers\\user_mask_detail_perlin_scale.bin";

constexpr float FMB_CLEAR_GRASS = -1.f; // sentinel stored whenever a stroke erases grass

#pragma pack(push, 1)
struct UM_Header
{
	u32 magic;
	u32 version;
	u32 size_x;
	u32 size_z;
	s32 offs_x;
	s32 offs_z;
	u32 settings_crc; // informational; masks apply regardless of detail settings
	u32 data_size;
};
#pragma pack(pop)

static_assert(sizeof(UM_Header) == 32, "UM_Header size");

// world pos -> fmb corner grid index ((sx+1)*(sz+1)), nearest corner. Returns size() if outside.
u32 WorldToFMBIdx(const CDetailManager* mgr, float world_x, float world_z)
{
	const u32 sx = mgr->dtH.size_x;
	const u32 sz = mgr->dtH.size_z;
	if (sx == 0 || sz == 0)
		return 0xffffffff;

	const int x = iFloor(world_x / dm_slot_size + 0.5f) + mgr->dtH.offs_x;
	const int z = iFloor(world_z / dm_slot_size + 0.5f) + mgr->dtH.offs_z;
	if (x < 0 || z < 0 || (u32)x > sx || (u32)z > sz)
		return 0xffffffff;
	return (u32)z * (sx + 1) + (u32)x;
}

// world pos -> cluster slot grid index (sx*sz). Returns size() if outside.
u32 WorldToClusterIdx(const CDetailManager* mgr, float world_x, float world_z)
{
	const u32 sx = mgr->dtH.size_x;
	const u32 sz = mgr->dtH.size_z;
	if (sx == 0 || sz == 0)
		return 0xffffffff;

	const int x = iFloor(world_x / dm_slot_size) + mgr->dtH.offs_x;
	const int z = iFloor(world_z / dm_slot_size) + mgr->dtH.offs_z;
	if (x < 0 || z < 0 || (u32)x >= sx || (u32)z >= sz)
		return 0xffffffff;
	return (u32)z * sx + (u32)x;
}

// Upsert a sorted sparse entry (sorts by idx). Returns true if an existing entry was updated.
template<typename Entry> bool Upsert(xr_vector<Entry>& vec, u32 idx, decltype(Entry::value) value)
{
	Entry key = {};
	key.idx = idx;
	key.value = value;
	auto it = std::lower_bound(vec.begin(), vec.end(), key,
		[](const Entry& a, const Entry& b) { return a.idx < b.idx; });
	if (it != vec.end() && it->idx == idx)
	{
		it->value = value;
		return true;
	}
	vec.insert(it, key);
	return false;
}

template<typename Entry> bool Remove(xr_vector<Entry>& vec, u32 idx)
{
	Entry key = {};
	key.idx = idx;
	auto it = std::lower_bound(vec.begin(), vec.end(), key,
		[](const Entry& a, const Entry& b) { return a.idx < b.idx; });
	if (it != vec.end() && it->idx == idx)
	{
		vec.erase(it);
		return true;
	}
	return false;
}
} // namespace

void CDetailManager::DetailLayers_LoadUserMasks()
{
	u32 sx = dtH.size_x;
	u32 sz = dtH.size_z;
	user_fmb_mask.clear();
	user_clu_mask.clear();
	if (sx == 0 || sz == 0)
		return;

	// FMB mask
	{
		IReader* R = FS.r_open("$level$", UM_FMB_FILE);
		if (R && R->length() >= (intptr_t)sizeof(UM_Header))
		{
			UM_Header h;
			R->r(&h, sizeof(UM_Header));
			const u32 corner_count = (sx + 1) * (sz + 1);
			if (h.magic == UM_MK_FMB && h.version == UM_VERSION
				&& h.size_x == sx && h.size_z == sz
				&& h.offs_x == dtH.offs_x && h.offs_z == dtH.offs_z
				&& h.data_size <= corner_count * sizeof(FMBMaskEntry)
				&& R->length() >= (intptr_t)(sizeof(UM_Header) + h.data_size))
			{
				user_fmb_mask.resize(h.data_size / sizeof(FMBMaskEntry));
				if (!user_fmb_mask.empty())
					R->r(user_fmb_mask.data(), h.data_size);
			}
		}
		if (R)
			FS.r_close(R);
	}

	// Cluster mask
	{
		IReader* R = FS.r_open("$level$", UM_CLU_FILE);
		if (R && R->length() >= (intptr_t)sizeof(UM_Header))
		{
			UM_Header h;
			R->r(&h, sizeof(UM_Header));
			const u32 slot_count = sx * sz;
			if (h.magic == UM_MK_CLU && h.version == UM_VERSION
				&& h.size_x == sx && h.size_z == sz
				&& h.offs_x == dtH.offs_x && h.offs_z == dtH.offs_z
				&& h.data_size <= slot_count * sizeof(CLUMaskEntry)
				&& R->length() >= (intptr_t)(sizeof(UM_Header) + h.data_size))
			{
				user_clu_mask.resize(h.data_size / sizeof(CLUMaskEntry));
				if (!user_clu_mask.empty())
					R->r(user_clu_mask.data(), h.data_size);
			}
		}
		if (R)
			FS.r_close(R);
	}

	if (!user_fmb_mask.empty() || !user_clu_mask.empty())
		Msg("* detail_layers: loaded %zu fmb + %zu cluster user mask entries",
			user_fmb_mask.size(), user_clu_mask.size());
}

void CDetailManager::DetailLayers_SaveUserMasks()
{
	u32 sx = dtH.size_x;
	u32 sz = dtH.size_z;
	if (sx == 0 || sz == 0)
		return;

	// FMB mask
	{
		UM_Header h = {};
		h.magic = UM_MK_FMB;
		h.version = UM_VERSION;
		h.size_x = sx;
		h.size_z = sz;
		h.offs_x = dtH.offs_x;
		h.offs_z = dtH.offs_z;
		h.data_size = (u32)(user_fmb_mask.size() * sizeof(FMBMaskEntry));

		IWriter* W = FS.w_open("$level$", UM_FMB_FILE);
		if (W)
		{
			W->w(&h, sizeof(h));
			if (!user_fmb_mask.empty())
				W->w(user_fmb_mask.data(), h.data_size);
			FS.w_close(W);
		}
	}

	// Cluster mask
	{
		UM_Header h = {};
		h.magic = UM_MK_CLU;
		h.version = UM_VERSION;
		h.size_x = sx;
		h.size_z = sz;
		h.offs_x = dtH.offs_x;
		h.offs_z = dtH.offs_z;
		h.data_size = (u32)(user_clu_mask.size() * sizeof(CLUMaskEntry));

		IWriter* W = FS.w_open("$level$", UM_CLU_FILE);
		if (W)
		{
			W->w(&h, sizeof(h));
			if (!user_clu_mask.empty())
				W->w(user_clu_mask.data(), h.data_size);
			FS.w_close(W);
		}
	}

	Msg("* detail_layers: saved %zu fmb + %zu cluster user mask entries",
		user_fmb_mask.size(), user_clu_mask.size());
}

// Snapshot the working fields into base so a later erase can restore generator value.
// Must be called after bake-load/build and BEFORE ApplyUserMasks.
void CDetailManager::DetailLayers_CommitBaseFields()
{
	if (!fmb_field.empty())
		fmb_field_base = fmb_field;
	if (!cluster_field.empty())
		cluster_field_base = cluster_field;
	if (!cluster_rnd_field.empty())
		cluster_rnd_field_base = cluster_rnd_field;
}

// Lay every sparse mask entry on top of the working fields. No entries => no-op.
void CDetailManager::DetailLayers_ApplyUserMasks()
{
	if (fmb_field.size() < (size_t)((dtH.size_x + 1) * (dtH.size_z + 1)))
		return;
	if (cluster_field.size() < (size_t)(dtH.size_x * dtH.size_z))
		return;

	for (const auto& e : user_fmb_mask)
	{
		if (e.idx < fmb_field.size())
		{
			// Signed delta added to the baked base, clamped to the grass height range.
			// Negatives push below the baked grass (bare at 0), positives build up to the
			// console's max grass height (1). Erasing below 0 is the "no grass" state.
			const float base_v = (e.idx < fmb_field_base.size()) ? fmb_field_base[e.idx] : 0.f;
			fmb_field[e.idx] = clampr(base_v + e.value, -1.f, 1.f);
		}
	}

	for (const auto& e : user_clu_mask)
		if (e.idx < cluster_field.size())
			cluster_field[e.idx] = e.value;
}

// Remove one corner's delta and restore the generated value, blending with strength.
// A cell that reaches the base value is dropped from the sparse mask entirely.
bool CDetailManager::DetailLayers_EraseFMB(float world_x, float world_z, float strength)
{
	u32 idx = WorldToFMBIdx(this, world_x, world_z);
	if (idx == 0xffffffff || idx >= fmb_field.size())
		return false;

	const float base_v = (idx < fmb_field_base.size()) ? fmb_field_base[idx] : 0.f;
	// Erase winds the stored delta back toward zero (= the baked grass).
	const float new_delta = (fmb_field[idx] - base_v) * (1.f - strength);
	if (std::abs(new_delta) < 1e-4f)
	{
		fmb_field[idx] = base_v;
		return Remove(user_fmb_mask, idx);
	}
	fmb_field[idx] = clampr(base_v + new_delta, -1.f, 1.f);
	return !!Upsert(user_fmb_mask, idx, new_delta);
}

// Upsert a corner delta blended from the current one toward (target - base) by strength.
// The painted target is clamped to [0..1] (0 = bare, 1 = max grass height from the
// console); FMB_CLEAR_GRASS (-1) stays outside the range as the "no grass" sentinel,
// so a stroke pointing below zero lands on bare ground.
bool CDetailManager::DetailLayers_PaintFMB(float world_x, float world_z, float value, float strength)
{
	u32 idx = WorldToFMBIdx(this, world_x, world_z);
	if (idx == 0xffffffff || idx >= fmb_field.size())
		return false;

	const float base_v = (idx < fmb_field_base.size()) ? fmb_field_base[idx] : 0.f;
	const float cur_delta = fmb_field[idx] - base_v;
	const float target = (value == FMB_CLEAR_GRASS) ? value : clampr(value, 0.f, 1.f);

	const float new_delta = cur_delta + ((target - base_v) - cur_delta) * strength;
	fmb_field[idx] = clampr(base_v + new_delta, -1.f, 1.f);
	return !!Upsert(user_fmb_mask, idx, new_delta);
}

// Remove one slot's override and restore the generated value, blending with strength.
bool CDetailManager::DetailLayers_EraseCluster(float world_x, float world_z, float strength)
{
	u32 idx = WorldToClusterIdx(this, world_x, world_z);
	if (idx == 0xffffffff || idx >= cluster_field.size())
		return false;

	u8 base_v = (idx < cluster_field_base.size()) ? cluster_field_base[idx] : u8(255);
	u8 cur = cluster_field[idx];
	u8 new_v = (u8)clampr((float)base_v + ((float)cur - (float)base_v) * (1.f - strength), 0.f, 255.f);
	if (new_v == base_v)
	{
		cluster_field[idx] = base_v;
		return Remove(user_clu_mask, idx);
	}
	cluster_field[idx] = new_v;
	return !!Upsert(user_clu_mask, idx, new_v);
}

// Upsert a slot override, blending toward `value` by strength.
// value == 255 => "no mix / native asset" (same as generated 255).
bool CDetailManager::DetailLayers_PaintCluster(float world_x, float world_z, u8 value, float strength)
{
	u32 idx = WorldToClusterIdx(this, world_x, world_z);
	if (idx == 0xffffffff || idx >= cluster_field.size())
		return false;

	u8 cur = cluster_field[idx];
	u8 new_v = (u8)clampr((float)cur + ((float)value - (float)cur) * strength, 0.f, 255.f);
	cluster_field[idx] = new_v;
	return !!Upsert(user_clu_mask, idx, new_v);
}

// Drop all overrides and bring the working fields back to their generated state.
void CDetailManager::DetailLayers_ClearUserMasks()
{
	user_fmb_mask.clear();
	user_clu_mask.clear();
	if (fmb_field.size() == fmb_field_base.size() && !fmb_field_base.empty())
		fmb_field = fmb_field_base;
	if (cluster_field.size() == cluster_field_base.size() && !cluster_field_base.empty())
		cluster_field = cluster_field_base;
}

#endif // !_EDITOR