

function get_file_name(file_path, remove_ext)
    local lastSlashIndex = file_path:match(".*()\\")
    local file_name = ""
	
    if lastSlashIndex then
        file_name = file_path:sub(lastSlashIndex + 1)
    else
        file_name = file_path
    end

    if remove_ext then
        local last_index = file_name:match(".*()%.")
        if last_index then
            return file_name:sub(1, last_index - 1)
        end
    end
    
    return file_name
end