function normal   (shader, t_base, t_second, t_detail)
      shader:begin  ("models_reflex_lens", "models_reflex_lens")
      : fog    (true)
      : zb    (true,false)
      : blend    (true,blend.srcalpha,blend.invsrcalpha)
      : aref      (true,0)
      : sorting      (2,true)
      : distort   (true)
    shader:dx10texture("s_base", t_base)
	shader:dx10texture("s_tonemap", "$user$tonemap")
	shader:dx10texture("s_env0", "$user$sky0")
	shader:dx10texture("s_env1", "$user$sky1")
    shader:dx10sampler("smp_rtlinear")
end
