function normal   (shader, t_base, t_second, t_detail)
      shader:begin  ("models_reflex_reticle", "models_reflex_reticle")
      : fog    (true)
      : zb    (true,false)
      : blend    (true,blend.srcalpha,blend.one)
      : aref      (true,0)
      : sorting      (2,true)
      : distort   (true)
    shader:dx10texture("s_base", t_base)
    shader:dx10sampler("smp_rtlinear")
end
