function normal(shader, t_base, t_second, t_detail)
  shader:begin("deffer_model", "base_lplanes_fft")
      : fog(true)
      : zb(true, false)
      : blend(true, blend.one, blend.one)
      : aref(true, 0)
      : sorting(3, true)
      : distort(true)
  shader:dx10texture("s_base", t_base)
  shader:dx10sampler("smp_base")
end