function init    (obj)
	xr_motivator.AddToMotivator(obj)
end

function actor_init    (npc)
	npc:bind_object(actor_binder(npc))
end

local game_difficulty_by_num = {
	[0] = "gd_novice",
	[1] = "gd_stalker",
	[2] = "gd_veteran",
	[3] = "gd_master"
}

local marshalLog = false

--[[
 IXR FFx0001 все коллбеки определять здесь (автоматическая регистрация - снатие событий)
 Отсутствие коллбека в движке не вызывает вылет
 Отсутсвие вызываемого метода в биндере не вызывает вылет
--]] 
local use_callback_logs = false -- логирование подписки и отписки для коллбеков
local all_callbacks = {
	["inventory_info"] 			= "info_callback",
	["on_item_take"] 			= "on_item_take",
	["on_item_drop"] 			= "on_item_drop",
	["trade_sell_buy_item"] 	= "on_trade",
	["task_state"] 				= "task_callback",
	["take_item_from_box"] 		= "take_item_from_box",
	["use_object"] 				= "use_inventory_item",
	["weapon_fired"]			= "on_weapon_fired", 
	["weapon_jammed"]			= "on_weapon_jammed",
	["weapon_zoom_in"]			= "on_weapon_zoom_in",
	["weapon_zoom_out"]			= "on_weapon_zoom_out",
	["weapon_magazine_empty"]	= "on_weapon_magazine_empty",
	["weapon_no_ammo"]			= "on_weapon_no_avialable_ammo", -- eWeaponNoAmmoAvailable
	["actor_before_death"] 		= "on_actor_before_death",
	["death"]					= "on_death",
	["key_press"]				= "on_key_press",
	["key_release"]				= "on_key_release",
	["key_hold"]				= "on_key_hold",
	["mouse_move"]				= "on_mouse_move",
	["mouse_wheel"]				= "on_mouse_wheel",
	["on_foot_step"]			= "actor_on_foot_step",
	["item_to_belt"]			= "actor_item_to_belt",
	["item_to_slot"]			= "actor_item_to_slot",
	["item_to_ruck"]			= "actor_item_to_ruck",
	["on_attach_vehicle"]		= "actor_on_attach_vehicle",
	["on_detach_vehicle"]		= "actor_on_detach_vehicle",
	["on_use_vehicle"]			= "actor_on_use_vehicle",
	["hit"]						= "actor_on_hit_callback",
	["on_actor_hit_fall"]		= "actor_on_hit_fall",
	["on_actor_jump_begin"]		= "actor_on_jump_begin",
	["on_actor_jump_end"]		= "actor_on_jump_end",
	
	["hud_animation_end"]		= "actor_on_hud_animation_end",
}

-- IXR FFx0001 Упрощенная система подписки и отписки от коллбеков
function manage_callbacks(_ref_binder, is_set)
	ixr_callback_binder.manage_callbacks(script_name(), all_callbacks, _ref_binder, is_set, use_callback_logs)
end

lasthealth  = 0
lasttime	= 0
post_process = 0
local weapon_hide = false
----------------------------------------------------------------------------------------------------------------------
class "actor_binder" (object_binder)
----------------------------------------------------------------------------------------------------------------------
function actor_binder:__init (obj) super(obj)
	self.bCheckStart = false
	self.weather_manager = level_weathers.WeatherManager()
	self.actor_detector = xr_detector.actor_detector()
	SendScriptCallback("actor_on_init", self) -- IX-Ray
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:net_spawn(data)
	printf("actor net spawn")		

	level.show_indicators()

	self.bCheckStart = true
	self.weapon_hide = false -- спрятано или нет оружие при разговоре.
	weapon_hide = false -- устанавливаем глобальный дефолтовый флаг.

	if object_binder.net_spawn(self,data) == false then
		return false
	end

	db.add_actor(self.object)
	
	if self.st.disable_input_time == nil then
		level.enable_input()
	end

	self.weather_manager:reset()
--	game_stats.initialize ()

	if(actor_stats.add_to_ranking~=nil)then
		actor_stats.add_to_ranking(self.object:id())
	end

	--' Загружаем настройки дропа
	death_manager.init_drop_settings()

	SendScriptCallback("on_game_load", binder)

	return true
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:net_destroy()
	SendScriptCallback("actor_on_net_destroy", self) -- IX-Ray
	
	if(actor_stats.remove_from_ranking~=nil)then
		actor_stats.remove_from_ranking(self.object:id())
	end
--	game_stats.shutdown ()
	db.del_actor(self.object)

    sr_light.clean_up ()

	manage_callbacks(self, false) -- IX-Ray UNSET CALLBACKS

	if sr_psy_antenna.psy_antenna then
		sr_psy_antenna.psy_antenna:destroy()
		sr_psy_antenna.psy_antenna = false
	end

	xr_sound.stop_all_sound_object()

	object_binder.net_destroy(self)
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:reinit()
	object_binder.reinit(self)
	
	local npc_id = self.object:id()

	db.storage[npc_id] = { }

	self.st = db.storage[npc_id]
	self.st.pstor = nil

	self.next_restrictors_update_time = -10000
	manage_callbacks(self, true) -- IX-Ray SET CALLBACKS
	SendScriptCallback("actor_on_reinit", self) -- IX-Ray
end

-- IX-Ray 
-- actor before death callback
-- IMPORTANT: if you wish to kill actor you need to call db.actor:kill(level.object_by_id(whoID), true) in actor_before_death callback, to ensure all objects are properly destroyed.
function actor_binder:on_actor_before_death(whoID)
	local flags = { ret_value = true }
	SendScriptCallback("actor_on_before_death", whoID, flags) -- IX-Ray
	
	if flags.ret_value then
		local killer = level.object_by_id(whoID) or db.actor
		db.actor:kill(killer, true)
	end
end
-- END IX-Ray 
----------------------------------------------------------------------------------------------------------------------
function actor_binder:take_item_from_box(box, item)
	local story_id = box:story_id()
	if story_id == nil then
		return
	end

	treasure_manager.take_item_from_box(box, story_id)
	SendScriptCallback("actor_on_item_take_from_box", box, item) -- IX-Ray
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:level_border_enter(npc, info_id)
	self.actor_detector:actor_enter()
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:level_border_exit(npc, info_id)
	self.actor_detector:actor_exit()
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:info_callback(npc, info_id)
	printf("*INFO*: npc='%s' id='%s'", npc:name(), info_id)
	--' Сюжет
	level_tasks.proceed(self.object)
	-- Отметки на карте
	level_tasks.process_info_portion(info_id)
	
	if not npc or not info_id then
		return
	end
	
	SendScriptCallback("actor_on_info_callback", npc, info_id) -- IX-Ray
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:on_trade (item, sell_bye, money)
    if sell_bye == true then
       game_stats.money_trade_update (money)
    else       
       game_stats.money_trade_update (-money) 
    end   
	
	if not item then
		return
	end
	
	SendScriptCallback("actor_on_trade", item, sell_bye, money) -- IX-Ray
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:article_callback(npc, group, name)
	--printf("article_callback [%s][%s]", group, name)
	if device().precache_frame >1 then return end
	
	if group == "Diary" then
		news_manager.send_encyclopedy("diary", group)
	else
		news_manager.send_encyclopedy("encyclopedy", group)
	end
	SendScriptCallback("actor_on_article", npc, group, name) -- IX-Ray
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:on_item_take (obj, m_last_dropped_owner_id)
	if obj and obj:id() then 
		SendScriptCallback("on_item_take", obj, db.actor ~= nil)
		
		if db.actor then
			local is_take_from_ground = (m_last_dropped_owner_id == 65535 or m_last_dropped_owner_id == db.actor:id())
			local before_transfer_parent_id = nil
			
			if not is_take_from_ground then
				before_transfer_parent_id = m_last_dropped_owner_id
			end
			
			SendScriptCallback("actor_on_item_take", obj, before_transfer_parent_id, is_take_from_ground)
			
			if is_take_from_ground then
				SendScriptCallback("actor_on_item_take_from_ground", obj)
			end
		end
	end

	printf("on_item_take [%s]", obj:name())
    level_tasks.proceed(self.object)
    --game_stats.update_take_item (obj, self.object)
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:on_item_drop (obj)
    level_tasks.proceed(self.object)
	if obj and obj:id() then 
		SendScriptCallback("on_item_drop", obj, db.actor ~= nil)
		
		if db.actor then 
			SendScriptCallback("actor_on_item_drop", obj)
		end
	end
end

----------------------------------------------------------------------------------------------------------------------
function actor_binder:use_inventory_item(obj)
	if obj and obj:id() then
		SendScriptCallback("actor_on_item_use", obj, obj:section())
	end
end

----------------------------------------------------------------------------------------------------------------------

function actor_binder:task_callback(_task, _objective, _state)
	task_manager.task_callback(_task:get_id(), _objective:get_idx(), _state)
	if _objective:get_idx() == 0 then
		if _state == task.fail then
			news_manager.send_task(db.actor, "fail", _task, _objective)
		elseif _state == task.completed then
			task_manager.reward_by_task(_task)
			news_manager.send_task(db.actor, "complete", _task, _objective)
		else
			news_manager.send_task(db.actor, "new", _task, _objective)
		end
	else
		if _task:get_objective(0):get_state() == task.in_progress then
			news_manager.send_task(db.actor, "update", _task, _objective)
		end
	end
end

----------------------------------------------------------------------------------------------------------------------
function actor_binder:actor_on_hit_fall(g_contact_health_lost, g_contact_power)
	SendScriptCallback("actor_on_hit_fall", self, g_contact_health_lost, g_contact_power) -- IX-Ray
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:actor_on_jump_begin(actor_position)
	SendScriptCallback("actor_on_jump_begin", self, actor_position) -- IX-Ray
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:actor_on_jump_end(g_contact_power, actor_position)
	SendScriptCallback("actor_on_jump_end", self, g_contact_power, actor_position) -- IX-Ray
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:actor_on_hit_callback(hitted_game_object, damage_number, direction_vector, who_game_object, bone_id_number, e_hit_type, impulse_number, p_last_hitting_weapon_game_object, health_lost_number)
	SendScriptCallback("actor_on_hit_callback", self, hitted_game_object, damage_number, direction_vector, who_game_object, bone_id_number, e_hit_type, impulse_number, p_last_hitting_weapon_game_object, health_lost_number) -- IX-Ray
end
----------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------------
function actor_binder:on_death(victim, who)
	SendScriptCallback("actor_on_death", victim, who)
end

----------------------------------------------------------------------------------------------------------------------
function actor_binder:actor_on_hud_animation_end(item, hud_section, m_current_motion_str, state_number, animation_slot_number)
	SendScriptCallback("actor_on_hud_animation_end", item, hud_section, m_current_motion_str, state_number, animation_slot_number)
end

----------------------------------------------------------------------------------------------------------------------
function actor_binder:actor_on_attach_vehicle(gobj)
	SendScriptCallback("actor_on_attach_vehicle", gobj)
end

----------------------------------------------------------------------------------------------------------------------
function actor_binder:actor_on_detach_vehicle(gobj)
	SendScriptCallback("actor_on_detach_vehicle", gobj)
end

----------------------------------------------------------------------------------------------------------------------
function actor_binder:actor_on_use_vehicle(gobj)
	SendScriptCallback("actor_on_use_vehicle", gobj)
end

----------------------------------------------------------------------------------------------------------------------
function actor_binder:actor_item_to_belt(gobj)
	SendScriptCallback("actor_item_to_belt", gobj)
end

----------------------------------------------------------------------------------------------------------------------
function actor_binder:actor_item_to_slot(gobj)
	SendScriptCallback("actor_item_to_slot", gobj)
end

----------------------------------------------------------------------------------------------------------------------
function actor_binder:actor_item_to_ruck(gobj)
	SendScriptCallback("actor_item_to_ruck", gobj)
end

----------------------------------------------------------------------------------------------------------------------
function actor_binder:actor_on_foot_step(gobj, power, b_play, b_on_ground, b_hud_view)
	SendScriptCallback("actor_on_foot_step", gobj, power, b_play, b_on_ground, b_hud_view)
	SendScriptCallback("actor_on_footstep", gobj, power, b_play, b_on_ground, b_hud_view)
end

----------------------------------------------------------------------------------------------------------------------
function actor_binder:on_key_press(dik_key)
	SendScriptCallback("on_key_press", dik_key)
end

----------------------------------------------------------------------------------------------------------------------
function actor_binder:on_key_release(dik_key)
	SendScriptCallback("on_key_release", dik_key)
end

----------------------------------------------------------------------------------------------------------------------
function actor_binder:on_key_hold(dik_key)
	SendScriptCallback("on_key_hold", dik_key)
end

----------------------------------------------------------------------------------------------------------------------
function actor_binder:on_mouse_move(dx, dy)
	SendScriptCallback("on_mouse_move", dx, dy)
end

----------------------------------------------------------------------------------------------------------------------
function actor_binder:on_mouse_wheel(direction)
	SendScriptCallback("on_mouse_wheel", direction)
end

----------------------------------------------------------------------------------------------------------------------
function actor_binder:on_weapon_magazine_empty(wpn, ammo_total)
	SendScriptCallback("actor_on_weapon_no_ammo", wpn, ammo_total)
end

----------------------------------------------------------------------------------------------------------------------
function actor_binder:on_weapon_zoom_in(obj, wpn)
	SendScriptCallback("actor_on_weapon_zoom_in", wpn)
end

----------------------------------------------------------------------------------------------------------------------
function actor_binder:on_weapon_zoom_out(obj, wpn)
	SendScriptCallback("actor_on_weapon_zoom_out", wpn)
end

----------------------------------------------------------------------------------------------------------------------
function actor_binder:on_weapon_fired(npc, wpn, iAmmoElapsed, m_ammoType)
	SendScriptCallback("actor_on_weapon_fired", npc, wpn, iAmmoElapsed, m_ammoType)
end

----------------------------------------------------------------------------------------------------------------------
function actor_binder:on_weapon_jammed(npc, wpn)
	SendScriptCallback("actor_on_weapon_jammed", wpn)
end

----------------------------------------------------------------------------------------------------------------------
function actor_binder:on_weapon_no_avialable_ammo(wpn, suitable_ammo_total)
	SendScriptCallback("actor_on_weapon_no_avialable_ammo", wpn, suitable_ammo_total)
	SendScriptCallback("actor_on_weapon_reload", wpn, suitable_ammo_total)
end

----------------------------------------------------------------------------------------------------------------------
function actor_binder:update(delta)
	object_binder.update(self, delta)

	-- DEBUG slowdown
--	slowdown.update()

	local time = time_global()
	
	game_stats.update (delta, self.object)

	-- апдейт погоды
	self.weather_manager:update()
	
	-- апдейт схемы детектора
	self.actor_detector:update()

	-- апдейт звуковой схемы актера
	xr_sound.update_actor()
	
	--' Проверка потери жизни
--[[
	if self.object.health - lasthealth > 0.001 or
	   self.object.health - lasthealth < -0.001 then
		printf("%f | %f", self.object.health, self.object.health - lasthealth, game.time() - lasttime)
		lasthealth = self.object.health
		lasttime = game.time()
	end
]]	
	-- Обновление отключения ввода с клавиатуры.
	if self.st.disable_input_time ~= nil and
	   game.get_game_time():diffSec(self.st.disable_input_time) >= self.st.disable_input_idle 
	then
		level.enable_input()
		self.st.disable_input_time = nil
	end
	-- Обновление сна с переносом чувака в указанную позицию
	if self.st.sleep_relocate_time ~= nil and
	   game.get_game_time():diffSec(self.st.sleep_relocate_time) >= self.st.sleep_relocate_idle 
	then
		self.object:set_actor_position(self.st.sleep_relocate_point)
		local dir = self.st.sleep_relocate_point:sub(self.st.sleep_relocate_look)
		self.object:set_actor_direction(dir:getH())
		self.st.sleep_relocate_time = nil
	end

	-- Апдейт прятание оружия игрока во время диалога
	if weapon_hide == true or self.object:is_talking() then
		if self.weapon_hide == false then
			self.object:hide_weapon()
			self.weapon_hide = true
		end
	else
		if self.weapon_hide == true then
			self.object:restore_weapon()
			self.weapon_hide = false
		end
	end	

	-- обновление рестрикторов, которые под логикой, срабатывает через интервалы времени
	if self.next_restrictors_update_time < time then
		bind_restrictor.actor_update(delta)

		self.next_restrictors_update_time = time + 200

		task_manager.actor_update()
	end

	-- обновление постпроцессов
	if post_process ~= 0 then
		if post_process:update () == true then
		   post_process = 0
		end
	end

	-- обновление пси-антенны
	if sr_psy_antenna.psy_antenna then
		sr_psy_antenna.psy_antenna:update(delta)
	end

	--' Вывод сообщения о большой радиации
	if self.object.radiation >= 0.7 then
		local hud = get_hud()
		local custom_static = hud:GetCustomStatic("cs_radiation_danger")
		if custom_static == nil then
			hud:AddCustomStatic("cs_radiation_danger", true)
			hud:GetCustomStatic("cs_radiation_danger"):wnd():SetTextST("st_radiation_danger")
		end
	else
		local hud = get_hud()
		local custom_static = hud:GetCustomStatic("cs_radiation_danger")
		if custom_static ~= nil then
			hud:RemoveCustomStatic("cs_radiation_danger")
		end
	end



 	if self.bCheckStart then
		printf("SET DEFAULT INFOS")		

		if not has_alife_info("storyline_actor_start") and
		   (level.name() == "l01_escape")
		then
			self.object:give_info_portion("storyline_actor_start")
			_G.g_start_avi = true
			printf("*AVI* RUN START AVI")			
		end

--		if not has_alife_info("encyclopedy") then
--			self.object:give_info_portion("encyclopedy")
--		end

		if not has_alife_info("global_dialogs") then
			self.object:give_info_portion("global_dialogs")
		end

		if not has_alife_info("level_changer_icons") then
			self.object:give_info_portion("level_changer_icons")
		end

		level_tasks.add_lchanger_location()

		self.bCheckStart = false		
	end		
	
	if self.first_update then
		self.first_update = false
		SendScriptCallback("actor_on_first_update", self, delta) -- IX-Ray
	end
		
	SendScriptCallback("update", delta) -- IX-Ray
	SendScriptCallback("actor_on_update", self, delta) -- IX-Ray
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:save(packet)
	if (utils.level_changing()) then
		SendScriptCallback("on_level_changing")
		SendScriptCallback("actor_on_level_changing")
   	end
	
	local save_treasure_manager = true
	
	printf("actor_binder:save(): self.object:name()='%s'", self.object:name())
	object_binder.save(self, packet)

	--' Сохраняем уровень сложности
	if save_treasure_manager == true then
		packet:w_u8(level.get_game_difficulty() + 128)
	else
		packet:w_u8(level.get_game_difficulty())
	end


	--' Сохраняем данные об отключенном вводе
	if self.st.disable_input_time == nil then
		packet:w_bool(false)
	else
		packet:w_bool(true)
		utils.w_CTime(packet, self.st.disable_input_time)
	end

	xr_logic.pstor_save_all(self.object, packet)
	self.weather_manager:save(packet)

	sr_psy_antenna.save( packet )
	
	if save_treasure_manager == true then
		treasure_manager.save(packet)      
	end                                  

	task_manager.save(packet)
	self.actor_detector:save(packet)
		
    SendScriptCallback("save", packet) -- IX-Ray
    SendScriptCallback("actor_on_save", packet) -- IX-Ray
end
----------------------------------------------------------------------------------------------------------------------
function actor_binder:load(reader)
	printf("actor_binder:load(): self.object:name()='%s'", self.object:name())
	object_binder.load(self, reader)
	printf("actor_binder:object_binder.load(): self.object:name()='%s'", self.object:name())

	--' Загружаем уровень сложности
	local game_difficulty = reader:r_u8()
	
	local load_treasure_manager = false      
	if game_difficulty >= 128 then           
		game_difficulty = game_difficulty - 128
		load_treasure_manager = true           
	end                                      

	
	get_console():execute("g_game_difficulty "..game_difficulty_by_num[game_difficulty])

	if reader:r_eof() then
		abort("SAVE FILE IS CORRUPT")
	end

	local stored_input_time = reader:r_u8()
	if stored_input_time == true then
		self.st.disable_input_time = utils.r_CTime(reader)
	end

	xr_logic.pstor_load_all(self.object, reader)
	self.weather_manager:load(reader)

	sr_psy_antenna.load(reader)
	
	if load_treasure_manager == true then
		treasure_manager.load(reader)      
	end                                  

	
	task_manager.load(reader)
	self.actor_detector:load(reader)	
    
    SendScriptCallback("load", reader) -- IX-Ray
    SendScriptCallback("actor_on_load", reader) -- IX-Ray
end
----------------------------------------------------------------------------------------------------------------------

--старт префетча звуков
--if string.find(command_line(), "-noprefetch") == nil then
--	sound_prefetch.prefetch_sounds()
--end


-- Weapon functions
function hide_weapon()
	weapon_hide = true
end
function restore_weapon()
	weapon_hide = false
end

-- this is test for section iteration
--[[
local function test_section_iteration(file_name, section_name)
	printf			("file    : %s",file_name)
	printf			("section : %s",section_name)
	
	local			file = ini_file(file_name)
	local			n = file:line_count(section_name)
	printf			("lines   : %d",n)
	
	local			id, value = "", "", result
	for i=0,n-1 do
		result, id, value	= file:r_line(section_name,i,"","")
		printf		("line %d : %s = %s",i,id,value)
	end
end

test_section_iteration("system.ltx","space_restrictor")
]]--
