class "se_actor"	(cse_alife_creature_actor)
--------------------
function se_actor:__init (section) super (section)
end

function se_actor:on_register()
	cse_alife_creature_actor.on_register(self)

	SendScriptCallback("se_actor_on_register", self)
	
	SendScriptCallback("server_entity_on_register", self, "se_actor")
	
end

function se_actor:on_unregister()
	SendScriptCallback("se_actor_on_unregister", self)
	SendScriptCallback("server_entity_on_unregister", self, "se_actor")
	cse_alife_creature_actor.on_unregister(self)
end

--------------------
function se_actor:STATE_Write(packet)
	SendScriptCallback("se_actor_on_STATE_Write", self, packet)
	
	cse_alife_creature_actor.STATE_Write(self, packet)
end
--------------------
function se_actor:STATE_Read(packet, size)
	SendScriptCallback("se_actor_on_STATE_Read", self, packet, size)
	
	cse_alife_creature_actor.STATE_Read(self, packet, size)
end