-- File:		UI_NUMPAD.SCRIPT
-- Description:		Numpad for password input
-- Created:		23.02.2005
-- Author:		Serge Vynnychenko
--
-- Copyright 2004 GSC Game World


function main()
	super_dlg = ui_numpad.numpad()
	level.start_stop_menu(super_dlg,true)
end

class "numpad" (CUIScriptWnd)

function numpad:__init(owner) super()
	self.owner = owner
	self:InitControls()
	self:InitCallBacks()

	self.focusIndex = {x=1, y=1}
	self.curBtn = self.focusList[1][1]
	self.curBtn:SetHighlighted(true)

	action_repeaters():Register(self, key_bindings.kUI_UP, 0, 0)
	action_repeaters():Register(self, key_bindings.kUI_DOWN, 0, 0)
	action_repeaters():Register(self, key_bindings.kUI_LEFT, 0, 0)
	action_repeaters():Register(self, key_bindings.kUI_RIGHT, 0, 0)
end

function numpad:__finalize()

end

function numpad:InitControls()

	self:Init(342,199,339,369)			  
    local xml = CScriptXmlInit()
    xml:ParseFile("ui_numpad_wnd.xml")
	
	local t;
     
	xml:InitStatic("background", self)
	t = xml:InitStatic("edit_box", self)
	t:SetWindowName("edit_window")
	self.focusList = {}
	local btn1, btn2, btn3

	btn1 = xml:Init3tButton("btn_7", self)
	self:Register(btn1,"btn_7")

	btn2 = xml:Init3tButton("btn_8", self)
	self:Register(btn2,"btn_8")

	btn3 = xml:Init3tButton("btn_9", self)
	self:Register(btn3,"btn_9")

	-- 1st stroke
	table.insert(self.focusList, { btn1, btn2, btn3 })

	btn1 = xml:Init3tButton("btn_4", self)
	self:Register(btn1,"btn_4")

	btn2 = xml:Init3tButton("btn_5", self)
	self:Register(btn2,"btn_5")

	btn3 = xml:Init3tButton("btn_6", self)
	self:Register(btn3,"btn_6")

	-- 2nd stroke
	table.insert(self.focusList, { btn1, btn2, btn3 })

	btn1 = xml:Init3tButton("btn_1", self)
	self:Register(btn1,"btn_1")

	btn2 = xml:Init3tButton("btn_2", self)
	self:Register(btn2,"btn_2")

	btn3 = xml:Init3tButton("btn_3", self)
	self:Register(btn3,"btn_3")

	-- 3rd stroke
	table.insert(self.focusList, { btn1, btn2, btn3 })

	btn1 = xml:Init3tButton("btn_0", self)
	self:Register(btn1,"btn_0")

	btn2 = xml:Init3tButton("btn_c", self)
	self:Register(btn2,"btn_c")

	btn3 = xml:Init3tButton("btn_backspase", self)
	self:Register(btn3,"btn_backspase")

	-- 4th stroke
	table.insert(self.focusList, { btn1, btn2, btn3 })
	--focusStroke = {}

	btn1 = xml:Init3tButton("btn_enter", self)
	self:Register(btn1,"btn_enter")

	btn2 = xml:Init3tButton("btn_cancel", self)
	self:Register(btn2,"btn_cancel")

	-- 5th stroke
	table.insert(self.focusList, { btn1, btn2 })
		
	-- Gamepad legend
	if xml:NodeExist("gamepad_legend", 0) then
		self.gamepad_legend = xml:InitGamepadLegend("gamepad_legend", self)
	end
end


function numpad:InitCallBacks()
	-- new game
	self:AddCallback("btn_enter",	ui_events.BUTTON_CLICKED,	self.OnButton_OK_clicked,		self)
	self:AddCallback("btn_cancel",	ui_events.BUTTON_CLICKED,	self.OnButton_CANCEL_clicked,	self)
	
	self:AddCallback("btn_0",		ui_events.BUTTON_CLICKED,	self.OnButton_0_clicked,		self)
	self:AddCallback("btn_1",		ui_events.BUTTON_CLICKED,	self.OnButton_1_clicked,		self)
	self:AddCallback("btn_2",		ui_events.BUTTON_CLICKED,	self.OnButton_2_clicked,		self)
	self:AddCallback("btn_3",		ui_events.BUTTON_CLICKED,	self.OnButton_3_clicked,		self)
	self:AddCallback("btn_4",		ui_events.BUTTON_CLICKED,	self.OnButton_4_clicked,		self)
	self:AddCallback("btn_5",		ui_events.BUTTON_CLICKED,	self.OnButton_5_clicked,		self)
	self:AddCallback("btn_6",		ui_events.BUTTON_CLICKED,	self.OnButton_6_clicked,		self)
	self:AddCallback("btn_7",		ui_events.BUTTON_CLICKED,	self.OnButton_7_clicked,		self)
	self:AddCallback("btn_8",		ui_events.BUTTON_CLICKED,	self.OnButton_8_clicked,		self)
	self:AddCallback("btn_9",		ui_events.BUTTON_CLICKED,	self.OnButton_9_clicked,		self)
	
	self:AddCallback("btn_c",			ui_events.BUTTON_CLICKED,	self.OnButton_c_clicked,			self)
	self:AddCallback("btn_backspase",	ui_events.BUTTON_CLICKED,	self.OnButton_backspace_clicked,	self)
end

function numpad:AddNumber(number)
	local edit_window = self:GetStatic("edit_window")
	local text = edit_window:GetText()
	
	if text == nil then
		text = "" .. number
	else
		if (string.len(text) > 12) then
			return
		end
		
		text = text .. number
	end
	
	edit_window:SetText(text)
end


function numpad:OnButton_backspace_clicked()
	local edit_window = self:GetStatic("edit_window")
	local text = edit_window:GetText()
	
	if text == nil then
		return
	end
	
	local b = 1
	local e = string.len(text) - 1
	
	text = string.sub(text, b, e)
	
	edit_window:SetText(text)
end

function numpad:OnButton_c_clicked()
	local edit_window = self:GetStatic("edit_window")	
	edit_window:SetText("")
end

function numpad:OnButton_0_clicked()
	self:AddNumber(0)
end

function numpad:OnButton_1_clicked()
	self:AddNumber(1)
end

function numpad:OnButton_2_clicked()
	self:AddNumber(2)
end

function numpad:OnButton_3_clicked()
	self:AddNumber(3)
end

function numpad:OnButton_4_clicked()
	self:AddNumber(4)
end

function numpad:OnButton_5_clicked()
	self:AddNumber(5)
end

function numpad:OnButton_6_clicked()
	self:AddNumber(6)
end

function numpad:OnButton_7_clicked()
	self:AddNumber(7)
end

function numpad:OnButton_8_clicked()
	self:AddNumber(8)
end

function numpad:OnButton_9_clicked()
	self:AddNumber(9)
end

function numpad:OnButton_CANCEL_clicked()
	self.owner:OnNumberReceive("")
	self:GetHolder():start_stop_menu(self, true)
end

function numpad:OnButton_OK_clicked()
	self:GetHolder():start_stop_menu(self, true)
	local edit_window = self:GetStatic("edit_window")
	local text = edit_window:GetText()
	self.owner:OnNumberReceive(text)
end

function numpad:TryOffsetSelector(xx, yy, canLoop)

	newx = self.focusIndex.x
	newy = self.focusIndex.y
		
	-- only allow strict v/h motion
	if xx == 0 then
		newy = newy + yy
		if newy < 1 then
			if canLoop then
				newy = #self.focusList
			else
				return false
			end
		elseif newy > #self.focusList then
			if canLoop then
				newy = 1
			else
				return false
			end
		end	
	elseif yy == 0 then
		newx = newx + xx
		if newx > #self.focusList[self.focusIndex.y] then
			if canLoop then
				newx = 1
			else
				return false
			end
		elseif newx < 1 then
			if canLoop then
				newx = #self.focusList[self.focusIndex.y]
			else
				return false
			end
		end	
	end
	
	self.curBtn:SetHighlighted(false)
	self.focusIndex.x = newx 
	self.focusIndex.y = newy
	self.curBtn = self.focusList[self.focusIndex.y][self.focusIndex.x]
	
	-- hack for missing btn in the last row
	if self.curBtn == nil then
		self.focusIndex.x = 2
		self.curBtn = self.focusList[self.focusIndex.y][self.focusIndex.x]
	end
	
	self.curBtn:SetHighlighted(true)
end

function numpad:OnKeyboard(dik, keyboard_action)  --virtual function
	CUIScriptWnd.OnKeyboard(self,dik,keyboard_action)
	
	if keyboard_action == ui_events.WINDOW_KEY_PRESSED then
		if dik == DIK_keys.DIK_ESCAPE then
			self:GetHolder():start_stop_menu(self,true)
		end
		
		if dik == DIK_keys.DIK_0 or dik == DIK_keys.DIK_NUMPAD0 then
			self:AddNumber(0)
		elseif dik == DIK_keys.DIK_1 or dik == DIK_keys.DIK_NUMPAD1 then
			self:AddNumber(1)
		elseif dik == DIK_keys.DIK_2 or dik == DIK_keys.DIK_NUMPAD2 then
			self:AddNumber(2)
		elseif dik == DIK_keys.DIK_3 or dik == DIK_keys.DIK_NUMPAD3 then
			self:AddNumber(3)
		elseif dik == DIK_keys.DIK_4 or dik == DIK_keys.DIK_NUMPAD4 then
			self:AddNumber(4)
		elseif dik == DIK_keys.DIK_5 or dik == DIK_keys.DIK_NUMPAD5 then
			self:AddNumber(5)
		elseif dik == DIK_keys.DIK_6 or dik == DIK_keys.DIK_NUMPAD6 then
			self:AddNumber(6)
		elseif dik == DIK_keys.DIK_7 or dik == DIK_keys.DIK_NUMPAD7 then
			self:AddNumber(7)
		elseif dik == DIK_keys.DIK_8 or dik == DIK_keys.DIK_NUMPAD8 then
			self:AddNumber(8)
		elseif dik == DIK_keys.DIK_9 or dik == DIK_keys.DIK_NUMPAD9 then
			self:AddNumber(9)
		elseif dik == DIK_keys.DIK_BACK then
			self:OnButton_backspace_clicked()
		elseif dik == DIK_keys.DIK_RETURN or dik == DIK_keys.DIK_NUMPADENTER then
			self:OnButton_OK_clicked()
		elseif dik == DIK_keys.DIK_DELETE or dik == DIK_keys.DIK_NUMPADCOMMA then
			self:OnButton_c_clicked()
		end
	end
	
	return true
end


function numpad:OnGamepadKey(key, gamepad_action)  --virtual function
	if gamepad_action == ui_events.WINDOW_KEY_PRESSED then
		local bindUI = dik_to_bind(key, action_groups.agUIGeneral)
		if bindUI == key_bindings.kUI_ACCEPT then
			self.curBtn:OnClick()
			return true
		elseif bindUI == key_bindings.kUI_BACK then
			-- todo: play sound
			self:OnButton_CANCEL_clicked()
			return true
		elseif bindUI == key_bindings.kUI_DOWN then
			if not any_binded_key_for_action_pressed_c(key_bindings.kUI_UP) then
				self:TryOffsetSelector(0,1,true)
			end
			action_repeaters():SetActionStarted(self, key_bindings.kUI_DOWN)
			return true
		elseif bindUI == key_bindings.kUI_UP then
			if not any_binded_key_for_action_pressed_c(key_bindings.kUI_DOWN) then
				self:TryOffsetSelector(0,-1,true)
			end
			action_repeaters():SetActionStarted(self, key_bindings.kUI_UP)
			return true
		elseif bindUI == key_bindings.kUI_LEFT then
			if not any_binded_key_for_action_pressed_c(key_bindings.kUI_RIGHT) then
				self:TryOffsetSelector(-1,0,true)
			end
			action_repeaters():SetActionStarted(self, key_bindings.kUI_LEFT)
			return true
		elseif bindUI == key_bindings.kUI_RIGHT then	
			if not any_binded_key_for_action_pressed_c(key_bindings.kUI_LEFT) then
				self:TryOffsetSelector(1,0,true)
			end
			action_repeaters():SetActionStarted(self, key_bindings.kUI_RIGHT) 
			return true
		end
	end

	CUIScriptWnd.OnGamepadKey(self,key,gamepad_action)
	return true
end

function numpad:OnGamepadKeyHold(key)  --virtual function
	local bindUI = dik_to_bind(key, action_groups.agUIGeneral)		
	if bindUI == key_bindings.kUI_DOWN then
		if action_repeaters():CanRepeatActionNow(self, key_bindings.kUI_DOWN) 
		and not any_binded_key_for_action_pressed_c(key_bindings.kUI_UP) then
			self:TryOffsetSelector(0,1,false)
		end
		return true
	
	elseif bindUI == key_bindings.kUI_UP then
		if action_repeaters():CanRepeatActionNow(self, key_bindings.kUI_UP) 
		and not any_binded_key_for_action_pressed_c(key_bindings.kUI_DOWN) then
			self:TryOffsetSelector(0,-1,false)
		end
		return true
	
	elseif bindUI == key_bindings.kUI_LEFT then
		if action_repeaters():CanRepeatActionNow(self, key_bindings.kUI_LEFT) 
		and not any_binded_key_for_action_pressed_c(key_bindings.kUI_RIGHT) then
			self:TryOffsetSelector(-1,0,false)
		end
		return true
	
	elseif bindUI == key_bindings.kUI_RIGHT then	
		if action_repeaters():CanRepeatActionNow(self, key_bindings.kUI_RIGHT) 
		and not any_binded_key_for_action_pressed_c(key_bindings.kUI_LEFT) then
			self:TryOffsetSelector(1,0,false)
		end
		return true
	end

	return CUIScriptWnd.OnGamepadKeyHold(self, key)
end

function numpad:Update()
	CUIScriptWnd.Update(self)
	if self.controller_mode ~= main_menu.in_controller_mode() then
		self.curBtn:SetHighlighted(main_menu.in_controller_mode())
	end
	
	self.controller_mode = main_menu.in_controller_mode()
end
