#include "../../xrCore/xrCore.h"
#include "GameLevelsRegistry.h"

constexpr const char* GameConfigName = "game.ltx";
constexpr const char* AutoRegFileName = "mod_game_levels_autoreg.ltx";
constexpr const char* AutoRegSectionPrefix = "autoreg_";
constexpr float AutoRegOffsetStep = 5000.f;

struct RegisteredLevel
{
	xr_string Section;
	xr_string Name;
	Fvector Offset;
	u8 Id = 0;
};

xr_unique_ptr<CInifile> OpenGameConfig()
{
	string_path Path;
	FS.update_path(Path, "$game_config$", GameConfigName);
	return xr_make_unique<CInifile>(Path);
}

xr_vector<RegisteredLevel> ReadRegistered(const CInifile& Ini)
{
	xr_vector<RegisteredLevel> Result;
	if (!Ini.section_exist("levels"))
	{
		return Result;
	}

	const char* Line = nullptr;
	const char* Value = nullptr;
	for (int It = 0; Ini.r_line("levels", It, &Line, &Value); ++It)
	{
		xr_string Section = Line;
		xr_strlwr(Section);

		if (!Ini.section_exist(Section.c_str()) || !Ini.line_exist(Section.c_str(), "name") || !Ini.line_exist(Section.c_str(), "id") || !Ini.line_exist(Section.c_str(), "offset"))
		{
			continue;
		}

		RegisteredLevel& Level = Result.emplace_back();
		Level.Section = Section;
		Level.Name = Ini.r_string(Section.c_str(), "name");
		xr_strlwr(Level.Name);

		Level.Offset = Ini.r_fvector3(Section.c_str(), "offset");
		Level.Id = Ini.r_u8(Section.c_str(), "id");
	}

	return Result;
}

bool IsRegistered(const xr_vector<RegisteredLevel>& Registered, const xr_string& Name)
{
	xr_string LowerName = Name;
	xr_strlwr(LowerName);

	return std::any_of(Registered.begin(), Registered.end(), [&LowerName](const RegisteredLevel& Level)
					   { return Level.Name == LowerName; });
}

bool IsAutoRegistered(const RegisteredLevel& Level)
{
	return Level.Section.starts_with(AutoRegSectionPrefix);
}

void WriteAutoRegFile(const xr_vector<RegisteredLevel>& Levels)
{
	IWriter* Writer = FS.w_open("$game_config$", AutoRegFileName);
	R_ASSERT3(Writer, "Can't write", AutoRegFileName);

	Writer->w_string("; Generated by xrLevelBuilder: levels missing from game_levels.ltx.");
	Writer->w_string("; Move them to game_levels.ltx to set proper ids and offsets.");
	Writer->w_string("![levels]");
	for (const RegisteredLevel& Level : Levels)
	{
		Writer->w_string(("  " + Level.Section).c_str());
	}

	string512 Line;
	for (const RegisteredLevel& Level : Levels)
	{
		Writer->w_string("");
		xr_sprintf(Line, "[%s]", Level.Section.c_str());
		Writer->w_string(Line);
		xr_sprintf(Line, "name = %s", Level.Name.c_str());
		Writer->w_string(Line);
		xr_sprintf(Line, "caption = \"%s\"", Level.Name.c_str());
		Writer->w_string(Line);
		xr_sprintf(Line, "offset = %.1f, %.1f, %.1f", Level.Offset.x, Level.Offset.y, Level.Offset.z);
		Writer->w_string(Line);
		Writer->w_string("weathers = [default]");
		xr_sprintf(Line, "id = %u", u32(Level.Id));
		Writer->w_string(Line);
	}

	FS.w_close(Writer, true);
}

xr_vector<xr_string> GameLevelsRegistry::FindUnregistered(const xr_vector<xr_string>& Levels)
{
	const xr_unique_ptr<CInifile> Ini = OpenGameConfig();
	const xr_vector<RegisteredLevel> Registered = ReadRegistered(*Ini);

	xr_vector<xr_string> Result;
	for (const xr_string& Name : Levels)
	{
		if (!IsRegistered(Registered, Name))
		{
			Result.push_back(Name);
		}
	}

	return Result;
}

bool GameLevelsRegistry::Register(const xr_vector<xr_string>& Levels)
{
	xr_vector<RegisteredLevel> Registered;
	{
		const xr_unique_ptr<CInifile> Ini = OpenGameConfig();
		Registered = ReadRegistered(*Ini);
	}

	std::array<bool, 256> UsedIds = {};
	float MaxOffsetX = 0.f;
	for (const RegisteredLevel& Level : Registered)
	{
		UsedIds[Level.Id] = true;
		MaxOffsetX = std::max(MaxOffsetX, Level.Offset.x);
	}

	xr_vector<RegisteredLevel> AutoRegistered;
	for (const RegisteredLevel& Level : Registered)
	{
		if (!IsAutoRegistered(Level))
		{
			continue;
		}

		const bool IsManual = std::any_of(Registered.begin(), Registered.end(), [&Level](const RegisteredLevel& Other)
										  { return !IsAutoRegistered(Other) && Other.Name == Level.Name; });
		if (!IsManual)
		{
			AutoRegistered.push_back(Level);
		}
	}

	bool Success = true;
	for (const xr_string& Name : Levels)
	{
		if (IsRegistered(Registered, Name))
		{
			continue;
		}

		auto FreeId = std::find(UsedIds.begin(), UsedIds.end(), false);
		if (FreeId == UsedIds.end())
		{
			Msg("! [game_levels] No free level id for %s", Name.c_str());
			Success = false;
			continue;
		}
		*FreeId = true;
		MaxOffsetX += AutoRegOffsetStep;

		RegisteredLevel& Level = AutoRegistered.emplace_back();
		Level.Name = Name;
		xr_strlwr(Level.Name);

		Level.Section = AutoRegSectionPrefix + Level.Name;
		Level.Offset.set(MaxOffsetX, 0.f, 0.f);
		Level.Id = u8(FreeId - UsedIds.begin());
		Registered.push_back(Level);

		Msg("* [game_levels] Registered %s: id %u, section %s", Level.Name.c_str(), u32(Level.Id), Level.Section.c_str());
	}

	WriteAutoRegFile(AutoRegistered);
	return Success;
}
