
ADD_BUTTON_IMAGE_S(Undo)
ADD_BUTTON_IMAGE_S(Redo)
ADD_BUTTON_IMAGE_D(CForm)
ADD_BUTTON_IMAGE_D(AIMap)
ADD_BUTTON_IMAGE_D(GGraph)
ADD_BUTTON_IMAGE_D(SRestrictor)

/*
ADD_BUTTON_IMAGE_P(Select)
ADD_BUTTON_IMAGE_P(Add)

ADD_BUTTON_IMAGE_D(CsLocal)
ADD_BUTTON_IMAGE_D(NuScale)
ADD_BUTTON_IMAGE_D(GSnap)
ADD_BUTTON_IMAGE_D(OSnap)
ADD_BUTTON_IMAGE_D(MoveToSnap)
ADD_BUTTON_IMAGE_D(NSnap)
ADD_BUTTON_IMAGE_D(VSnap)
ADD_BUTTON_IMAGE_D(ASnap)
ADD_BUTTON_IMAGE_D(MSnap)

ADD_BUTTON_IMAGE_S(Zoom)
ADD_BUTTON_IMAGE_S(ZoomSel)

ADD_BUTTON_IMAGE_T1(View,F)
ADD_BUTTON_IMAGE_T1_1(View, B1,B)
ADD_BUTTON_IMAGE_T1(View, L)
ADD_BUTTON_IMAGE_T1(View, R)
ADD_BUTTON_IMAGE_T1(View, T)
ADD_BUTTON_IMAGE_T1_1(View, B2,B)
ADD_BUTTON_IMAGE_T1(View, X)

ADD_BUTTON_IMAGE_T2(Camera, P)
ADD_BUTTON_IMAGE_T2(Camera, A)
ADD_BUTTON_IMAGE_T2(Camera, F)*/


#undef ADD_BUTTON_IMAGE_D
#undef ADD_BUTTON_IMAGE_S