#pragma once

// Project-owned legacy numeric identifiers.
// Historical DirectX 9 encodings still consumed by the D3D11 state translator, blender/state recording,
// vertex declarations and stored asset formats. Values must not change. No DX9 SDK dependency.
// Requires the Windows base types (BYTE, WORD, DWORD, HRESULT); include after windows.h.

typedef enum _D3DBLEND {
	D3DBLEND_ZERO = 1,
	D3DBLEND_ONE = 2,
	D3DBLEND_SRCCOLOR = 3,
	D3DBLEND_INVSRCCOLOR = 4,
	D3DBLEND_SRCALPHA = 5,
	D3DBLEND_INVSRCALPHA = 6,
	D3DBLEND_DESTALPHA = 7,
	D3DBLEND_INVDESTALPHA = 8,
	D3DBLEND_DESTCOLOR = 9,
	D3DBLEND_INVDESTCOLOR = 0xA,
	D3DBLEND_SRCALPHASAT = 0xB,
	D3DBLEND_BLENDFACTOR = 0xE,
	D3DBLEND_INVBLENDFACTOR = 0xF,
	D3DBLEND_SRCCOLOR2 = 0x10,
	D3DBLEND_INVSRCCOLOR2 = 0x11,
} D3DBLEND;

typedef enum _D3DBLENDOP {
	D3DBLENDOP_ADD = 1,
	D3DBLENDOP_SUBTRACT = 2,
	D3DBLENDOP_REVSUBTRACT = 3,
	D3DBLENDOP_MIN = 4,
	D3DBLENDOP_MAX = 5,
} D3DBLENDOP;

typedef enum _D3DCMPFUNC {
	D3DCMP_NEVER = 1,
	D3DCMP_LESS = 2,
	D3DCMP_EQUAL = 3,
	D3DCMP_LESSEQUAL = 4,
	D3DCMP_GREATER = 5,
	D3DCMP_NOTEQUAL = 6,
	D3DCMP_GREATEREQUAL = 7,
	D3DCMP_ALWAYS = 8,
} D3DCMPFUNC;

typedef enum _D3DCULL {
	D3DCULL_NONE = 1,
	D3DCULL_CW = 2,
	D3DCULL_CCW = 3,
} D3DCULL;

typedef enum _D3DDECLMETHOD {
	D3DDECLMETHOD_DEFAULT = 0,
	D3DDECLMETHOD_UV = 4,
} D3DDECLMETHOD;

typedef enum _D3DDECLTYPE {
	D3DDECLTYPE_FLOAT1 = 0,
	D3DDECLTYPE_FLOAT2 = 1,
	D3DDECLTYPE_FLOAT3 = 2,
	D3DDECLTYPE_FLOAT4 = 3,
	D3DDECLTYPE_D3DCOLOR = 4,
	D3DDECLTYPE_UBYTE4 = 5,
	D3DDECLTYPE_SHORT2 = 6,
	D3DDECLTYPE_SHORT4 = 7,
	D3DDECLTYPE_UBYTE4N = 8,
	D3DDECLTYPE_SHORT2N = 9,
	D3DDECLTYPE_SHORT4N = 0xA,
	D3DDECLTYPE_USHORT2N = 0xB,
	D3DDECLTYPE_USHORT4N = 0xC,
	D3DDECLTYPE_UDEC3 = 0xD,
	D3DDECLTYPE_DEC3N = 0xE,
	D3DDECLTYPE_FLOAT16_2 = 0xF,
	D3DDECLTYPE_FLOAT16_4 = 0x10,
	D3DDECLTYPE_UNUSED = 0x11,
} D3DDECLTYPE;

typedef enum _D3DDECLUSAGE {
	D3DDECLUSAGE_POSITION = 0,
	D3DDECLUSAGE_BLENDWEIGHT = 1,
	D3DDECLUSAGE_BLENDINDICES = 2,
	D3DDECLUSAGE_NORMAL = 3,
	D3DDECLUSAGE_PSIZE = 4,
	D3DDECLUSAGE_TEXCOORD = 5,
	D3DDECLUSAGE_TANGENT = 6,
	D3DDECLUSAGE_BINORMAL = 7,
	D3DDECLUSAGE_POSITIONT = 9,
	D3DDECLUSAGE_COLOR = 0xA,
} D3DDECLUSAGE;

typedef enum _D3DFILLMODE {
	D3DFILL_POINT = 1,
	D3DFILL_WIREFRAME = 2,
	D3DFILL_SOLID = 3,
} D3DFILLMODE;

typedef enum _D3DLIGHTTYPE {
	D3DLIGHT_POINT = 1,
	D3DLIGHT_SPOT = 2,
	D3DLIGHT_DIRECTIONAL = 3,
} D3DLIGHTTYPE;

typedef enum _D3DMATERIALCOLORSOURCE {
	D3DMCS_MATERIAL = 0,
	D3DMCS_COLOR1 = 1,
} D3DMATERIALCOLORSOURCE;

typedef enum _D3DPOOL {
	D3DPOOL_DEFAULT = 0,
	D3DPOOL_MANAGED = 1,
	D3DPOOL_SYSTEMMEM = 2,
	D3DPOOL_SCRATCH = 3,
} D3DPOOL;

typedef enum _D3DQUERYTYPE {
	D3DQUERYTYPE_OCCLUSION = 9,
} D3DQUERYTYPE;

typedef enum _D3DRENDERSTATETYPE {
	D3DRS_ZENABLE = 7,
	D3DRS_FILLMODE = 8,
	D3DRS_SHADEMODE = 9,
	D3DRS_ZWRITEENABLE = 0xE,
	D3DRS_ALPHATESTENABLE = 0xF,
	D3DRS_LASTPIXEL = 0x10,
	D3DRS_SRCBLEND = 0x13,
	D3DRS_DESTBLEND = 0x14,
	D3DRS_CULLMODE = 0x16,
	D3DRS_ZFUNC = 0x17,
	D3DRS_ALPHAREF = 0x18,
	D3DRS_ALPHAFUNC = 0x19,
	D3DRS_DITHERENABLE = 0x1A,
	D3DRS_ALPHABLENDENABLE = 0x1B,
	D3DRS_FOGENABLE = 0x1C,
	D3DRS_SPECULARENABLE = 0x1D,
	D3DRS_FOGCOLOR = 0x22,
	D3DRS_FOGTABLEMODE = 0x23,
	D3DRS_FOGSTART = 0x24,
	D3DRS_FOGEND = 0x25,
	D3DRS_FOGDENSITY = 0x26,
	D3DRS_RANGEFOGENABLE = 0x30,
	D3DRS_STENCILENABLE = 0x34,
	D3DRS_STENCILFAIL = 0x35,
	D3DRS_STENCILZFAIL = 0x36,
	D3DRS_STENCILPASS = 0x37,
	D3DRS_STENCILFUNC = 0x38,
	D3DRS_STENCILREF = 0x39,
	D3DRS_STENCILMASK = 0x3A,
	D3DRS_STENCILWRITEMASK = 0x3B,
	D3DRS_TEXTUREFACTOR = 0x3C,
	D3DRS_WRAP0 = 0x80,
	D3DRS_WRAP1 = 0x81,
	D3DRS_WRAP2 = 0x82,
	D3DRS_WRAP3 = 0x83,
	D3DRS_WRAP4 = 0x84,
	D3DRS_WRAP5 = 0x85,
	D3DRS_WRAP6 = 0x86,
	D3DRS_WRAP7 = 0x87,
	D3DRS_CLIPPING = 0x88,
	D3DRS_LIGHTING = 0x89,
	D3DRS_AMBIENT = 0x8B,
	D3DRS_FOGVERTEXMODE = 0x8C,
	D3DRS_COLORVERTEX = 0x8D,
	D3DRS_LOCALVIEWER = 0x8E,
	D3DRS_NORMALIZENORMALS = 0x8F,
	D3DRS_DIFFUSEMATERIALSOURCE = 0x91,
	D3DRS_SPECULARMATERIALSOURCE = 0x92,
	D3DRS_AMBIENTMATERIALSOURCE = 0x93,
	D3DRS_EMISSIVEMATERIALSOURCE = 0x94,
	D3DRS_VERTEXBLEND = 0x97,
	D3DRS_CLIPPLANEENABLE = 0x98,
	D3DRS_POINTSIZE = 0x9A,
	D3DRS_POINTSIZE_MIN = 0x9B,
	D3DRS_POINTSPRITEENABLE = 0x9C,
	D3DRS_POINTSCALEENABLE = 0x9D,
	D3DRS_POINTSCALE_A = 0x9E,
	D3DRS_POINTSCALE_B = 0x9F,
	D3DRS_POINTSCALE_C = 0xA0,
	D3DRS_MULTISAMPLEANTIALIAS = 0xA1,
	D3DRS_MULTISAMPLEMASK = 0xA2,
	D3DRS_PATCHEDGESTYLE = 0xA3,
	D3DRS_DEBUGMONITORTOKEN = 0xA5,
	D3DRS_POINTSIZE_MAX = 0xA6,
	D3DRS_INDEXEDVERTEXBLENDENABLE = 0xA7,
	D3DRS_COLORWRITEENABLE = 0xA8,
	D3DRS_TWEENFACTOR = 0xAA,
	D3DRS_BLENDOP = 0xAB,
	D3DRS_POSITIONDEGREE = 0xAC,
	D3DRS_NORMALDEGREE = 0xAD,
	D3DRS_SCISSORTESTENABLE = 0xAE,
	D3DRS_SLOPESCALEDEPTHBIAS = 0xAF,
	D3DRS_ANTIALIASEDLINEENABLE = 0xB0,
	D3DRS_MINTESSELLATIONLEVEL = 0xB2,
	D3DRS_MAXTESSELLATIONLEVEL = 0xB3,
	D3DRS_ADAPTIVETESS_X = 0xB4,
	D3DRS_ADAPTIVETESS_Y = 0xB5,
	D3DRS_ADAPTIVETESS_Z = 0xB6,
	D3DRS_ADAPTIVETESS_W = 0xB7,
	D3DRS_ENABLEADAPTIVETESSELLATION = 0xB8,
	D3DRS_TWOSIDEDSTENCILMODE = 0xB9,
	D3DRS_CCW_STENCILFAIL = 0xBA,
	D3DRS_CCW_STENCILZFAIL = 0xBB,
	D3DRS_CCW_STENCILPASS = 0xBC,
	D3DRS_CCW_STENCILFUNC = 0xBD,
	D3DRS_COLORWRITEENABLE1 = 0xBE,
	D3DRS_COLORWRITEENABLE2 = 0xBF,
	D3DRS_COLORWRITEENABLE3 = 0xC0,
	D3DRS_BLENDFACTOR = 0xC1,
	D3DRS_SRGBWRITEENABLE = 0xC2,
	D3DRS_DEPTHBIAS = 0xC3,
	D3DRS_WRAP8 = 0xC6,
	D3DRS_WRAP9 = 0xC7,
	D3DRS_WRAP10 = 0xC8,
	D3DRS_WRAP11 = 0xC9,
	D3DRS_WRAP12 = 0xCA,
	D3DRS_WRAP13 = 0xCB,
	D3DRS_WRAP14 = 0xCC,
	D3DRS_WRAP15 = 0xCD,
	D3DRS_SEPARATEALPHABLENDENABLE = 0xCE,
	D3DRS_SRCBLENDALPHA = 0xCF,
	D3DRS_DESTBLENDALPHA = 0xD0,
	D3DRS_BLENDOPALPHA = 0xD1,
	D3DRS_FORCE_DWORD = 0x7FFFFFFF,
} D3DRENDERSTATETYPE;

typedef enum _D3DSAMPLERSTATETYPE {
	D3DSAMP_ADDRESSU = 1,
	D3DSAMP_ADDRESSV = 2,
	D3DSAMP_ADDRESSW = 3,
	D3DSAMP_BORDERCOLOR = 4,
	D3DSAMP_MAGFILTER = 5,
	D3DSAMP_MINFILTER = 6,
	D3DSAMP_MIPFILTER = 7,
	D3DSAMP_MIPMAPLODBIAS = 8,
	D3DSAMP_MAXMIPLEVEL = 9,
	D3DSAMP_MAXANISOTROPY = 0xA,
} D3DSAMPLERSTATETYPE;

typedef enum _D3DSHADEMODE {
	D3DSHADE_FLAT = 1,
	D3DSHADE_GOURAUD = 2,
} D3DSHADEMODE;

typedef enum _D3DSTENCILOP {
	D3DSTENCILOP_KEEP = 1,
	D3DSTENCILOP_ZERO = 2,
	D3DSTENCILOP_REPLACE = 3,
	D3DSTENCILOP_INCRSAT = 4,
	D3DSTENCILOP_DECRSAT = 5,
	D3DSTENCILOP_INVERT = 6,
	D3DSTENCILOP_INCR = 7,
	D3DSTENCILOP_DECR = 8,
} D3DSTENCILOP;

typedef enum _D3DTEXTUREADDRESS {
	D3DTADDRESS_WRAP = 1,
	D3DTADDRESS_MIRROR = 2,
	D3DTADDRESS_CLAMP = 3,
	D3DTADDRESS_BORDER = 4,
	D3DTADDRESS_MIRRORONCE = 5,
} D3DTEXTUREADDRESS;

typedef enum _D3DTEXTUREFILTERTYPE {
	D3DTEXF_NONE = 0,
	D3DTEXF_POINT = 1,
	D3DTEXF_LINEAR = 2,
} D3DTEXTUREFILTERTYPE;

typedef enum _D3DTEXTUREOP {
	D3DTOP_DISABLE = 1,
	D3DTOP_SELECTARG1 = 2,
	D3DTOP_SELECTARG2 = 3,
	D3DTOP_MODULATE = 4,
	D3DTOP_MODULATE2X = 5,
	D3DTOP_ADD = 7,
	D3DTOP_DOTPRODUCT3 = 0x18,
} D3DTEXTUREOP;

typedef enum _D3DTEXTURESTAGESTATETYPE {
	D3DTSS_COLOROP = 1,
	D3DTSS_COLORARG1 = 2,
	D3DTSS_COLORARG2 = 3,
	D3DTSS_ALPHAOP = 4,
	D3DTSS_ALPHAARG1 = 5,
	D3DTSS_ALPHAARG2 = 6,
	D3DTSS_TEXCOORDINDEX = 0xB,
	D3DTSS_TEXTURETRANSFORMFLAGS = 0x18,
	D3DTSS_COLORARG0 = 0x1A,
	D3DTSS_ALPHAARG0 = 0x1B,
} D3DTEXTURESTAGESTATETYPE;

typedef enum _D3DTRANSFORMSTATETYPE {
	D3DTS_VIEW = 2,
	D3DTS_PROJECTION = 3,
	D3DTS_TEXTURE0 = 0x10,
} D3DTRANSFORMSTATETYPE;

typedef enum _D3DTEXTURETRANSFORMFLAGS {
	D3DTTFF_DISABLE = 0,
	D3DTTFF_COUNT2 = 2,
	D3DTTFF_COUNT3 = 3,
} D3DTEXTURETRANSFORMFLAGS;

typedef DWORD D3DCOLOR;

typedef struct _D3DVERTEXELEMENT9 {
	WORD Stream;
	WORD Offset;
	BYTE Type;
	BYTE Method;
	BYTE Usage;
	BYTE UsageIndex;
} D3DVERTEXELEMENT9;

#define D3DCOLORWRITEENABLE_ALPHA 8
#define D3DCOLORWRITEENABLE_BLUE 4
#define D3DCOLORWRITEENABLE_GREEN 2
#define D3DCOLORWRITEENABLE_RED 1
#define D3DDECL_END() {0xFF,0,D3DDECLTYPE_UNUSED,0,0,0}
#define D3DFVF_DIFFUSE 0x40
#define D3DFVF_LASTBETA_D3DCOLOR 0x8000
#define D3DFVF_LASTBETA_UBYTE4 0x1000
#define D3DFVF_NORMAL 0x10
#define D3DFVF_POSITION_MASK 0x400E
#define D3DFVF_PSIZE 0x20
#define D3DFVF_RESERVED0 1
#define D3DFVF_RESERVED2 0x6000
#define D3DFVF_SPECULAR 0x80
#define D3DFVF_TEX1 0x100
#define D3DFVF_TEX2 0x200
#define D3DFVF_TEX3 0x300
#define D3DFVF_TEX4 0x400
#define D3DFVF_TEX7 0x700
#define D3DFVF_TEXCOUNT_MASK 0xF00
#define D3DFVF_TEXCOUNT_SHIFT 8
#define D3DFVF_XYZ 2
#define D3DFVF_XYZB1 6
#define D3DFVF_XYZB2 8
#define D3DFVF_XYZB3 0xA
#define D3DFVF_XYZB4 0xC
#define D3DFVF_XYZB5 0xE
#define D3DFVF_XYZRHW 4
#define D3DFVF_XYZW 0x4002
#define D3DLOCK_DISCARD 0x2000
#define D3DLOCK_NOOVERWRITE 0x1000
#define D3DLOCK_READONLY 0x10
#define D3DTA_CURRENT 1
#define D3DTA_DIFFUSE 0
#define D3DTA_TEXTURE 2
#define D3DTA_TFACTOR 3
#define D3DTSS_TCI_CAMERASPACENORMAL 0x10000
#define D3DTSS_TCI_CAMERASPACEPOSITION 0x20000
#define D3DTSS_TCI_CAMERASPACEREFLECTIONVECTOR 0x30000
#define D3DTSS_TCI_PASSTHRU 0
#define MAXD3DDECLLENGTH 0x40
#define D3DCOLOR_ARGB(a,r,g,b) ((D3DCOLOR)((((a)&0xff)<<24)|(((r)&0xff)<<16)|(((g)&0xff)<<8)|((b)&0xff)))
#define D3DCOLOR_RGBA(r,g,b,a) D3DCOLOR_ARGB(a,r,g,b)
#define D3DFVF_TEXCOORDSIZE2(CoordIndex) (0)
#define D3DFVF_TEXCOORDSIZE3(CoordIndex) (1 << ((CoordIndex) * 2 + 16))
#define D3DFVF_TEXCOORDSIZE4(CoordIndex) (2 << ((CoordIndex) * 2 + 16))
#define D3DTS_WORLD 0x100
#define D3D_OK S_OK
#define D3DERR_DEVICELOST ((HRESULT)0x88760868L)
#ifndef MAKEFOURCC
#define MAKEFOURCC(ch0, ch1, ch2, ch3) ((DWORD)(BYTE)(ch0) | ((DWORD)(BYTE)(ch1) << 8) | ((DWORD)(BYTE)(ch2) << 16) | ((DWORD)(BYTE)(ch3) << 24))
#endif
