////////////////////////////////////////////////////////////////////////////
//	Module 		: script_engine_export.h
//	Created 	: 01.04.2004
//  Modified 	: 22.06.2004
//	Author		: Dmitriy Iassenev
//	Description : XRay Script Engine export
////////////////////////////////////////////////////////////////////////////

#pragma once

#include "../xrScripts/exports/script_fvector.h"
#include "../xrScripts/exports/script_fcolor.h"
#include "../xrScripts/exports/script_fmatrix.h"
#include "../xrScripts/exports/script_flags.h"
#include "../xrScripts/script_engine.h"
#include "../xrScripts/exports/script_token_list.h"
#include "../xrScripts/exports/script_rtoken_list.h"
#include "../xrScripts/exports/script_ini_file.h"
#include "../xrScripts/exports/fs_registrator.h"
#include "../xrScripts/exports/script_reader.h"
#include "../xrScripts/exports/script_net_packet.h"
#include "object_factory.h"
#include "../xrScripts/exports/script_sound_type.h"
#include "xrServer_Objects_ALife_All.h"
#include "xrServer_Objects_Alife_Smartcovers.h"


#ifndef XRGAME_EXPORTS
#	include "script_properties_list_helper.h"
#else
#	include "../xrGame/base_client_classes.h"
#	include "../xrGame/alife_simulator.h"
#	include "../xrGame/script_hit.h"
#	include "../xrGame/script_monster_hit_info.h"
#	include "../xrGame/script_sound_info.h"
#	include "../xrGame/script_sound.h"
#	include "../xrGame/script_particles.h"
#	include "../xrGame/script_binder_object.h"
#	include "../xrGame/action_planner_action.h"
#	include "../xrGame/action_planner.h"
#	include "../xrGame/action_base.h"
#	include "../xrGame/property_storage.h"
#	include "../xrGame/property_evaluator.h"
#	include "../xrGame/script_world_state.h"
#	include "../xrGame/script_world_property.h"
#	include "../xrGame/ai/stalker/ai_stalker.h"
#	include "../xrGame/script_effector.h"
#	include "../xrGame/Level.h"
#	include "../xrGame/memory_space.h"
#	include "../xrGame/script_render_device.h"
#	include "../xrGame/script_game_object.h"
#	include "../xrGame/cover_point.h"
#	include "../xrGame/patrol_path_params.h"
#	include "../xrGame/particle_params.h"
#	include "../xrGame/script_movement_action.h"
#	include "../xrGame/script_watch_action.h"
#	include "../xrGame/script_animation_action.h"
#	include "../xrGame/script_sound_action.h"
#	include "../xrGame/script_particle_action.h"
#	include "../xrGame/script_object_action.h"
#	include "../xrGame/script_action_condition.h"
#	include "../xrGame/script_monster_action.h"
#	include "../xrGame/script_entity_action.h"
#	include "../xrGame/helicopter.h"
#	include "../xrGame/game_base.h"
#	include "../xrGame/demoinfo.h"
#	include "../xrGame/script_ui_registrator.h"
#	include "../xrGame/key_binding_registrator.h"
#	include "../xrGame/console_registrator.h"
#	include	"../xrGame/physics_shell_scripted.h"
#	include	"../xrGame/physics_joint_scripted.h"
#	include	"../xrGame/physics_element_scripted.h"
#	include	"../xrGame/physics_world_scripted.h"

#	include	"../xrGame/HangingLamp.h"
#	include "../xrGame/holder_custom.h"
#	include "../xrGame/GameTask.h"
#	include "../xrGame/client_spawn_manager.h"
#	include "../xrGame/script_zone.h"
#	include "../xrGame/ef_storage.h"
#	include "../xrGame/ai/stalker/ai_stalker.h"
#	include "../xrGame/ai/monsters/bloodsucker/bloodsucker.h"
#	include "../xrGame/ai/monsters/boar/boar.h"
#	include "../xrGame/ai/monsters/dog/dog.h"
#	include "../xrGame/ai/monsters/flesh/flesh.h"
#	include "../xrGame/ai/monsters/pseudodog/pseudodog.h"
#	include "../xrGame/ai/monsters/pseudodog/psy_dog.h"
#	include "../xrGame/ai/monsters/burer/burer.h"
#	include "../xrGame/ai/monsters/chimera/chimera.h"
#	include "../xrGame/ai/monsters/pseudogigant/pseudo_gigant.h"
#	include "../xrGame/ai/monsters/poltergeist/poltergeist.h"
#	include "../xrGame/ai/monsters/zombie/zombie.h"
#	include "../xrGame/ai/monsters/fracture/fracture.h"
#	include "../xrGame/ai/monsters/snork/snork.h"
#	include "../xrGame/ai/monsters/controller/controller.h"
#	include "../xrGame/ai/monsters/cat/cat.h"
#	include "../xrGame/ai/monsters/tushkano/tushkano.h"
#	include "../xrGame/PhraseDialog_script.h"
#	ifdef	DEBUG
#		include "../xrGame/PHDebug.h"
#	endif
#	include "../xrGame/hit.h"
#	include "../xrGame/PHDestroyable.h"
#	include "../xrGame/car.h"
#	include "../xrGame/script_lanim.h"
#	include "../xrGame/artefact.h"
#	include "../xrGame/game_cl_single.h"
#	include "../xrGame/game_base.h"
#	include "../xrGame/game_sv_base.h"
#	include "../xrGame/game_sv_mp.h"
#	include "../xrGame/game_sv_deathmatch.h"
#	include "../xrGame/game_sv_mp_script.h"
#	include "../xrGame/game_cl_mp.h"
#	include "../xrGame/game_cl_mp_script.h"
#	include "alife_human_brain.h"
#	include "alife_monster_brain.h"
#	include "../xrGame/alife_monster_movement_manager.h"
#	include "../xrGame/alife_monster_patrol_path_manager.h"
#	include "../xrGame/alife_monster_detail_path_manager.h"
#	include "../xrGame/alife_smart_terrain_task.h"
#	include "../xrGame/game_graph.h"
#	include "../xrGame/smart_zone.h"
#	include "../xrGame/F1.h"
#	include "../xrGame/RGD5.h"
#	include "../xrGame/Scope.h"
#	include "../xrGame/StalkerOutfit.h"
#	include "../xrGame/Torch.h"
#	include "../xrGame/WeaponAK74.h"
#	include "../xrGame/WeaponBinoculars.h"
#	include "../xrGame/weaponBM16.h"
#	include "../xrGame/WeaponFN2000.h"
#	include "../xrGame/WeaponFORT.h"
#	include "../xrGame/WeaponGroza.h"
#	include "../xrGame/WeaponHPSA.h"
#	include "../xrGame/WeaponKnife.h"
#	include "../xrGame/WeaponLR300.h"
#	include "../xrGame/WeaponPM.h"
#	include "../xrGame/WeaponRG6.h"
#	include "../xrGame/WeaponRPG7.h"
#	include "../xrGame/WeaponShotgun.h"
#	include "../xrGame/WeaponSVD.h"
#	include "../xrGame/WeaponSVU.h"
#	include "../xrGame/WeaponUSP45.h"
#	include "../xrGame/WeaponVal.h"
#	include "../xrGame/WeaponVintorez.h"
#	include "../xrGame/WeaponWalther.h"
#	include "../xrGame/saved_game_wrapper.h"
#	include "../xrGame/Mincer.h"
#	include "../xrGame/MosquitoBald.h"
#	include "../xrGame/HairsZone.h"
#	include "../xrGame/ai/trader/ai_trader.h"
#	include "../xrGame/space_restrictor.h"
#	include "../xrGame/PhysicObject.h"
#	include "../xrGame/smart_cover_object.h"
#	include "../xrGame/ui/FactionState.h"
#	include "../xrGame/Actor.h"
#	include "../xrGame/GametaskManager.h"
#endif
