function normal   (shader, t_base, t_second, t_detail)
      shader:begin    ("deffer_model","model_pda_screen")
      : fog            (true)
      : zb            (true,false)
      : blend        (true,blend.srcalpha,blend.invsrcalpha)
      : aref        (true,0)
      : sorting        (2,true)
      : distort        (true)
    shader:dx10texture    ("s_base",    t_base)
    shader:dx10texture     ("s_vp2",    "$user$ui_pda")    
    shader:dx10texture     ("s_load",    "ui\\ui_pda_loadscreen")    
    shader:dx10sampler    ("smp_rtlinear")    
    shader:dx10sampler    ("smp_base")    
end
