class "se_artefact"	(cse_alife_item_artefact)

function se_artefact:__init (section) super (section)
end

function se_artefact:on_register()
	cse_alife_item_artefact.on_register(self)	
	SendScriptCallback("server_entity_on_register", self, "se_artefact")
end

function se_artefact:on_unregister()
	SendScriptCallback("server_entity_on_unregister", self, "se_artefact")
	cse_alife_item_artefact.on_unregister(self)
end

--------------------
function se_artefact:can_switch_offline ()
	return cse_alife_item_artefact.can_switch_offline (self)
end
--------------------
function se_artefact:can_switch_online ()
    return cse_alife_item_artefact.can_switch_online (self)
end
--------------------
