class "opt_video_adv" (CUIWindow)
function opt_video_adv:__init() super()
end

function opt_video_adv:__finalize()
end

function all_modes(render_id)
	return true
end

function mode_1(id)
	return id == "renderer_r1"
end

function mode_2(id)
	return id ~= "renderer_r1"
end

function mode_4(id)
	return id == "renderer_r4"
end

function opt_video_adv:InitControls(x, y, xml, handler)
	self:SetWndPos(vector2():set(x,y))
	self:SetWndSize(vector2():set(738,416))
	self:SetAutoDelete(true)

	if xml:NodeExist("frame_videoadv", 0) then
		xml:InitFrame("frame_videoadv", self)
	end
	self.focusList = {}
	self.scroll_v = xml:InitScrollView("main_dialog:scroll_v", self)
    handler.scroll_v = self.scroll_v
	
	self.btn_simply = xml:Init3tButton("main_dialog:btn_template", self)
	self.btn_simply:SetTextST("ui_mm_simply")
	handler:Register(self.btn_simply, "btn_simply_graphic")
	
	local ctl = nil

	local reloadControls = function()
		local pos = handler.scroll_v:GetCurrentScrollPos()
		handler:UpdateDependControls()
		handler.scroll_v:SetScrollPos(pos)
	end
	
	-----------------------------------------------------------------------------
	-----------------------------------------------------------------------------
	-----------------------------------------------------------------------------
	
	handler:lineFrame(self, all_modes, "st_common_settings")

	handler:addTrack(self, all_modes, "ui_mm_detail_density", "r__detail_density", 0.02, true, "float", false, system_depends.sdVidRestart)
	handler:addTrack(self, all_modes, "ui_mm_grass_distance", "r__detail_radius", 1, false, "int", true, system_depends.sdNothing)    
	handler:addTrack(self, all_modes, "ui_mm_vis_distance", "rs_vis_distance", 0.1, false, "float", false, system_depends.sdNothing)
	handler:addTrack(self, all_modes, "ui_mm_geometry_lod", "r__geometry_lod", 0.1, false, "float", false, system_depends.sdNothing)

	-----------------------------------------------------------------------------
	-----------------------------------------------------------------------------
	-----------------------------------------------------------------------------
	
	handler:lineFrame(self, all_modes, "st_surface_options")

	handler:addTrack(self, all_modes, "ui_mm_texture_quality", "texture_lod", 1, true, "int", false, system_depends.sdVidRestart)
	handler:addTrack(self, all_modes, "ui_mm_anisotropic", "r__tf_aniso", 1, false, "int", false, system_depends.sdNothing)
	
	handler:addCheck(self, mode_1, "ui_mm_r1_detail_textures", "r1_detail_textures", system_depends.sdNothing)
	handler:addCheck(self, mode_2, "ui_mm_r2_detail_bump", "r2_detail_bump", system_depends.sdNothing)
	handler:addCheck(self, mode_2, "ui_mm_r2_steep_parallax", "r2_steep_parallax", system_depends.sdNothing)
	handler:addCheck(self, mode_4, "ui_mm_r4_enable_tessellation", "r4_enable_tessellation", system_depends.sdVidRestart)
	
	-----------------------------------------------------------------------------
	-----------------------------------------------------------------------------
	-----------------------------------------------------------------------------
	
	handler:lineFrame(self, all_modes, "st_aa_options")

 	handler:addComboBox(self, mode_4, "ui_mm_r_scale_mode", "vid_scale_mode", 5, false, system_depends.sdVidRestart, "scaleMode")
    handler:AddCallback("scaleMode", ui_events.LIST_ITEM_SELECT, reloadControls, nil)
	
	local scalePresetPrec = function(id)
		if mode_4(id) then
			local current_id = handler:GetComboBox("scaleMode"):CurrentID()
			if current_id > 1 then
				return true
			end
		end
		return false
	end
	
 	handler:addComboBox(self, scalePresetPrec, "ui_mm_r_scale_preset", "vid_scale_preset", 7, false, system_depends.sdVidRestart, "scalePreset")
    handler:AddCallback("scalePreset", ui_events.LIST_ITEM_SELECT, reloadControls, nil)
	
	local vidScalePrec = function(id)
		if mode_4(id) then
			local scale_mode = handler:GetComboBox("scaleMode"):CurrentID()
			if scale_mode > 1 then
				local scale_preset = handler:GetComboBox("scalePreset"):CurrentID()
				local value = handler:GetComboBox("scalePreset"):GetValueOf(scale_preset)
				return value == "st_scale_custom"
			end
			return true
		end
		return false
	end
	
	handler:addTrack(self, vidScalePrec, "ui_mm_vid_scale", "vid_scale", 0.01, false, "float", true, system_depends.sdVidRestart, "scaleTrack", 100)

	local typeAAPrec = function(id)
		if mode_4(id) then
			local current_id = handler:GetComboBox("scaleMode"):CurrentID()
			if current_id > 1 then
				handler:GetCheck("hashedAlpha"):Enable(true)
				return false
			end
			handler:GetCheck("hashedAlpha"):Enable(false)
			handler:GetCheck("hashedAlpha"):SetCheck(false)
		end
		return true
	end
	
	handler:addTrack(self, mode_4, "ui_mm_cas_sharpening", "r4_cas_sharpening", 0.01, false, "float", true, system_depends.sdNothing, "sharpeningTrack", 100)

	handler:addCheck(self, mode_4, "ui_mm_hashed_alpha_test", "r4_hashed_alpha_test", system_depends.sdSystemRestart, "hashedAlpha")
	
	handler:addComboBox(self, typeAAPrec, "ui_mm_supersample", "r_aa", 4, false, system_depends.sdNothing)
	
	-----------------------------------------------------------------------------
	-----------------------------------------------------------------------------
	-----------------------------------------------------------------------------
	
	handler:lineFrame(self, all_modes, "st_lights_options")

	handler:addTrack(self, mode_2, "ui_mm_sun_quality", "r2_ls_squality", 0.1, false, "float", false, system_depends.sdNothing)
	handler:addTrack(self, mode_2, "ui_mm_light_distance", "r2_slight_fade", 0.01, false, "float", false, system_depends.sdNothing)
	handler:addCheck(self, all_modes, "ui_mm_npc_torch", "ai_use_torch_dynamic_lights", system_depends.sdNothing)
	handler:addCheck(self, mode_2, "ui_mm_volumetric_light", "r2_volumetric_lights", system_depends.sdVidRestart)
	handler:addCheck(self, mode_4, "ui_mm_r4_hud_shadows", "r4_hud_shadows", system_depends.sdVidRestart)
	handler:addCheck(self, all_modes, "ui_mm_r_actor_shadow", "r_actor_shadow", system_depends.sdNothing)
	
	-----------------------------------------------------------------------------
	-----------------------------------------------------------------------------
	-----------------------------------------------------------------------------
	
	handler:lineFrame(self, mode_2, "st_sunlight_options")

    local sunTable = {}	
	
	handler.enableSun = handler:addCheck(self, nil, "ui_mm_r2_sun", "r2_sun", system_depends.sdSystemRestart, "enableSun")

    local enableSunFunc = function(id)
		if mode_2(id) then
			for _, control in pairs(sunTable) do
				control:Enable(handler.enableSun:GetCheck())
				if control.GetCheck then
					control:SetCheck(control:GetCheck() and handler.enableSun:GetCheck())
				end
			end
			return true
		end
		return false
    end
	
	table.insert(handler.m_preconditions, {func=enableSunFunc, control=handler.enableSun:GetParent()})
    handler:AddCallback("enableSun", ui_events.BUTTON_CLICKED, reloadControls, nil)

	ctl = handler:addCheck(self, mode_2, "ui_mm_r2_details_shadows", "r2_sun_details", system_depends.sdNothing)
    table.insert(sunTable, ctl)
	
	ctl = handler:addCheck(self, mode_2, "ui_mm_lights_details", "r2_lights_details", system_depends.sdNothing)
    table.insert(sunTable, ctl)
	
	ctl = handler:addCheck(self, mode_2, "ui_mm_r2_cloud_shadows", "r2_cloud_shadows", system_depends.sdVidRestart)
    table.insert(sunTable, ctl)
	
  	ctl = handler:addComboBox(self, mode_2, "ui_mm_r2_sun_quality", "r2_sun_quality", 6, false, system_depends.sdVidRestart)
    table.insert(sunTable, ctl)
	
  	ctl = handler:addComboBox(self, mode_2, "ui_mm_sun_shafts", "r2_sun_shafts", 5, false, system_depends.sdVidRestart)
    table.insert(sunTable, ctl)

  	handler:addComboBox(self, mode_2, "ui_mm_r__smap_size", "r2_smap_size", 5, false, system_depends.sdSystemRestart)
	
	-----------------------------------------------------------------------------
	-----------------------------------------------------------------------------
	-----------------------------------------------------------------------------
	
	handler:lineFrame(self, mode_2, "st_effects_options")

  	handler:addComboBox(self, mode_2, "ui_mm_ssao_text", "r2_ssao_mode", 5, false, system_depends.sdSystemRestart)

	handler:addCheck(self, mode_2, "ui_mm_soft_water", "r2_soft_water", system_depends.sdVidRestart)
	handler:addCheck(self, mode_2, "ui_mm_soft_particles", "r2_soft_particles", system_depends.sdVidRestart)
	handler:addCheck(self, mode_4, "ui_mm_r3_dynamic_wet_surfaces", "r3_dynamic_wet_surfaces", system_depends.sdNothing)
	handler:addCheck(self, mode_4, "ui_mm_sslr_water", "r4_sslr_water", system_depends.sdSystemRestart)
	handler:addCheck(self, mode_4, "ui_mm_r3_volumetric_smoke", "r3_volumetric_smoke", system_depends.sdNothing)
	handler:addCheck(self, mode_4, "ui_mm_puddles", "r4_puddles", system_depends.sdNothing)
	-----------------------------------------------------------------------------
	-----------------------------------------------------------------------------
	-----------------------------------------------------------------------------
	
	handler:lineFrame(self, mode_2, "st_postprocess_options")
	
	handler:addCheck(self, mode_2, "ui_mm_vignette", "r2_vignette", system_depends.sdNothing)
	handler:addCheck(self, mode_2, "ui_mm_aberration", "r2_aberration", system_depends.sdNothing)
	handler:addCheck(self, mode_2, "ui_mm_saturation", "r2_saturation", system_depends.sdNothing)
	handler:addCheck(self, mode_4, "ui_mm_r4_use_gasmask", "r4_use_gasmask", system_depends.sdNothing)
	handler:addCheck(self, mode_2, "ui_mm_r2_use_rain_drops", "r2_use_rain_drops", system_depends.sdNothing)

	handler.enableDof = handler:addCheck(self, mode_2, "ui_mm_dof", "r2_dof_enable", system_depends.sdVidRestart, "enableDof")
    handler:AddCallback("enableDof", ui_events.BUTTON_CLICKED, reloadControls, nil)

	handler.reloadDof = handler:addCheck(self, nil, "ui_mm_dof_reload", "enable_dof_reload", system_depends.sdNothing)
    
    local enableReloadDofFunc = function(id)
		if mode_2(id) then
			handler.reloadDof:Enable(handler.enableDof:GetCheck())
			handler.reloadDof:SetCheck(handler.reloadDof:GetCheck() and handler.enableDof:GetCheck())
			return true
		end
		return false
    end
	
    table.insert(handler.m_preconditions, {func=enableReloadDofFunc, control=handler.reloadDof:GetParent()})

   	handler.talkDof = handler:addCheck(self, nil, "ui_mm_dof_talk", "enable_dof_talk", system_depends.sdNothing)
    
    local enableTalkDofFunc = function(id)
		if mode_2(id) then
			handler.talkDof:Enable(handler.enableDof:GetCheck())
			handler.talkDof:SetCheck(handler.talkDof:GetCheck() and handler.enableDof:GetCheck())
			return true
		end
		return false
    end
	
    table.insert(handler.m_preconditions, {func=enableTalkDofFunc, control=handler.talkDof:GetParent()})
end
