class "opt_sound" (CUIWindow)

function opt_sound:__init() super()
end

function opt_sound:__finalize()

end

function opt_sound:InitControls(x, y, xml, handler)

    self:SetWndPos(vector2():set(x,y))
    self:SetWndSize(vector2():set(738,416))
    self:SetAutoDelete(true)
	if xml:NodeExist("frame", 0) then
		self.bk = xml:InitFrame("frame", self)
	end
 	self.focusList = {}
    self.scroll_v = xml:InitScrollView("main_dialog:scroll_v", self)

    local _st
	
    _st = xml:InitStatic("video_adv:templ_item", nil)
    local caption = xml:InitStatic("tab_sound:cap_mastervolume", _st)
    local element = xml:InitTrackBar("tab_sound:track_mastervolume", _st)
    handler:addControl(self, caption, element, _st)

    --_st = xml:InitStatic("video_adv:templ_item", nil)
    --caption = xml:InitStatic("tab_sound:cap_shootvolume", _st)
    --element = xml:InitTrackBar("tab_sound:track_shootvolume", _st)
    --handler:addControl(self, caption, element, _st)

    _st = xml:InitStatic("video_adv:templ_item", nil)
    caption = xml:InitStatic("tab_sound:cap_musicvolume", _st)
    element = xml:InitTrackBar("tab_sound:track_musicvolume", _st)
    handler:addControl(self, caption, element, _st)

    _st = xml:InitStatic("video_adv:templ_item", nil)
    caption = xml:InitStatic("tab_sound:cap_snd_device", _st)
    element = xml:InitComboBox("tab_sound:list_snd_device", _st)
    handler:addControl(self, caption, element, _st)

	if not is_soc() then
		_st = xml:InitStatic("video_adv:templ_item", nil)
		caption = xml:InitStatic("tab_sound:cap_check_dynamic_music", _st)
		element = xml:InitCheck("tab_sound:check_dynamic_music", _st)
		handler:addControl(self, caption, element, _st)
	end
	
    _st = xml:InitStatic("video_adv:templ_item", nil)
    caption = xml:InitStatic("tab_sound:cap_check_eax", _st)
    element = xml:InitCheck("tab_sound:check_eax", _st)
    handler:addControl(self, caption, element, _st)
end
