class "opt_gameplay" (CUIWindow)

function opt_gameplay:__init() super()
end

function opt_gameplay:__finalize()

end

function opt_gameplay:InitControls(x, y, xml, handler)

    self:SetWndPos(vector2():set(x,y))
    self:SetWndSize(vector2():set(738,416))
    self:SetAutoDelete(true)
	
	if xml:NodeExist("frame_gameplay", 0) then
		self.bk = xml:InitFrame("frame_gameplay", self)
	end
 	self.focusList = {}
	self.scroll_v = xml:InitScrollView("main_dialog:scroll_v", self)

	handler:lineFrame(self, true, "st_common_settings")
	
	handler:addComboBox(self, true, "ui_mm_difficulty", "g_game_difficulty", 4, false, system_depends.sdNothing)
	handler:addComboBox(self, true, "ui_mm_lang", "language", 4, false, system_depends.sdNothing)
	handler:addComboBox(self, true, "st_quicksaves_count", "g_quicksaves_count", 4, false, system_depends.sdNothing)
	
	handler:lineFrame(self, true, "st_gameplay_settings")

	handler:addCheck(self, true, "st_3d_scopes", "g_3d_scopes", system_depends.sdNothing)
	handler:addTrack(self, true, "ui_mm_bobbing_factor", "g_bobbing_factor", 0.1, false, "float", true, system_depends.sdNothing, nil, 10)
	handler:addCheck(self, true, "ui_mm_hit_slowmo", "g_hit_slowmo", system_depends.sdNothing)
	handler:addCheck(self, true, "ui_mm_wpn_aim_toggle", "wpn_aim_toggle", system_depends.sdNothing)
	if is_cop() then
		handler:addCheck(self, true, "ui_mm_important_save", "g_important_save", system_depends.sdNothing)
	end	
	handler:addCheck(self, true, "ui_mm_show_weapon", "hud_weapon", system_depends.sdNothing)
	handler:addCheck(self, true, "ui_mm_crouch_toggle", "g_crouch_toggle", system_depends.sdNothing)

	handler:lineFrame(self, true, "st_ui_settings")

	handler:addCheck(self, true, "ui_mm_show_crosshair", "hud_crosshair", system_depends.sdNothing)
	handler:addCheck(self, true, "ui_mm_dyn_crosshair", "cl_dynamiccrosshair", system_depends.sdNothing)
	handler:addCheck(self, true, "ui_mm_crosshair_distance", "hud_crosshair_dist", system_depends.sdNothing)
	handler:addCheck(self, true, "ui_mm_tips", "hud_info", system_depends.sdNothing)
 	handler:addCheck(self, true, "ui_st_disable_hud", "hud_draw", system_depends.sdNothing)
 	handler:addCheck(self, true, "ui_rs_fps_show", "rs_fps_show", system_depends.sdNothing)
	handler:addCheck(self, true, "ui_mm_show_minimap", "hud_minimap", system_depends.sdNothing)
	handler:addCheck(self, true, "ui_mm_hide_quick_slots", "hud_hide_quick_slots", system_depends.sdNothing)
end
