cmake_minimum_required(VERSION 3.18)

project(LuaJIT)

set(LUA_COMMAND "" CACHE FILEPATH "Path to existing Lua interpreter")
option(LUAJIT_ENABLE_CLI "Enable building LuaJIT CLI" OFF)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)

set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_EX ${CMAKE_BINARY_DIR}/lib/$<CONFIG>)

set(MAJVER 2)
set(MINVER 0)
set(ABIVER 5.1)
set(NODOTABIVER 51)

set(DASM ${CMAKE_CURRENT_SOURCE_DIR}/dynasm/dynasm.lua)

if(WIN32)
    set(LJCOMPILE_FLAGS /W3 /MP)
    set(LJCOMPILE_DEFS -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -DLUAJIT_OS=LUAJIT_OS_WINDOWS)
    set(LJDYNBUILD -DLUA_BUILD_AS_DLL -D "_CRT_STDIO_INLINE=__declspec(dllexport)__inline")
    set(LJVM_MODE peobj)

    if(CMAKE_SYSTEM_PROCESSOR MATCHES "i386|i686|x86" OR CMAKE_VS_PLATFORM_NAME STREQUAL "Win32")
        set(LJCOMPILE_FLAGS ${LJCOMPILE_FLAGS} /arch:SSE2)
        set(DASC ${CMAKE_CURRENT_SOURCE_DIR}/src/vm_x86.dasc)
        set(DASMFLAGS -D WIN -D JIT -D FFI -D ENDIAN_LE -D FPU)
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "x64|x86_64|AMD64" OR CMAKE_VS_PLATFORM_NAME STREQUAL "x64")
        set(DASC ${CMAKE_CURRENT_SOURCE_DIR}/src/vm_x86.dasc)
        set(DASMFLAGS -D WIN -D JIT -D FFI -D ENDIAN_LE -D FPU -D P64)
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "arm" OR CMAKE_VS_PLATFORM_NAME STREQUAL "ARM")
        set(DASC ${CMAKE_CURRENT_SOURCE_DIR}/src/vm_arm.dasc)
        set(DASMFLAGS -D WIN -D JIT -D FFI)
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "arm64|aarch64" OR CMAKE_VS_PLATFORM_NAME STREQUAL "ARM64")
        set(DASC ${CMAKE_CURRENT_SOURCE_DIR}/src/vm_arm.dasc)
        set(DASMFLAGS -D WIN -D JIT -D FFI -D P64)
    endif()
elseif(UNIX AND NOT APPLE)
    set(LJCOMPILE_FLAGS -O2 -fomit-frame-pointer -fno-stack-protector -Wall -fPIC -Wno-misleading-indentation)
    set(LJCOMPILE_DEFS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DLUAJIT_UNWIND_EXTERNAL -DLUAJIT_OS=LUAJIT_OS_LINUX)
    set(LJDYNBUILD -shared)
    set(LJVM_MODE elfasm)

    if(CMAKE_SYSTEM_PROCESSOR MATCHES "i386|i686")
        set(DASC ${CMAKE_CURRENT_SOURCE_DIR}/src/vm_x86.dasc)
        set(LJCOMPILE_FLAGS -march=i686 -msse -msse2 -mfpmath=sse ${LJCOMPILE_FLAGS})
        set(DASMFLAGS -D ENDIAN_LE -D JIT -D FFI -D FPU -D HFABI)
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "x64|x86_64|AMD64")
        set(DASC ${CMAKE_CURRENT_SOURCE_DIR}/src/vm_x86.dasc)
        set(DASMFLAGS -D ENDIAN_LE -D P64 -D JIT -D FFI -D FPU -D HFABI)
    endif()
elseif(APPLE)
    set(LJCOMPILE_FLAGS -O2 -fomit-frame-pointer -fno-stack-protector -Wall -fPIC)
    set(LJCOMPILE_DEFS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DLUAJIT_UNWIND_EXTERNAL -DLUAJIT_OS=LUAJIT_OS_OSX)
    set(LJDYNBUILD -shared)
    set(LJVM_MODE machasm)

    if(CMAKE_SYSTEM_PROCESSOR MATCHES "arm64|aarch64" OR CMAKE_OSX_ARCHITECTURES MATCHES "arm64")
        set(DASC ${CMAKE_CURRENT_SOURCE_DIR}/src/vm_arm.dasc)
        set(DASMFLAGS -D ENDIAN_LE -D P64 -D JIT -D FFI -D DUALNUM -D FPU -D HFABI)
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "x64|x86_64|AMD64" OR CMAKE_OSX_ARCHITECTURES MATCHES "x86_64")
        set(DASC ${CMAKE_CURRENT_SOURCE_DIR}/src/vm_x86.dasc)
        set(DASMFLAGS -D ENDIAN_LE -D P64 -D JIT -D FFI -D FPU -D HFABI)
    endif()
endif()

if(UNIX AND NOT APPLE)
    find_library(LIBM_LIBRARY NAMES m)
    find_library(LIBDL_LIBRARY NAMES dl)
endif()

find_package(Git)

add_subdirectory(src/host)
add_subdirectory(src)
add_subdirectory(etc)
