--[[	axr_companions

by Alundaio

	Copyright (C) 2012 Alundaio
	This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License
-]]

-- SEE configs\ai_tweaks\axr_companions
allow_only_friends_as_companions = true
allow_simulation_squads_as_companions = false
max_actor_squad_size = 0 -- used only for non task companions

companion_squads = {}
------------------------------------------
local _current_move_mode = 1
local _current_combat_mode = 1
local _draw_part

------------------------------------------
-- Localized Functions
------------------------------------------
local function on_fighting_actor(npc)
	if not (IsStalker(npc)) then
		return 
	end
	--alun_utils.debug_write(strformat("axr_companions.on_fighting_actor"))
	if (db.actor:has_info("axr_has_companion")) then
		for i=1,max_actor_squad_size do
			local c = utils.load_var(db.actor,"companion_"..i,nil)
			local obj = c and level.object_by_id(c)
			if (obj) then
				alun_utils.set_squad_relation_to_squad(obj,npc,game_object.enemy)
			end
		end
	end
	for id,squad in pairs(companion_squads) do 
		xr_combat_ignore.safe_zone_npcs[id] = nil
		if (squad and squad.commander_id) then
			for k in squad:squad_members() do
				local member = db.storage[k.id] and db.storage[k.id].object
				if (member and member:alive()) then
					member:set_relation(game_object.enemy,npc)
					npc:set_relation(game_object.enemy,member)
				end
			end
		end
	end
end

local function squad_on_npc_death(squad,se_npc)
	--alun_utils.debug_write(strformat("axr_companions.squad_on_npc_death"))
	if (se_npc and alife():has_info(se_npc.id,"npcx_is_companion") ) then
		for i=1,max_actor_squad_size do
			local c = utils.load_var(db.actor,"companion_"..i,nil)
			if (c == se_npc.id) then
				utils.save_var(db.actor,"companion_"..i,nil)
			end
		end
		if (get_companion_count() < 1) then
			db.actor:disable_info_portion("axr_has_companion")
		end
		if (squad:npc_count() == 0) then 
			companion_squads[squad.id] = nil
		end
	end
end

local function squad_on_unregister(squad)
	companion_squads[squad.id] = nil
end

local function squad_on_update(squad)
	--alun_utils.debug_write(strformat("axr_companions.squad_on_update - heli_enemy_flag"))
	local id = squad:commander_id()
	local sim = alife()
	if (id and sim:has_info(id,"npcx_is_companion")) then
		squad.scripted_target = "actor"
		companion_squads[squad.id] = squad
		if (utils.load_var(db.actor,"heli_enemy_flag") == true) then
			for k in squad:squad_members() do
				if (db.storage[k.id]) then
					db.storage[k.id].heli_enemy_flag = true
				end
			end
		end
	end
end

local function on_level_changing()
	local sim = alife()
	local se_actor = sim:actor()
	
	local gg = game_graph()
	local gvid = se_actor.m_game_vertex_id
	local vert = gg:vertex(gvid)
	local lvid = vert:level_vertex_id()
	local pos = vert:level_point()
	
	for id,v in pairs(companion_squads) do 
		local squad = sim:object(id)
		if (squad and companion_squad_can_teleport(squad)) then
			TeleportSquad(squad,pos,lvid,gvid)
		end
	end
end

---------------------------------
-- Register Callbacks
---------------------------------
function on_game_load()
	-- Patriarch achievement doubles allowed squad sizes.
	local ini = ini_file("ai_tweaks\\axr_companions.ltx")
	if (has_alife_info("achieved_patriarch")) then
		max_actor_squad_size = ini:r_float_ex("main","max_actor_squad_size_patriarch") or 4
	end
end

function on_game_start()
	local ini = ini_file("ai_tweaks\\axr_companions.ltx")
	Enabled = ini:r_bool_ex("main","enable",false)
	if not (Enabled) then return end
	RegisterScriptCallback("npc_on_fighting_actor",on_fighting_actor)
	RegisterScriptCallback("squad_on_update",squad_on_update)
	RegisterScriptCallback("squad_on_npc_death",squad_on_npc_death)
	RegisterScriptCallback("squad_on_unregister",squad_on_unregister)
	RegisterScriptCallback("on_level_changing",on_level_changing)
	RegisterScriptCallback("on_game_load",on_game_load)

	allow_only_friends_as_companions = ini:r_bool_ex("main","allow_only_friends_as_companions",false)
	allow_simulation_squads_as_companions = ini:r_bool_ex("main","allow_simulation_squads_as_companions",false)
	max_actor_squad_size = ini:r_float_ex("main","max_actor_squad_size") or 2
end

function companion_squad_can_teleport(squad)
	local id = squad:commander_id()
	local sim = alife()
	local se_obj = sim:object(id)
	if (se_obj) then
		if (utils.se_obj_load_var(se_obj.id,se_obj:name(),"companion_cannot_teleport")) then 
			return false 
		end
	end 
	
	if (id) and (sim:has_info(id,"npcx_beh_patrol_mode") or sim:has_info(id,"npcx_beh_wait")) then
		return false
	end
	return true
end 

function get_companion_count()
	local count = 0
	for i=1,max_actor_squad_size do
		local c = utils.load_var(db.actor,"companion_"..i,nil)
		local se_obj = c and alife():object(c)
		if (se_obj and IsStalker(nil,se_obj:clsid()) and se_obj:alive()) then
			count = count + 1
		else 
			utils.save_var(db.actor,"companion_"..i,nil)
		end
	end
	return count
end

function list_actor_squad_by_id()
	local t = {}
	for i=1,max_actor_squad_size do
		local c = utils.load_var(db.actor,"companion_"..i,nil)
		if (c) then
			local se_obj = alife():object(c)
			if (se_obj and IsStalker(nil,se_obj:clsid()) and se_obj:alive()) then
				table.insert(t,c)
			else 
				utils.save_var(db.actor,"companion_"..i,nil)
			end
		end
	end
	return t
end 

function setup_companion_logic(npc,st,loaded,cannot_dismiss)
	npc:give_info_portion("npcx_is_companion")
	
	if (cannot_dismiss or utils.se_obj_load_var(npc:id(),npc:name(),"companion_cannot_dismiss")) then
		npc:give_info_portion("npcx_beh_cannot_dismiss")
	end
		
	local ltx_name = "scripts\\beh_companion.ltx"
	local ltx = ini_file(ltx_name)
	if not (ltx) then 
		log("ERROR: do not have access to scripts\\beh_companion.ltx! Make sure you installed properly!")
		return
	end
	
	local id = npc:id()
	local sim = alife()
	local se_npc = sim:object(id)
	local unreg_id = se_npc and se_npc.m_smart_terrain_id
	if (unreg_id and unreg_id ~= 65535) then
		local unreg = sim:object(unreg_id)
		if (unreg) then
			unreg:unregister_npc(se_npc)
		end
	end
	
	xr_logic.configure_schemes(npc, ltx, ltx_name, modules.stype_stalker, loaded and st.loaded_section_logic or "logic", "")
	
	local section = loaded and st.loaded_active_section or xr_logic.determine_section_to_activate(npc, ltx, "logic", db.actor)
	xr_logic.activate_by_section(npc, ltx, section, "", loaded)
	--printf("setup complete")
end 

function add_special_task_npc_to_actor_squad(npc)
	local id = npc:id()
	local sim = alife()
	local se_npc = sim:object(id)
	local unreg_id = se_npc and se_npc.m_smart_terrain_id
	if (unreg_id and unreg_id ~= 65535) then
		local unreg = sim:object(unreg_id)
		if (unreg) then
			unreg:unregister_npc(se_npc)
		end
	end
	npc:inactualize_patrol_path()
	npc:give_info_portion("npcx_is_companion")
	axr_logic.set_new_scheme_and_logic(npc,"beh","beh@base","logic",nil,"scripts\\beh_companion.ltx")
	setup_companion_logic(npc)
end 

function add_to_actor_squad(npc)
	local inserted
	local id = npc:id()
	for i=1,max_actor_squad_size do
		local c = utils.load_var(db.actor,"companion_"..i,nil)
		if not (c) then
			utils.save_var(db.actor,"companion_"..i,id)
			--alun_utils.debug_write("add to actor squad %s in slot %s",npc:name(),i)
			inserted = true
			break
		end
	end

	if not (inserted) then
		return
	end

	if not ( db.actor:has_info("axr_has_companion") ) then
		db.actor:give_info_portion("axr_has_companion")
	end

	local sim = alife()
	local se_npc = sim:object(id)
	if (se_npc) then
		utils.se_obj_save_var(se_npc.id,se_npc:name(),"companion",true)
	end
	setup_companion_logic(npc,db.storage[id],false)
	
	--axr_logic.set_new_scheme_and_logic(npc,"beh","beh@base","logic",nil,"scripts\\beh_companion.ltx")
	--alun_utils.debug_write("Inserted %s into actor squad",npc:name())
end

function remove_from_actor_squad(npc)
	local squad = get_object_squad(npc)
	if (squad) then 
		squad.scripted_target = nil
	end 
	
	local se_obj = alife():object(npc:id())
	if not (se_obj) then 
		return 
	end
	
	utils.se_obj_save_var(se_obj.id,se_obj:name(),"companion",nil)
	utils.se_obj_save_var(se_obj.id,se_obj:name(),"companion_cannot_dismiss",nil)
	utils.se_obj_save_var(se_obj.id,se_obj:name(),"companion_cannot_teleport",nil)
			
	npc:disable_info_portion("npcx_is_companion")
	npc:disable_info_portion("npcx_beh_cannot_dismiss")
	
	axr_logic.restore_scheme_and_logic(npc)

	local count = 0
	for i=1,max_actor_squad_size do
		local c = utils.load_var(db.actor,"companion_"..i,nil)
		if (c == npc:id()) then
			utils.save_var(db.actor,"companion_"..i,nil)
		end
		count = count + 1
	end
	if (get_companion_count() < 1) then
		db.actor:disable_info_portion("axr_has_companion")
	end
end

function can_join_actor(npc)
	local squad = get_object_squad(npc)
	if squad ~= nil and squad:commander_id() ~= npc:id() then
		return false
	end

	if (get_companion_count() + alun_utils.get_squad_count(npc) <= max_actor_squad_size) then
		return true
	end

	return false
end

function set_companion_allow_teleport(npc)
	local se_obj = alife():object(npc:id())
	if not (se_obj) then 
		return 
	end
	utils.se_obj_save_var(se_obj.id,se_obj:name(),"companion_cannot_teleport",nil)
end 

function set_companion_disable_teleport(npc)
	local se_obj = alife():object(npc:id())
	if not (se_obj) then 
		return 
	end
	utils.se_obj_save_var(se_obj.id,se_obj:name(),"companion_cannot_teleport",true)
end 

function set_companion_combat_type_camper(npc)
	npc:disable_info_portion("npcx_beh_combat_tactics_monolith")
	npc:give_info_portion("npcx_beh_combat_tactics_camper")
end

function set_companion_combat_type_monolith(npc)
	npc:disable_info_portion("npcx_beh_combat_tactics_camper")
	npc:give_info_portion("npcx_beh_combat_tactics_monolith")
end

function set_companion_combat_type_default(npc)
	npc:disable_info_portion("npcx_beh_combat_tactics_monolith")
	npc:disable_info_portion("npcx_beh_combat_tactics_camper")
end

function set_companion_to_wait_state(npc)
	npc:give_info_portion("npcx_beh_wait")
	utils.save_var(npc,"fight_from_point",npc:level_vertex_id())
end

function set_companion_to_follow_state(npc)
	npc:disable_info_portion("npcx_beh_wait")
	npc:disable_info_portion("npcx_beh_hide_in_cover")
	npc:disable_info_portion("npcx_beh_patrol_mode")
	utils.save_var(npc,"fight_from_point",nil)
end

function set_companion_to_attack_state(npc)
	npc:disable_info_portion("npcx_beh_ignore_combat")
	npc:disable_info_portion("npcx_beh_ignore_actor_enemies")
end

function set_companion_to_ignore_combat_state(npc)
	npc:give_info_portion("npcx_beh_ignore_combat")
	npc:give_info_portion("npcx_beh_ignore_actor_enemies")
end

function set_companion_to_attack_only_actor_combat_enemy_state(npc)
	npc:give_info_portion("npcx_beh_ignore_combat")
	npc:disable_info_portion("npcx_beh_ignore_actor_enemies")
end

function set_companion_to_stealth_substate(npc)
	npc:give_info_portion("npcx_beh_substate_stealth")
end

function set_companion_to_relax_substate(npc)
	npc:give_info_portion("npcx_beh_substate_relax")
end

function set_companion_to_default_substate(npc)
	npc:disable_info_portion("npcx_beh_substate_stealth")
	npc:disable_info_portion("npcx_beh_substate_relax")
end

function switch_companion_distance(npc)
	if ( npc:has_info("npcx_beh_distance_far") ) then
		npc:disable_info_portion("npcx_beh_distance_far")
	else
		npc:give_info_portion("npcx_beh_distance_far")
	end
end

function set_companion_hide_in_cover(npc)
	npc:give_info_portion("npcx_beh_hide_in_cover")
	npc:disable_info_portion("npcx_beh_wait")
end

function switch_companion_patrol_mode(npc)
	if ( npc:has_info("npcx_beh_patrol_mode") ) then
		npc:disable_info_portion("npcx_beh_patrol_mode")
	else
		npc:give_info_portion("npcx_beh_patrol_mode")
	end
end

function switch_companion_gather_items(npc)
	if ( npc:has_info("npcx_beh_gather_items") ) then
		SetHudMsg(game.translate_string("st_disable_looting"),8)
		npc:disable_info_portion("npcx_beh_gather_items")
	else
		SetHudMsg(game.translate_string("st_enable_looting"),8)
		npc:give_info_portion("npcx_beh_gather_items")
	end
end

function switch_companion_loot_corpses(npc)
	if ( npc:has_info("npcx_beh_loot_corpses") ) then
		npc:disable_info_portion("npcx_beh_loot_corpses")
	else
		npc:give_info_portion("npcx_beh_loot_corpses")
	end
end

function companion_remove_waypoints(npc)
	npc:disable_info_portion("npcx_beh_patrol_mode")
	local i = 1
	local p = utils.se_obj_load_var(npc:id(),npc:name(),"pathpoint"..i)--utils.load_var(npc,"pathpoint"..tostring(i))
	while p do 
		utils.se_obj_save_var(npc:id(),npc:name(),"pathpoint"..i,nil)--utils.save_var(npc,"pathpoint"..tostring(i),nil)
		i = i + 1
		p = utils.se_obj_load_var(npc:id(),npc:name(),"pathpoint"..i)--utils.load_var(npc,"pathpoint"..tostring(i))
	end
end

function companion_add_waypoints(npc,pos)
	local i = 1
	local p = utils.se_obj_load_var(npc:id(),npc:name(),"pathpoint"..i)--utils.load_var(npc,"pathpoint"..tostring(i))
	while p do 
		i = i + 1
		p = utils.se_obj_load_var(npc:id(),npc:name(),"pathpoint"..i)--utils.load_var(npc,"pathpoint"..tostring(i))
	end
	local pos = db.actor:position()
	local s = "5000,patrol | pos:"..pos.x..","..pos.y..","..pos.z
	utils.se_obj_load_var(npc:id(),npc:name(),"pathpoint"..i,s)--utils.save_var(npc,"pathpoint"..tostring(i),s)
end

function cycle_companions_combat_mode()
	local t = {"set_companion_to_attack_state","set_companion_to_ignore_combat_state","set_companion_to_attack_only_actor_combat_enemy_state"}
	if (_current_combat_mode+1 > #t) then 
		_current_combat_mode = 1
	else 
		_current_combat_mode = _current_combat_mode + 1
	end
	
	SetHudMsg(game.translate_string("st_"..t[_current_combat_mode]),8)
	
	local f = this[t[_current_combat_mode]]
	if (f) then 
		for id,squad in pairs(companion_squads) do 
			if (squad and squad.commander_id) then
				for k in squad:squad_members() do
					if not (xrs_kill_wounded.hostage_list[k.id]) then
						local member = db.storage[k.id] and db.storage[k.id].object
						if (member and member:alive()) then
							f(member)
						end
					end
				end
			end
		end
	end
end 

function cycle_companions_move_mode()
	local t = {"set_companion_to_wait_state","set_companion_to_follow_state"}
	
	if (_current_move_mode+1 > #t) then 
		_current_move_mode = 1
	else 
		_current_move_mode = _current_move_mode + 1
	end
	
	SetHudMsg(game.translate_string("st_"..t[_current_move_mode]),8)
	
	local f = this[t[_current_move_mode]]
	if (f) then 
		for id,squad in pairs(companion_squads) do 
			if (squad and squad.commander_id) then
				for k in squad:squad_members() do
					if not (xrs_kill_wounded.hostage_list[k.id]) then
						st = db.storage[k.id]
						if (k.id == squad:commander_id()) then 
							if (st and st.beh) then 
								st.beh.rally_lvid = nil
							end
						end
						local member = st and st.object
						if (member and member:alive()) then
							f(member)
						end
					end
				end
			end
		end
	end
end 

function move_to_point(p)
	local lvid
	if (p==1) then 
		SetHudMsg(game.translate_string("st_hold_then_release"),8)
		--_draw_part = particles_object("weapons\\light_signal")
		_draw_part = particles_object("_samples_particles_\\flash_light")
		--_draw_part = particles_object("static\\net_base_blue")
	elseif (p==2) then
		if (_draw_part) then 
			local r = level.get_target_dist and level.get_target_dist()
			if (r) then
				lvid = level.vertex_in_direction(level.vertex_id(device().cam_pos),device().cam_dir,r)
				local pos = level.vertex_position(lvid)
				--if not(_draw_part:playing()) then
					_draw_part:play_at_pos(vector():set(pos.x,pos.y-0.5,pos.z))
				--else 
				--	_draw_part:move_to(pos,pos)
				--end
			end
		end	
	else
		if (_draw_part) then
			_draw_part:stop()
			_draw_part = nil
		end
		local r = level.get_target_dist and level.get_target_dist()
		if (r) then
			lvid = level.vertex_in_direction(level.vertex_id(device().cam_pos),device().cam_dir,r)
			if (lvid) then
				_current_move_mode = 1
				SetHudMsg(game.translate_string("st_move_to_point"),8)
				for id,squad in pairs(companion_squads) do 
					if (squad and squad.commander_id) then
						for k in squad:squad_members() do
							st = db.storage[k.id]
							local member = st and st.object
							if (member and member:alive()) then
								set_companion_to_follow_state(member)
								utils.save_var(member,"fight_from_point",lvid)
							end
							if (k.id == squad:commander_id() and not xrs_kill_wounded.hostage_list[k.id]) then 
								if (st and st.beh) then 
									st.beh.rally_lvid = lvid
								end
							end
						end
					end
				end
			end
		end
	end
end