function bind(obj)
    obj:bind_object(item_binder(obj))
end
--------------------------------------------------------------------------------
-- Class "item_binder"
--------------------------------------------------------------------------------
class "item_binder" (object_binder)
-- Class constructor
function item_binder:__init(obj) super(obj)

end
-- Class update
function item_binder:update(delta)
    object_binder.update(self, delta)
end
-- Reload object
function item_binder:reload(section)
    object_binder.reload(self, section)
end
-- Reinitialize object
function item_binder:reinit()
    object_binder.reinit(self)
end
-- Net spawn
function item_binder:net_spawn(sobject)
    if not(object_binder.net_spawn(self, sobject)) then
        return false
    end
	if (sobject.remaining_uses and sobject.remaining_uses > 0 and sobject.remaining_uses <= self.object:get_max_uses()) then
		--printf("set remaining_uses on net spawn %s",sobject.remaining_uses)
		self.object:set_remaining_uses(tonumber(sobject.remaining_uses) or 1)
	end
    return true
end
-- Net destroy
function item_binder:net_destroy()
	object_binder.net_destroy(self)
end
-- Save
function item_binder:save(stpk)
	object_binder.save(self, stpk)
end
-- Load
function item_binder:load(stpk)
	object_binder.load(self, stpk)
end