local sim_objects_registry = nil
local props_ini = ini_file("misc\\simulation_objects_props.ltx")
config = ini_file_ex("ai_tweaks\\simulation_objects.ltx")

local ALLOW_NPC_LEVEL_TRANSITION = true


-- setup default squad behaviors
local default_squad_behaviour = {	
	["actor"]			= 0,
	["all"]				= 1,
	["base"] 			= 1,
	["lair"]			= 0,
	["resource"] 		= 2,
	["squad"] 			= 0,
	["surge"]			= 3,
	["territory"]		= 1
}

local default_monster_behaviour = {	
	["actor"]			= 0,
	["base"] 			= 0,
	["lair"]			= 1,
	["monster"]			= 1,
	["resource"] 		= 0,
	["squad"] 			= 0,
	["surge"]			= 0,
	["territory"]		= 1
}

class "simulation_objects_registry"
function simulation_objects_registry:__init()
	self.objects = {}
end

function simulation_objects_registry:register(obj)
	self:get_props(obj)
	self:update_avaliability(obj)
end

function simulation_objects_registry:update_avaliability(obj)
	if (obj:clsid() == clsid.online_offline_group_s) then 
		return
	end 
	
	if (obj:sim_available() and xr_logic.pick_section_from_condlist(alife():actor(), obj, obj.sim_avail) == "true") then
		self.objects[obj.id] = obj
	else
		self.objects[obj.id] = nil
	end
end

function simulation_objects_registry:get_props(obj)
	local cls = obj:clsid()
	if (cls == clsid.online_offline_group_s) then 
		return
	end
	
	obj.props = {}
	
	local props_section
	if (cls == clsid.online_offline_group_s) then
		if (props_ini:section_exist(obj:section_name())) then 
			props_section = obj:section_name()
		else 
			props_section = "default_squad"
		end
	elseif (cls == clsid.script_actor) then 
		props_section = "actor"
	else 
		if (props_ini:section_exist(obj:name())) then 
			props_section = obj:name()
		else 
			props_section = "default"
		end
	end

	if not (props_ini:section_exist(props_section)) then 
		printf("invalid section for props_ini %s",props_section)
		return
	end
	
	local n = props_ini:line_count(props_section)
	local result, prop_name, prop_condlist
	local tonumber = tonumber
	for j=0,n-1 do
		result, prop_name, prop_condlist = props_ini:r_line_ex(props_section,j,"","")
		if prop_name == "sim_avail" then
			obj.sim_avail = xr_logic.parse_condlist(nil, "simulation_object", "sim_avail", prop_condlist)
		else
			obj.props[prop_name] = tonumber(prop_condlist)
		end
	end
	if obj.sim_avail == nil then
		obj.sim_avail = xr_logic.parse_condlist(nil, "simulation_object", "sim_avail", "true")
	end
end

function simulation_objects_registry:unregister(obj)
	self.objects[obj.id] = nil
end

function get_sim_obj_registry()
	if sim_objects_registry == nil then
		sim_objects_registry = simulation_objects_registry()
	end
	return sim_objects_registry
end

--***********************************************************************************************
--*										SIMULATION_LOCAL_FUNCTIONS								*
--***********************************************************************************************


function sim_dist_to(obj1 , obj2)
	local pos1,lv1,gv1 = obj1:get_location()
	local pos2,lv2,gv2 = obj2:get_location()
	return utils.graph_distance(gv1, gv2)
end

local function evaluate_prior_by_dist(target, squad)
	local dist = sim_dist_to(target, squad)
	if dist < 1 then
		dist = 1
	end
	return 1 + 1/dist
end

function is_on_the_same_level(obj1, obj2)
	local gg = game_graph()
	return obj1 and obj2 and gg:vertex(obj1.m_game_vertex_id):level_id() == gg:vertex(obj2.m_game_vertex_id):level_id() or false
end

function evaluate_prior(target, squad)

	local sim = alife()
	local prior = 5

	if (target:clsid() == clsid.script_actor) then
		if not (is_on_the_same_level(target, squad)) then
			return 0
		end

		if not (target:target_precondition(squad)) then
			return 0
		end

	elseif (target:clsid() == clsid.online_offline_group_s) then

		if (squad.id == target.id) then
			return 0
		end

		if (not is_on_the_same_level(sim:actor(), squad)) then
			return 0
		end

		-- If target squad is in safe zone, ignore them.
		if (xr_combat_ignore.safe_zone_npcs[squad.id]) then
			return 0
		end

		if (xr_combat_ignore.safe_zone_npcs[target.id]) then
			return 0
		end

		-- Prevent cluster-fucks
		local target_of_my_target = target.assigned_target_id and sim:object(target.assigned_target_id)
		if (target_of_my_target and target_of_my_target:clsid() == clsid.online_offline_group_s) then
			return 0
		end

		if not (target:target_precondition(squad)) then
			return 0
		end

	elseif (target:clsid() == clsid.smart_terrain) then

		if (target.disabled) then
			return 0
		end

		if (SIMBOARD.smarts[target.id] == nil or SIMBOARD.smarts[target.id].squads == nil) then
			return 0
		end

		-- Level travel
		if not (is_on_the_same_level(target, squad)) then
			-- if (is_squad_monster[squad.player_id]) then 
				-- return 0 
			-- end
			
			if not (ALLOW_NPC_LEVEL_TRANSITION) then
				return 0
			end
		end
	end

	-- priorize target based on target props
	local target_koeff = target.props[squad.player_id]
	if (target_koeff ~= nil) then 
		prior = prior + (1*target_koeff)
	end
	
	if (is_squad_monster[squad.player_id]) then 
		for k,v in pairs (default_monster_behaviour) do
			target_koeff = target.props[k] or 0
			prior = prior + (v*target_koeff)
		end
	else 
		for k,v in pairs (default_squad_behaviour) do
			target_koeff = target.props[k] or 0
			prior = prior + (v*target_koeff)
		end
	end
	
	return prior*evaluate_prior_by_dist(target, squad)
end