-- File:        UI_MAIN_MENU.SCRIPT
-- Description: Load Dialog for STALKER
-- Created:     28.10.2004
-- Last edit:	10.01.2015
-- Copyright:   2004 GSC Game World
-- Author:      Serhiy Vynnychenko (narrator@gsc-game.kiev.ua)
-- Version:     0.9

local SKIP_FACTION_SELECTION = false -- TRUE to disable faction selection menu and start normally

class "main_menu" (CUIScriptWnd)
function main_menu:__init() super()
	math.randomseed(os.time())
	self.mbox_mode = 0
	self.main_xml = CScriptXmlInit()
	self.main_xml:ParseFile("ui_mm_main.xml")

	SendScriptCallback("main_menu_on_init", self)

    self:InitControls()

    self:InitCallBacks()
	
	RegisterScriptCallback("on_localization_change", self)
	
	if not (level.present()) then
		xrs_debug_tools.on_game_start()
	end
end

function main_menu:Update()
	CUIScriptWnd.Update(self)
	
	if self.gamepad_legend then
		local text_back		= self:GetStatic("gp_back")	
		if text_back then
			text_back:Show((level.present()	and ((db.actor ~= nil)and(db.actor:alive())
			or not IsGameTypeSingle())) or 
			self.shniaga:GetPage() == CUIMMShniaga.epi_new_game
			)
		end

		local text_select		= self:GetStatic("gp_select")	
		if text_select then
			if self.shniaga:GetPage() ~= CUIMMShniaga.epi_new_game then
				text_select:SetTextST("ui_mm_select")
			else
				text_select:SetTextST("ui_mm_select_difficulty")
			end
		end
	end
	
	SendScriptCallback("main_menu_update", self)
	-- Warning messages timer 
	if (self.msg_wnd_timer) then 
		self.msg_wnd_timer = self.msg_wnd_timer - 1
		if (self.msg_wnd_timer <= 0) then
			self.msg_wnd_timer = nil
			self.msg_wnd:Show(false)
		end
	end
end

function main_menu:__finalize()
end

function main_menu:InitControls()
	self:SetWndRect	(Frect():set(0,0,1024,768))

    self.main_xml:InitStatic("background", self)
    self.shniaga = self.main_xml:InitMMShniaga("shniaga_wnd", self)

	self.message_box = CUIMessageBoxEx()
	self:Register(self.message_box, "msg_box")

	local _ver = self.main_xml:InitStatic("static_version",self)
	local mm						= _G.main_menu.get_main_menu()
	_ver:TextControl():SetText("Call of Chernobyl ver. " .. (_G.GAME_VERSION))
	
	-- IX-Ray start
	if self.main_xml:NodeExist("english_lang", 0) then
		self.eng_lang_btn = self.main_xml:Init3tButton("english_lang", self)
		self:Register(self.eng_lang_btn, "english_lang")
	end
	
	if self.main_xml:NodeExist("russian_lang", 0) then
		self.ru_lang_btn = self.main_xml:Init3tButton("russian_lang", self)
		self:Register(self.ru_lang_btn, "russian_lang")
	end
	
	if self.main_xml:NodeExist("gamepad_legend", 0) then
		self.gamepad_legend = self.main_xml:InitGamepadLegend("gamepad_legend", self)
		self:Register(self.gamepad_legend, "gamepad_legend")
	end
	
	if is_cop() then
		gamepad_led(255, 63, 0)
	elseif is_cs() then
		gamepad_led(191, 255, 255)
	else
		gamepad_led(255, 255, 0)
	end
	SendScriptCallback("main_menu_on_init_controlls", self)
	-- IX-Ray end

	-- Message Window 
	self.msg_wnd = self.main_xml:InitFrame("msg_wnd:background",self)
	self.msg_wnd:SetAutoDelete(false)
	self.msg_wnd_text = self.main_xml:InitTextWnd("msg_wnd:text",self.msg_wnd)
	self.msg_wnd_text:SetTextAlignment(2)
	
	self.msg_wnd:Show(false)
	self.msg_wnd:SetColor(GetARGB(255,0,0,0))
	
	action_repeaters():Register(self, key_bindings.kUI_DOWN,0,0)
	action_repeaters():Register(self, key_bindings.kUI_UP,0,0)
	action_repeaters():Register(self, key_bindings.kUI_LEFT,0,0)
	action_repeaters():Register(self, key_bindings.kUI_RIGHT,0,0)
end

function main_menu:Show(f)
	self.shniaga:SetVisibleMagnifier(f)
end


function main_menu:InitCallBacks()
	-- new game
	self:AddCallback("btn_novice",		ui_events.BUTTON_CLICKED,				self.OnButton_new_novice_game,		self)
	self:AddCallback("btn_stalker",		ui_events.BUTTON_CLICKED,				self.OnButton_new_stalker_game,		self)
	self:AddCallback("btn_veteran",		ui_events.BUTTON_CLICKED,				self.OnButton_new_veteran_game,		self)
	self:AddCallback("btn_master",		ui_events.BUTTON_CLICKED,				self.OnButton_new_master_game,		self)
	self:AddCallback("btn_spawn",		ui_events.BUTTON_CLICKED,				self.OnButton_load_spawn,			self)
	-- options
	self:AddCallback("btn_options",     ui_events.BUTTON_CLICKED,				self.OnButton_options_clicked,		self)
    -- AtmosFear options
	self:AddCallback("btn_af_options",  ui_events.BUTTON_CLICKED,				self.OnButton_af_options_clicked,	self)
	-- end AtmosFear options
	-- load
	self:AddCallback("btn_load",        ui_events.BUTTON_CLICKED,				self.OnButton_load_clicked,			self)
	-- save
	self:AddCallback("btn_save",		ui_events.BUTTON_CLICKED,				self.OnButton_save_clicked,			self)
	-- multiplayer
	if (IsSupportMP()) then -- IX-Ray: Optional multiplayer check
		self:AddCallback("btn_multiplayer", ui_events.BUTTON_CLICKED,				self.OnButton_multiplayer_clicked,	self)
	end
	-- quit
	self:AddCallback("btn_quit",		ui_events.BUTTON_CLICKED,				self.OnButton_quit_clicked,			self)
	self:AddCallback("btn_quit_to_mm",	ui_events.BUTTON_CLICKED,				self.OnButton_disconnect_clicked,	self)
	self:AddCallback("btn_ret",			ui_events.BUTTON_CLICKED,				self.OnButton_return_game,			self)
	self:AddCallback("btn_lastsave",	ui_events.BUTTON_CLICKED,				self.OnButton_last_save,			self)
	self:AddCallback("btn_credits",		ui_events.BUTTON_CLICKED,				self.OnButton_credits_clicked,		self)
	
	-- IX-Ray start
	self:AddCallback("english_lang",	ui_events.BUTTON_CLICKED,				self.OnBtnEnglish,			self)
	self:AddCallback("russian_lang",	ui_events.BUTTON_CLICKED,				self.OnBtnRussian,			self)
	-- IX-Ray end
	
	-- message box
	self:AddCallback("msg_box",     ui_events.MESSAGE_BOX_OK_CLICKED,		self.OnMsgOk,						self)
	self:AddCallback("msg_box",     ui_events.MESSAGE_BOX_CANCEL_CLICKED,	self.OnMsgCancel,					self)
	self:AddCallback("msg_box",     ui_events.MESSAGE_BOX_YES_CLICKED,		self.OnMsgYes,						self)
	self:AddCallback("msg_box",     ui_events.MESSAGE_BOX_NO_CLICKED,		self.OnMsgNo,						self)
	self:AddCallback("msg_box",			ui_events.MESSAGE_BOX_QUIT_GAME_CLICKED,self.OnMessageQuitGame,				self)
	self:AddCallback("msg_box",			ui_events.MESSAGE_BOX_QUIT_WIN_CLICKED,	self.OnMessageQuitWin,				self)

	self:Register(self, "self")
	self:AddCallback("self",	ui_events.MAIN_MENU_RELOADED, self.OnMenuReloaded, self)
	
	SendScriptCallback("main_menu_on_init_callbacks", self)
end
function main_menu:OnMsgOk()
	if (self.mbox_mode == 2) then
		local console = get_console()
		console:execute("quit")
	end
	self.mbox_mode = 0
end

function main_menu:OnMsgCancel()
	self.mbox_mode = 0
end

function main_menu:OnMsgYes()

	if 	self.mbox_mode == 1 then
		self:LoadLastSave()
	end

	self.mbox_mode = 0
end

function main_menu:OnMsgNo()
	self.mbox_mode = 0
end

function main_menu:LoadLastSave()
	local					console = get_console()
	console:execute			("main_menu off")
	console:execute			("load_last_save")
end

function main_menu:OnButton_last_save()
	if ( alife() == nil) then
		self:LoadLastSave	()
		return
	end

	if ( (db.actor ~= nil) and (db.actor:alive() == false) ) then
		self:LoadLastSave	()
		return
	end

	self.mbox_mode			= 1
	self.message_box:InitMessageBox	("message_box_confirm_load_save")
	self.message_box:ShowDialog(true)
end

function main_menu:OnButton_credits_clicked()
--	local console = get_console()
--	console:execute("main_menu off")
	game.start_tutorial("credits_seq")
end

function main_menu:OnButton_quit_clicked()
	self.message_box:InitMessageBox("message_box_quit_windows")
	self.message_box:ShowDialog(true)
end


function main_menu:OnButton_disconnect_clicked()
	self.message_box:InitMessageBox("message_box_quit_game")

	if (level.game_id() ~= 1) then
		self.message_box:SetText("ui_mm_disconnect_message")	-- MultiPlayer
	else
		self.message_box:SetText("ui_mm_quit_game_message")		-- SinglePlayer
	end
	self.message_box:ShowDialog(true)
end

function main_menu:OnMessageQuitGame()
	local console = get_console()
	console:execute("disconnect")
end

function main_menu:OnMessageQuitWin()
	local console = get_console()
	console:execute("quit")
end

function main_menu:OnButton_return_game()
	local console = get_console()
	console:execute("main_menu off")
	SendScriptCallback("main_menu_on_quit", self)
end

function main_menu:OnButton_new_novice_game()
	local console = get_console()
	console:execute("g_game_difficulty gd_novice")
	self:ShowFactionUI()
end

function main_menu:OnButton_new_stalker_game()
	local console = get_console()
	console:execute("g_game_difficulty gd_stalker")
	self:ShowFactionUI()
end

function main_menu:OnButton_new_veteran_game()
	local console = get_console()
	console:execute("g_game_difficulty gd_veteran")
	self:ShowFactionUI()
end

function main_menu:OnButton_new_master_game()
	local console = get_console()
	console:execute("g_game_difficulty gd_master")
	self:ShowFactionUI()
end

local faction_ui
function main_menu:ShowFactionUI()
	if (SKIP_FACTION_SELECTION) then 
		self:StartGame() 
		return 
	end
	if not (faction_ui) then
		faction_ui = ui_mm_faction_select and ui_mm_faction_select.faction_ui(self)
	end

	if (faction_ui) then
		faction_ui:ShowDialog(true)
		self:HideDialog()
		self:Show(false)
	end
end 

function main_menu:StartGame()
	local console = get_console()

	if (alife() ~= nil) then
		console:execute	("disconnect")
	end
	device():pause(false)
	console:execute("start server(all/single/alife/new) client(localhost)")
	console:execute("main_menu off")
end

function main_menu:OnButton_load_spawn()
	if self.spawn_dlg == nil then
		self.spawn_dlg = ui_spawn_dialog.spawn_dialog()
		self.spawn_dlg.owner = self
	end

	self.spawn_dlg:ShowDialog(true)
	self:HideDialog()
	self:Show(false)
end

function main_menu:OnButton_save_clicked()
	if self.save_dlg == nil then
		self.save_dlg = ui_save_dialog.save_dialog()
		self.save_dlg.owner = self
	end

	self.save_dlg:FillList()
	self.save_dlg:ShowDialog(true)
	self:HideDialog()
	self:Show(false)
end

function main_menu:OnButton_options_clicked()
	if self.opt_dlg == nil then
		self.opt_dlg = ui_mm_opt_main.options_dialog()
		self.opt_dlg.owner = self
	end

	self.opt_dlg:SetCurrentValues()
	self.opt_dlg:ShowDialog(true)
	self:HideDialog()
	self:Show(false)
end

-- AtmosFear options dialog
function main_menu:OnButton_af_options_clicked()
	if self.af_opt_dlg == nil then
		self.af_opt_dlg = atmosfear_options.af_options_dialog()
		self.af_opt_dlg.owner = self
	end

	self.af_opt_dlg:SetCurrentValues()
	self.af_opt_dlg:ShowDialog(true)
	self:HideDialog()
	self:Show(false)
end
-- End AtmosFear options dialog

-- IX-Ray start
function main_menu:OnBtnEnglish()
	local console = get_console()
	console:execute("language eng")
end

function main_menu:OnBtnRussian()
	local console = get_console()
	console:execute("language rus")
end
-- IX-Ray end

function main_menu:OnButton_load_clicked()
	if self.load_dlg ==nil then
		self.load_dlg = ui_load_dialog.load_dialog()
		self.load_dlg.owner = self
	end

	self.load_dlg:FillList()
	self.load_dlg:ShowDialog(true)
	self:HideDialog()
	self:Show(false)
end

function main_menu:OnButton_multiplayer_clicked()
	if not(self.mp_dlg) then
        self.mp_dlg = ui_mp_main.mp_main()
        self.mp_dlg.owner = self
		self.mp_dlg:OnRadio_NetChanged()
    end
    self.mp_dlg:UpdateControls()
    self.mp_dlg:ShowDialog(true)

    self:HideDialog()
	self:Show(false)
end

function main_menu:Dispatch(cmd, param)  --virtual function
	if cmd == 1 then -- new
		self:ReloadGamepadLegend()
	elseif cmd == 2 then
		self:OnButton_multiplayer_clicked()
	end
	return true
end

function main_menu:OnKeyboard(dik, keyboard_action)  --virtual function
	CUIScriptWnd.OnKeyboard(self,dik,keyboard_action)
	
	local hold = false
	if GetModule("ixr_options") and GetModule("ixr_options").on_press_key(dik, keyboard_action, hold) then -- вернёт true если было совпадение по кнопке с опциями
		return true
	end
	
	local bind = dik_to_bind(dik)
	local console = get_console()
	
	SendScriptCallback("main_menu_on_keyboard", dik, keyboard_action, self, level.present())

	if keyboard_action == ui_events.WINDOW_KEY_PRESSED then
		if dik == DIK_keys.DIK_ESCAPE then
			if level.present() and
				(	((db.actor ~= nil)and(db.actor:alive())) or
					(false==IsGameTypeSingle())
				) then
				self.OnButton_return_game()                      --' xStream 02.2008
				-- console:execute("main_menu off")							   --' xStream 02.2008
			end
		end

--		if dik == DIK_keys.DIK_S then
--			self:OnButton_load_spawn()

--		else
		if dik == DIK_keys.DIK_Q then
			self:OnMessageQuitWin()
		end

	end

	return true
end

function main_menu:OnKeyboardHold(dik)  --virtual function
	if GetModule("ixr_options") and GetModule("ixr_options").on_press_key(dik, nil, true) then -- вернёт true если было совпадение по кнопке с опциями
		return true
	end

	return true
end

function main_menu:OnGamepadKey(dik, gamepad_action)  --virtual function
	CUIScriptWnd.OnGamepadKey(self,dik,gamepad_action)

	if GetModule("ixr_options") and GetModule("ixr_options").on_gamepad_key(dik, gamepad_action) then -- вернёт true если было совпадение по кнопке с опциями
		return true
	end
	
	local bind = dik_to_bind(dik)
	local bindUI = dik_to_bind(dik, action_groups.agUIGeneral)
	local console = get_console()
	
	if gamepad_action == ui_events.WINDOW_KEY_PRESSED then
		if bind == key_bindings.kQUIT or bindUI == key_bindings.kUI_BACK then
			if level.present() and
				(	((db.actor ~= nil)and(db.actor:alive())) or
					(false==IsGameTypeSingle())
				) then
				self.OnButton_return_game()                      --' xStream 02.2008
			end
		elseif bindUI == key_bindings.kUI_ACTION_2 then
			if GetModule("ixr_options") then
				GetModule("ixr_options").on_btn_options_ixr_clicked()
			end
		end

	end

	return true
end

function main_menu:OnGamepadKeyHold(dik)  --virtual function
	CUIScriptWnd.OnGamepadKeyHold(self,dik)
	
	if GetModule("ixr_options") and GetModule("ixr_options").on_gamepad_key_hold(dik, nil) then -- вернёт true если было совпадение по кнопке с опциями
		return true
	end
	
	return false
end

function main_menu:OnMenuReloaded()
	self:OnButton_options_clicked()
	self.opt_dlg:OnMenuReloaded()
end

function main_menu:ReloadGamepadLegend()
	if self.gamepad_legend then
		self.gamepad_legend:ReloadLegend()
	end
	if self.save_dlg then
		self.save_dlg.gamepad_legend:ReloadLegend()
	end
	if self.load_dlg then
		self.load_dlg.gamepad_legend:ReloadLegend()
	end
	if self.opt_dlg then
		self.opt_dlg.gamepad_legend:ReloadLegend()
		if self.opt_dlg.dlg_controller_layout then
			self.opt_dlg.dlg_controller_layout:ReloadGamepadTextures()
		end
	end
end

function main_menu:SetMsg(text,tmr)
	if (text == "") then 
		return 
	end
	self.msg_wnd:Show(true)
	self.msg_wnd_text:SetText(text)
	self.msg_wnd_text:AdjustHeightToText()
	self.msg_wnd_text:SetWndSize(vector2():set(1024,self.msg_wnd_text:GetHeight()+10))
	self.msg_wnd_text:SetWndPos(vector2():set(0,20))
	
	self.msg_wnd:SetWndSize(vector2():set(1024,self.msg_wnd_text:GetHeight()+44))
	self.msg_wnd:SetWndPos(vector2():set(0,80))

	self.msg_wnd_timer = 100*tmr
end
