// Generated by xrTiramisuMaterialCore. Do not edit.
void EvaluateMaterial(
    in MaterialContext Context,
    in MaterialParameters Parameters,
    out MaterialInputs Result)
{
    Result.BaseColor = float3(1.0f, 1.0f, 1.0f);
    Result.Normal = Context.WorldNormal;
    Result.Roughness = 0.5f;
    Result.Metallic = 0.0f;
    Result.AmbientOcclusion = 1.0f;
    Result.Emissive = float3(0.0f, 0.0f, 0.0f);
    Result.Opacity = 1.0f;
    Result.OpacityMask = 1.0f;
    Result.WorldPositionOffset = float3(0.0f, 0.0f, 0.0f);
#line 1 "material-node/3d584a86-b582-4b55-8609-6dff1856e5d4"
    Result.BaseColor = Parameters.P_190412be_3265_452a_94db_d4ee1a545fc8;
}
