#pragma once

enum ERHI_API_LAYER
{
	D3D11,
	D3D9,

	NOT_CREATED = -1
};

enum class ERTColor
{
	Transparent,
	Gray,
	Black
};

enum class ERHI_USAGE
{
	USAGE_DEFAULT = 0,
	USAGE_IMMUTABLE = 1,
	USAGE_DYNAMIC = 2,
	USAGE_STAGING = 3
};

enum class ERHI_DSV_DIMENSION
{
	UNKNOWN = 0,
	TEXTURE1D = 1,
	TEXTURE1DARRAY = 2,
	TEXTURE2D = 3,
	TEXTURE2DARRAY = 4,
	TEXTURE2DMS = 5,
	TEXTURE2DMSARRAY = 6
};

enum class ERHI_VIEW_DIMENSION
{
	Texture2D,
	Texture3D,
	Buffer
};

enum class ERHI_BUFFER_TYPE
{
	VERTEX,
	INDEX,
	CONSTANT,
	STRUCTURED
};

enum class ERHI_BUFFER_MAP
{
	READ,
	WRITE,
	WRITE_DISCARD,
	WRITE_NO_OVERWRITE,
	READ_AND_WRITE
};

enum ERHI_CPU_ACCESS_FLAG
{
	ERHI_CPU_ACCESS_FLAG_NONE,
	ERHI_CPU_ACCESS_FLAG_WRITE,
	ERHI_CPU_ACCESS_FLAG_READ
};

enum ERHI_BIND_FLAG
{
	VERTEX_BUFFER = 0x1L,
	INDEX_BUFFER = 0x2L,
	CONSTANT_BUFFER = 0x4L,
	SHADER_RESOURCE = 0x8L,
	STREAM_OUTPUT = 0x10L,
	RENDER_TARGET = 0x20L,
	DEPTH_STENCIL = 0x40L,
	UNORDERED_ACCESS = 0x80L,
	DECODER = 0x200L,
	VIDEO_ENCODER = 0x400L,

	NOT_SET = 0
};
ENUM_CLASS_FLAGS(ERHI_BIND_FLAG);

enum class ERHI_RTV_DIMENSION
{
	UNKNOWN = 0,
	BUFFER = 1,
	TEXTURE1D = 2,
	TEXTURE1DARRAY = 3,
	TEXTURE2D = 4,
	TEXTURE2DARRAY = 5,
	TEXTURE2DMS = 6,
	TEXTURE2DMSARRAY = 7,
	TEXTURE3D = 8
};

enum class ERHI_SHADER_TYPE
{
	PS,
	VS,
	GS,
	HS,
	DS,
	CS,
};

enum class ERHI_CLEAR_TARGET
{
	DEPTH = 1 << 0,
	STENCIL = 1 << 1
};
ENUM_CLASS_FLAGS(ERHI_CLEAR_TARGET);

enum class ERHI_INPUT_CLASSIFICATION
{
	VERTEX_DATA,
	INSTANCE_DATA
};

enum class ERHI_RESOURCE_DIMENSION
{
	UNKNOWN = 0,
	BUFFER = 1,
	TEXTURE1D = 2,
	TEXTURE2D = 3,
	TEXTURE3D = 4
};

enum class ERHI_SRV_DIMENSION
{
	UNKNOWN = 0,
	BUFFER = 1,
	TEXTURE1D = 2,
	TEXTURE1DARRAY = 3,
	TEXTURE2D = 4,
	TEXTURE2DARRAY = 5,
	TEXTURE2DMS = 6,
	TEXTURE2DMSARRAY = 7,
	TEXTURE3D = 8,
	TEXTURECUBE = 9,
	TEXTURECUBEARRAY = 10,
	BUFFEREX = 11
};

enum class ERHI_RESOURCE_MISC_FLAG
{
	GENERATE_MIPS = 0x1L,
	SHARED = 0x2L,
	TEXTURECUBE = 0x4L,
	DRAWINDIRECT_ARGS = 0x10L,
	BUFFER_ALLOW_RAW_VIEWS = 0x20L,
	BUFFER_STRUCTURED = 0x40L,
	RESOURCE_CLAMP = 0x80L,
	SHARED_KEYEDMUTEX = 0x100L,
	GDI_COMPATIBLE = 0x200L,
	SHARED_NTHANDLE = 0x800L,
	RESTRICTED_CONTENT = 0x1000L,
	RESTRICT_SHARED_RESOURCE = 0x2000L,
	RESTRICT_SHARED_RESOURCE_DRIVER = 0x4000L,
	GUARDED = 0x8000L,
	TILE_POOL = 0x20000L,
	TILED = 0x40000L,
	HW_PROTECTED = 0x80000L,
	SHARED_DISPLAYABLE = 0x100000L,
	SHARED_EXCLUSIVE_WRITER = 0x200000L,
	NO_SHADER_ACCESS = 0x400000L
};
ENUM_CLASS_FLAGS(ERHI_RESOURCE_MISC_FLAG);

enum class ERHI_TEXTURE_ADDRESS_MODE
{
	WRAP = 1,
	MIRROR = 2,
	CLAMP = 3,
	BORDER = 4,
	MIRROR_ONCE = 5
};

enum class ERHI_COMPARISON_FUNC
{
	NEVER = 1,
	LESS = 2,
	EQUAL = 3,
	LESS_EQUAL = 4,
	GREATER = 5,
	NOT_EQUAL = 6,
	GREATER_EQUAL = 7,
	ALWAYS = 8
};

enum class ERHI_FILTER
{
	MIN_MAG_MIP_POINT = 0,
	MIN_MAG_POINT_MIP_LINEAR = 0x1,
	MIN_POINT_MAG_LINEAR_MIP_POINT = 0x4,
	MIN_POINT_MAG_MIP_LINEAR = 0x5,
	MIN_LINEAR_MAG_MIP_POINT = 0x10,
	MIN_LINEAR_MAG_POINT_MIP_LINEAR = 0x11,
	MIN_MAG_LINEAR_MIP_POINT = 0x14,
	MIN_MAG_MIP_LINEAR = 0x15,
	ANISOTROPIC = 0x55,
	COMPARISON_MIN_MAG_MIP_POINT = 0x80,
	COMPARISON_MIN_MAG_POINT_MIP_LINEAR = 0x81,
	COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT = 0x84,
	COMPARISON_MIN_POINT_MAG_MIP_LINEAR = 0x85,
	COMPARISON_MIN_LINEAR_MAG_MIP_POINT = 0x90,
	COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR = 0x91,
	COMPARISON_MIN_MAG_LINEAR_MIP_POINT = 0x94,
	COMPARISON_MIN_MAG_MIP_LINEAR = 0x95,
	COMPARISON_ANISOTROPIC = 0xd5,
	MINIMUM_MIN_MAG_MIP_POINT = 0x100,
	MINIMUM_MIN_MAG_POINT_MIP_LINEAR = 0x101,
	MINIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT = 0x104,
	MINIMUM_MIN_POINT_MAG_MIP_LINEAR = 0x105,
	MINIMUM_MIN_LINEAR_MAG_MIP_POINT = 0x110,
	MINIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR = 0x111,
	MINIMUM_MIN_MAG_LINEAR_MIP_POINT = 0x114,
	MINIMUM_MIN_MAG_MIP_LINEAR = 0x115,
	MINIMUM_ANISOTROPIC = 0x155,
	MAXIMUM_MIN_MAG_MIP_POINT = 0x180,
	MAXIMUM_MIN_MAG_POINT_MIP_LINEAR = 0x181,
	MAXIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT = 0x184,
	MAXIMUM_MIN_POINT_MAG_MIP_LINEAR = 0x185,
	MAXIMUM_MIN_LINEAR_MAG_MIP_POINT = 0x190,
	MAXIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR = 0x191,
	MAXIMUM_MIN_MAG_LINEAR_MIP_POINT = 0x194,
	MAXIMUM_MIN_MAG_MIP_LINEAR = 0x195,
	MAXIMUM_ANISOTROPIC = 0x1d5
};
ENUM_CLASS_FLAGS(ERHI_FILTER);