local OBJECT_ID_MAX_VALUE = 65535

function collect_object_info(game_object_npc)
	local result_info = {
		["header"] = "-[Stalker Info]-",
	}
	

	if not game_object_npc or not game_object_npc:id() or not game_object_npc:alive() then
		return result_info
	end

	local storage_data = db.storage[game_object_npc:id()]
	if not storage_data then
		return result_info
	end

	local sobj_npc = alife():object(game_object_npc:id())
	if not sobj_npc or not sobj_npc.id then
		return result_info
	end

	add_to_result(result_info, "Name", game_object_npc:name())
	add_to_result(result_info, "Section", sobj_npc:section_name())
	add_to_result(result_info, "SID", get_object_story_id(game_object_npc:id()))
	add_to_result(result_info, "CLSID", game_object_npc:clsid())
	
	if (sobj_npc.parent_id and sobj_npc.parent_id ~= OBJECT_ID_MAX_VALUE) then 
		add_to_result(result_info, "Parent ID", sobj_npc.parent_id)
	end
	
	if (sobj_npc.group_id and sobj_npc.group_id ~= OBJECT_ID_MAX_VALUE) then 
		add_to_result(result_info, "Squad ID", sobj_npc.group_id)
	end
	
	add_to_result(result_info, "Community", character_community(game_object_npc))
	add_to_result(result_info, "Rank", ranks.get_obj_rank_name(game_object_npc))
	add_to_result(result_info, "Visual", game_object_npc:get_visual_name())
	add_to_result(result_info, "Health", math.floor(game_object_npc.health * 100))
	add_to_result(result_info, "FOV", game_object_npc:fov())
	add_to_result(result_info, "Range", game_object_npc:range())
	add_to_result(result_info, "rx_dont_shoot", storage_data.rx_dont_shoot)
	
	local sight_type = game_object_npc:sight_params()
	add_to_result(result_info, "Sight Type", sight_type and sight_type.m_sight_type)
	
	local smrt = sobj_npc.m_smart_terrain_id and sobj_npc.m_smart_terrain_id ~= OBJECT_ID_MAX_VALUE and alife_object(sobj_npc.m_smart_terrain_id)
	add_to_result(result_info, "m_smart_terrain_id", smrt and smrt:name())
	
	if (smrt) then
		local arriving = smrt.arriving_npc[sobj_npc.id]
		if (arriving) then 
			add_to_result(result_info, "arriving_npc", true)
		end
		
		add_to_result(result_info, "Arrived", arrived_to_smart(sobj_npc, smrt))
		
		local npc_info = smrt.npc_info and smrt.npc_info[sobj_npc.id]
		if (npc_info) then
			add_to_result(result_info, "Job", npc_info.job and npc_info.job.section)
		else 
			add_to_result(result_info, "npc_info", nil)
		end
	end
	
	add_to_result(result_info, "A.Scheme", storage_data.active_scheme)
	add_to_result(result_info, "A.Section", storage_data.active_section)
	add_to_result(result_info, "Logic", storage_data.section_logic)
	add_to_result(result_info, "Ini", storage_data.ini_filename)
	add_to_result(result_info, "AnimState", state_mgr.get_state(game_object_npc))

	local pt_index = game_object_npc.get_current_point_index and game_object_npc:get_current_point_index()
	if (not pt_index or pt_index == 4294967296 ) then
		pt_index = storage_data.active_scheme and (storage_data.active_scheme == "camper" or storage_data.active_scheme == "beh") and load_var(game_object_npc, "path_index", nil)
	end

	if (pt_index) then
		add_to_result(result_info, "PT index", pt_index)
	end

	if (storage_data.corpse_detection and storage_data.corpse_detection.selected_corpse_id) then
		local vo = level.object_by_id(storage_data.corpse_detection.selected_corpse_id)
		if (vo) then
			add_to_result(result_info, "Looting corpse", vo:name())
		end
	end

	if (storage_data.help_wounded and storage_data.help_wounded.selected_id) then
		local vo = level.object_by_id(storage_data.help_wounded.selected_id)
		if (vo) then
			add_to_result(result_info, "Helping wounded", vo:name())
		end
	end

	if (storage_data.gather_items and storage_data.gather_items.selected_id) then
		local vo = level.object_by_id(storage_data.gather_items.selected_id)
		if (vo) then
			add_to_result(result_info, "Picking up", vo:name())
		end
	end

	local vo = game_object_npc:best_enemy()
	if (vo and vo:alive() and IsStalker(vo) and IsWounded(vo)) then
		if (db.storage[vo:id()] and db.storage[vo:id()].victim_surrender and db.storage[vo:id()].victim_surrender < (OBJECT_ID_MAX_VALUE - 1)) then
			add_to_result(result_info, "Kill wounded", vo:name())
		end
	end
	
	local dist = device().cam_pos:distance_to(game_object_npc:position())
	
	add_to_result(result_info, "distance", string.format("%d (%dm)", dist*dist, dist))
	add_to_result(result_info, "OUT RESTR", game_object_npc:out_restrictions())
	add_to_result(result_info, "IN RESTR", game_object_npc:in_restrictions())

	return result_info
end

function add_to_result(_tbl, k, v)
	_tbl[tostring(k)] = tostring(v)
end

function arrived_to_smart(obj,  smart)
	if not (obj and smart) then return false end 
	
	local cls = obj and obj.clsid and obj:clsid()
	if not (cls) then return false end 
	
	local gg = game_graph()
	local obj_gv,  obj_pos = gg:vertex(obj.m_game_vertex_id),  obj.position
	local smart_gv = gg:vertex(smart.m_game_vertex_id)
	
	if obj_gv:level_id() ~= smart_gv:level_id() then
		return false 
	end
	
	if (IsHelicopter(nil, cls)) then return true end 

	local squad = obj.group_id ~= OBJECT_ID_MAX_VALUE and alife_object(obj.group_id)
	if (squad) then
		if (squad.m_game_vertex_id == smart.m_game_vertex_id) then  return true end 
		if (squad.current_target_id and squad.current_target_id == smart.id) then return true end
		if (is_squad_monster[squad.player_id] and squad:get_script_target() == nil) then return squad.position:distance_to_sqr(smart.position) <= 625 end

		return squad.always_arrived or squad.position:distance_to_sqr(smart.position) <= smart.arrive_dist ^ 2
	end 

	return obj_pos:distance_to_sqr(smart.position) <= 2500
end
