name: 'Non-Unity build'

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  build-engine:
    name: 'Build engine'

    strategy:
      matrix:
        system:
          - windows-latest
        preset:
          - Engine
        platform:
          - x64
        config:
          - Release

    runs-on: ${{ matrix.system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Cache packages
        uses: actions/cache@v5
        with:
          key: ${{ matrix.preset }}-NuGet-${{ hashFiles('**/Packages.config') }}
          restore-keys: |
            ${{ matrix.preset }}-NuGet-${{ hashFiles('**/Packages.config') }}
            ${{ matrix.preset }}-NuGet-
          path: |
            ~/.nuget/packages

      - name: Configure engine
        run: |
          cmake `
            --preset ${{ matrix.preset }}-${{ matrix.platform }}-NonUnity

      - name: Build engine
        run: |
          cmake `
            --build `
            --preset ${{ matrix.preset }}-${{ matrix.platform }}-NonUnity-${{ matrix.config }}
